# Aggregate Loss Models

## Introduction

Sub bab ini membahas mengenai pembangunan model probabilitas untuk menggambarkan klaim agregat oleh sistem asuransi yang terjadi dalam periode waktu tertentu. Sistem asuransi dapat berupa polis tunggal, kontrak asuransi kelompok, lini bisnis , atau seluruh buku bisnis perusahaan asuransi. Dalam bab ini, klaim agregat mengacu pada jumlah klaim dari portofolio kontrak asuransi. 

Pertimbangkan portofolio asuransi dari $N$ kontrak individu, dan $S$ menunjukkan kerugian agregat portofolio dalam jangka waktu tertentu. Ada dua pendekatan untuk memodelkan kerugian agregat $S$ , model risiko individu dan model risiko kolektif. Model risiko individu menekankan kerugian dari masing-masing kontrak individu dan mewakili kerugian agregat sebagai:

$$S_n=X_1 +X_2 +\cdots+X_n,$$

Di mana $X_i~(i=1,\ldots,n)$ diinterpretasikan sebagai jumlah kerugian dari $X_i$ kontrak. $N$ menunjukkan jumlah kontrak dalam portofolio dan dengan demikian merupakan angka tetap daripada variabel acak. Untuk model risiko individu, biasanya diasumsikan $X_i$ ini independen. Karena fitur kontrak yang berbeda seperti cakupan dan paparan , $X_i$ belum tentu terdistribusi secara identik. Fitur penting dari distribusi masing-masing $X_i$ adalah massa probabilitas pada nol yang sesuai dengan peristiwa tidak adanya klai

Model risiko kolektif mewakili kerugian agregat dalam hal distribusi frekuensi dan distribusi keparahan:

$$S_N=X_1 +X_2 + \cdots + X_N .$$

Sejumlah klaim acak $N$ yang dapat mewakili baik jumlah kerugian atau jumlah pembayaran. Sebaliknya, dalam model risiko individual biasanya menggunakan sejumlah kontrak tetap $N$.$X_1, X_2, \ldots, X_N$ sebagai representasi dari jumlah masing-masing kerugian. Setiap kerugian mungkin atau mungkin tidak sesuai dengan kontrak unik. 

Misalnya, mungkin ada banyak klaim yang timbul dari satu kontrak. Itu wajar untuk dipikirkan $X_i>0$ karena jika $X_i=0$ maka tidak ada klaim yang terjadi. Biasanya kita menganggap bahwa kondisional pada $X_{1},X_{2},\ldots ,X_{n}$ adalah iid variabel acak. Distribusi dari N dikenal sebagai distribusi frekuensi , dan distribusi umum dari $X$ dikenal sebagai distribusi keparahan . Dengan berasumsi $N$ Dan $X$ sendiri. Dengan model risiko kolektif, sehingga dapat menguraikan kerugian agregat menjadi frekuensi $( N )$ proses dan tingkat keparahan $( X )$ model. Fleksibilitas ini memungkinkan analis untuk mengomentari dua komponen terpisah ini. Misalnya, pertumbuhan penjualan karena standar penjaminan emisi yang lebih rendah dapat menyebabkan frekuensi kerugian yang lebih tinggi tetapi mungkin tidak memengaruhi keparahan. Demikian pula, inflasi atau kekuatan ekonomi lainnya dapat berdampak pada keparahan tetapi tidak pada frekuensi.


## Moments and Distribution

Jadi model risiko keleksif $SN=X_1+...+X_N$ dan tidak bergantung pada N
Misalkan $μ = E(X_i)$ dan $σ^2=Var(X_i)$ untuk semua $i$

Dengan demikian, bersyarat pada `N` kita memiliki ekspektasi jumlah adalah jumlah ekspektasi dan varians.

$$
\begin{aligned}
{\rm E}(S|N) &= {\rm E}(X_1 + \cdots + X_N|N) = \mu N \\
{\rm Var}(S|N) &= {\rm Var}(X_1 + \cdots + X_N|N) = \sigma^2 N.
\end{aligned}
$$

Dengan menggunakan hukum ekspektasi berulang,rata-rata kerugian agregat adalah

${\rm E}(S_N)={\rm E}_N[{\rm E}_S(S|N)] = {\rm E}_N(N\mu) = \mu ~{\rm E}(N).$

Dengan menggunakan hukum varians total, varians dari kerugian agregat adalah

$$
\begin{aligned}
{\rm Var}(S_N) &= {\rm E}_N[{\rm Var}(S_N|N)] + {\rm Var}_N[{\rm E}(S_N|N)] \\
&= \mathrm{E}_N \left[ \sigma^2 N \right] + \mathrm{Var}_N\left[ \mu N \right] \\
&=\sigma^2~{\rm E}[N] + \mu^2~ {\rm Var}[N] .
\end{aligned}
$$

Kasus Khusus: Frekuensi Berdistribusi Poisson. Jika $N∼Poi(λ)$ maka

$$
\begin{aligned}
\mathrm{E}(N) &= \mathrm{Var}(N) = \lambda\\
\mathrm{E}(S_N) &= \lambda ~\mathrm{E}(X)\\
\mathrm{Var}(S_N) &= \lambda (\sigma^2 + \mu^2) = \lambda ~\mathrm{E} (X^2).
\end{aligned}
$$

####  Actuarial Exam Question

Jumlah kecelakaan mengikuti distribusi Poisson dengan rata-rata 12. Setiap kecelakaan menghasilkan 1, 2, atau 3 penuntut dengan probabilitas masing-masing 1/2, 1/3, dan 1/6. Hitunglah varians dalam jumlah total penuntut.

*JAWABAN*

$$
\begin{aligned} 
& \mathrm{E}(X^2) = 1^2 \left( \frac{1}{2}\right) + 2^2\left(\frac{1}{3} \right) + 3^2\left(\frac{1}{6}\right)
= \frac{10}{3} \\
\Rightarrow &\mathrm{Var}(S_N) = \lambda \ \mathrm{E}(X^2) = 12\left(\frac{10}{3}\right) = 40 .
\end{aligned}
$$

Sebagai alternatif, Dapat menggunakan pendekatan umum,
$\mathrm{Var}(S_N) = \sigma^2 \mathrm{E}(N) + \mu^2 \mathrm{Var}(N)$, Dimana

$$
\begin{aligned}
\mathrm{E}(N) &= \mathrm{Var}(N) = 12 \\
\mu &= \mathrm{E}(X) = 1\left(\frac{1}{2}\right) + 2\left(\frac{1}{3}\right) + 3\left(\frac{1}{6}\right)
= \frac{5}{3} \\
\sigma^2 &= \mathrm{E}(X^2) - [\mathrm{E}(X)]^2 = \frac{10}{3} - \frac{25}{9}
= \frac{5}{9} \\
\Rightarrow \ \mathrm{Var}(S_N) &= \left(\frac{5}{9}\right)\left(12\right) + \left(\frac{5}{3}\right)^2\left(12\right) = 40 .
\end{aligned}
$$

Secara umum, momen-momen SN dapat diturunkan dari fungsi pembangkit momen (mgf). Karena $X_i$ adalah iid, dapat dinyatakan mgf dari X sebagai $M_{X(t)}= E(e^{tX})$ . Dengan menggunakan hukum ekspektasi yang diiterasi, mgf dari $S_N$ adalah

$$
\begin{aligned}
M_{S_N}(t) &= \mathrm{E}(e^{t S_N})=\mathrm{E}_N[\mathrm{E}(e^{tS_N}|N)]\\
&= \mathrm{E}_N \left[ ~\mathrm{E}\left( e^{t(X_1+\cdots+X_N)}\right) ~\right] = 
\mathrm{E}_N \left[ \mathrm{E}(e^{tX_1})\cdots\mathrm{E}(e^{tX_N}) \right] ~~ \text{since } X_i \text{'s are independent} \\
&= \mathrm{E}N[~(M{X}(t))^N~] .
\end{aligned}
$$

Lalu dapat melihat fungsi pembangkit probabilitas(pgf) dari `N` adalah $P_N(z)= E(Z^N)$. Dengan menyatakan $M_X(t)=z$, lalu mengganti ke dalam ekspresi untuk mgf dari SN di atas, maka diperoleh

$$
\begin{aligned}
M_{S_N}(t) = \mathrm{E~}(z^N)  = P_{N}(z) = P_{N}[M_{X}(t)].
\end{aligned}
$$
Demikian pula, jika $S_N$ merupakan diskrit, dapat menunjukkan juga pgf dari $S_N$ adalah

$$
\begin{aligned}
P_{S_N}(z) = P_{N}[P_{X}(z)] .
\end{aligned}
$$

Untuk mendapatkan $E(S_N) = M′S_N(0)$ dapat menggunakan aturan rantai:

$M_{S_N}'(t) = \frac{\partial}{\partial t} P_{N}(M_{X}(t)) = P_{N}'(M_{X}(t)) M_{X}'(t)\\$

Lalu Memanggil

$M_{X}(0) = 1, M_{X}'(0) = \mathrm{E}(X) = \mu, P_{N}'(1) = \mathrm{E}(N)$

Jadi,

$\mathrm{E}(S_N) = M_{S_N}'(0) = P_{N}'(M_{X}(0)) M_{X}'(0) = \mu {\rm E}(N) .$

Demikian pula, dapat menggunakan relasi $E(S^2_N) = M′′_{S_N}(0)$ untuk mendapatkan

$\mathrm{Var}(S_N) = \sigma^2 \mathrm{E}(N) + \mu^2 \mathrm{Var}(N).$

**Special Case. Poisson Frequency.**

Misalkan $N∼Poi(λ)$ dengan demikian, pgf dari $N$ adalah $P_N(z) = e^{λ(z-1)}$ dan mgf dari $S_N$ adalah

$$
\begin{aligned}
M_{S_N}(t) &= P_N[M_X(t)] = e^{\lambda(M_{X}(t) - 1)}.
\end{aligned}
$$

Mengambil hasil turunan

$$
\begin{aligned}
M_{S_N}'(t) &= e^{\lambda(M_{X}(t) - 1)}~ \lambda~ M_{X}'(t) = M_{S_N}(t) ~\lambda ~M_{X}'(t)\\
M_{S_N}''(t) &= M_{S_N}(t) ~\lambda~ M_{X}''(t) + [~M_{S_N}(t)~\lambda~ M_{X}'(t)~] ~\lambda~ M_{X}'(t) . 
\end{aligned}
$$
Mengevaluasi hal ini pada t = 0 menghasilkan

$$
\begin{aligned}
\mathrm{E}(S_N) &= M_{S_N}'(0) =  \lambda \mathrm{E}(X) = \lambda \mu
\end{aligned}
$$

Lalu


$$
\begin{aligned} M_{S_N}''(0) &= \lambda \mathrm{E}(X^2) + \lambda^2 \mu^2\\
\Rightarrow \mathrm{Var}(S_N) &= \lambda \mathrm{E}(X^2) + \lambda^2 \mu^2 - (\lambda \mu)^2 = \lambda~ \mathrm{E}(X^2).
\end{aligned}
$$

#### Example 5.3.2. Actuarial Exam Question

Dimisalkan produser acara kuis televisi yang memberikan hadiah uang tunai. Jumlah hadiah(N) dan jumlah hadiah(X) memiliki distribusi sebagai berikut:

$${\small 
\begin{matrix}
\begin{array}{ccccc}\hline
    n & \Pr(N=n) & & x & \Pr(X=x)\\ \hline
    1 & 0.8 & & 0 & 0.2 \\
    2 & 0.2 & & 100 & 0.7 \\
       &       & & 1000 & 0.1\\\hline
  \end{array}
\end{matrix}
}$$

Sehingga Anggaran untuk hadiah sama dengan jumlah hadiah uang tunai yang diharapkan ditambah dengan deviasi standar dari jumlah hadiah uang tunai. Hitung anggaran!

**JAWABAN**

Diperlukan untuk menghitung rata-rata dan standar deviasi dari agregat (jumlah) hadiah uang tunai. Momen-momen dari distribusi frekuensi N adalah

$$
\begin{aligned}
\mathrm{E}(N) &= 1 (0.8) + 2 (0.2) =1.2\\
\mathrm{E}(N^2) &=  1^2 (0.8) + 2^2 (0.2) =1.6\\
\mathrm{Var}(N) &= \mathrm{E}(N^2) - \left[ \mathrm{E}(N) \right]^2= 0.16 .
\end{aligned}
$$
Momen-momen dari distribusi tingkat keparahan X adalah

$$
\begin{aligned}
\mathrm{E}(X) &= 0 (0.2) + 100 (0.7) + 1000 (0.1) = 170 = \mu\\
\mathrm{E}(X^2) &= 0^2 (0.2) + 100^2 (0.7) + 1000^2 (0.1) = 107,000\\
\mathrm{Var}(X) &= \mathrm{E}(X^2) - \left[ \mathrm{E}(X) \right]^2=78,100 = \sigma^2 .
\end{aligned}
$$

Dengan demikian, rata-rata dan varians dari keseluruhan hadiah uang tunai adalah

$$
\begin{aligned}
\mathrm{E}(S_N)  &= \mu \mathrm{E}(N) = 170 (1.2) = 204 \\
\mathrm{Var}(S_N) &= \sigma^2 \mathrm{E}(N) + \mu^2 \mathrm{Var}(N)\\
&= 78,100 (1.2) + 170^2 (0.16) = 98,344 .
\end{aligned}
$$

Sehingga anggaran yang dibutuhkan sebagai berikut


$$
\begin{aligned}
Budget &= \mathrm{E}(S_N) + \sqrt{\mathrm{Var}(S_N)} \\
&= 204 + \sqrt{98,344} = 517.60 .
\end{aligned}
$$


Distribusi $S_N$ disebut distribusi majemuk, dan dapat diturunkan berdasarkan konvolusi $F_X$ sebagai berikut:

$$
\begin{aligned}
F_{S_N}(s) &= \Pr \left(X_1 + \cdots + X_N \le s \right) \\
&=  \mathrm{E} \left[ \Pr \left(X_1 + \cdots + X_N  \le s|N=n \right) \right]\\
&=  \mathrm{E} \left[ F_{X}^{\ast N}(s) \right] \\
&=  p_0 + \sum_{n=1}^{\infty }p_n F_{X}^{\ast n}(s) .
\end{aligned}
$$


Ketika $E(N)$ dan $Var(N)$ diketahui, kita juga dapat menggunakan suatu jenis teorema limit pusat untuk mengestimasi distribusi $S_N$ seperti pada model risiko individu. Yaitu, $\frac{S_N - \mathrm{E}(S_N)}{\sqrt{\mathrm{Var}(S_N)}}$ kira-kira mengikuti distribusi normal standar $N(0,1)$ . Dari jenis teorema limit pusat ini, aproksimasi bekerja dengan baik jika $E[N]$ cukup besar.

### Stop-loss Insurance

Modifikasi pertanggungan pada tingkat polis perorangan Pertanggungan atas kerugian agregat $S_N$ , yang dikenakan sebuah deductible $d$ disebut dengan . Nilai yang diharapkan dari jumlah kerugian agregat yang melebihi deductible,

$$
\begin{eqnarray*}
\mathrm{E}[(S-d)_+]
\end{eqnarray*}
$$

dikenal sebagai premi stop-loss bersih. Untuk menghitung premi stop-loss neto, kita memiliki

$$
\begin{eqnarray*}
\mathrm{E}(S_N-d)_+ 
&=&
\left\{\begin{array}{ll}
\int_{d}^{\infty}(s-d) f_{S_N}(s) ds& \text{for continuous } S_N\\
 \sum_{s>d}(s-d) f_{S_N}(s) & \text{for discrete } S_N\\
 \end{array}\right.\\
&=& \mathrm{E}(S_N) - \mathrm{E}(S_N\wedge d)\\
\end{eqnarray*}
$$
### Actuarial Exam Question

Dalam satu minggu tertentu, jumlah proyek yang mengharuskan Anda bekerja lembur memiliki distribusi geometris dengan $β = 2$ . Untuk setiap proyek, distribusi jumlah jam lembur dalam seminggu, X adalah sebagai berikut

$$
{\small 
\begin{matrix}
\begin{array}{ccc} \hline
    x &  & f(x)\\ \hline
    5 &  & 0.2 \\
    10 & & 0.3 \\
    20 & & 0.5\\ \hline
  \end{array}
\end{matrix}
}
$$  

Jumlah proyek dan jumlah jam lembur tidak bergantung. Anda akan dibayar untuk jam lembur yang melebihi 15 jam dalam seminggu. Hitunglah jumlah jam lembur yang akan  diterima dalam seminggu.

**JAWABAN**

Jumlah proyek dalam seminggu yang membutuhkan kerja lembur memiliki distribusi $N∼Geo(β=2)$ sedangkan jumlah jam kerja lembur per proyek memiliki distribusi $X$ seperti yang telah dijelaskan di atas. Jumlah keseluruhan jam lembur dalam seminggu adalah SN dan oleh karena itu kita mencari

$\mathrm{E}(S_N-15)_+ = \mathrm{E}(S_N) - \mathrm{E}(S_N \wedge 15).$

Untuk mencari $\mathrm{E}(S_N) = \mathrm{E}(X) ~\mathrm{E}(N)$, maka akan didapat

$$
\begin{aligned}
&\mathrm{E}(X) = 5(0.2) + 10(0.3)+ 20(0.5)= 14 \\
&\mathrm{E}(N) = 2 \\
\Rightarrow \ &\mathrm{E}(S) = \mathrm{E}(X) ~ \mathrm{E}(N) = 14(2) = 28 .
\end{aligned}
$$

Untuk mencari $\mathrm{E} (S_N \wedge 15) = 0 \Pr (S_N=0) + 5 \Pr(S_N=5) + 10 \Pr(S_N=10) + 15 \Pr(S_N \geq 15))$, maka akan didapat

$$
\begin{aligned}
\Pr(S_N=0) &= \Pr(N=0) = \frac{1}{1+\beta} = \frac{1}{3} \\
\Pr(S_N=5) &= \Pr(X=5, \ N=1) = 0.2 \left(\frac{2}{9} \right)= \frac{0.4}{9}\\
\Pr(S_N=10) &= \Pr(X=10, \ N=1) + \Pr(X_1=X_2=5, N=2) \\
&= 0.3 \left(\frac{2}{9} \right) + (0.2)(0.2) \left( \frac{4}{27} \right)= 0.0726 \\
\Pr(S_N \geq 15) &= 1 - \left(\frac{1}{3} + \frac{0.4}{9} + 0.0726 \right) = 0.5496\\
\Rightarrow \mathrm{E}(S_N \wedge 15) &= 0 \Pr (S_N=0) + 5 \Pr(S_N=5) + 10 \Pr(S_N=10) + 15 \Pr(S_N \geq 15) \\
&= 0 \left( \frac{1}{3} \right) + 5
\left( \frac{0.4}{9} \right) + 10 (0.0726) + 15 (0.5496) = 9.193 .\\
\end{aligned}
$$

Oleh Karena itu:

$$
\begin{aligned}
\mathrm{E}(S_N-15)_+ &= \mathrm{E}(S_N) - \mathrm{E}(S_N \wedge 15) \\
&= 28 - 9.193 = 18.807 .
\end{aligned}
$$

**Recursive Net Stop-Loss Premium Calculation**

Untuk kasus diskrit, ini dapat dihitung secara rekursif sebagai

$$
\begin{aligned}
\mathrm{E}\left[ \left( S_N-(j+1)h \right) _{+} \right]=\mathrm{E}\left[ ( S_N-jh )_{+} \right] -h \left( 1-F_{S_N}(jh)
\right) .
\end{aligned}
$$

Ini mengasumsikan bahwa dukungan $S_N$ tersebar secara merata di atas unit-unit h.

Untuk menetapkan ini, kita mengasumsikan bahwa $h = 1$ Kita memiliki

$$
\begin{aligned}
\mathrm{E}\left[ \left( S_N-(j+1) \right) _{+} \right] &=\mathrm{E}(S_N) - \mathrm{E}[S_N\wedge (j+1)] \ ,\ \text{ and } \\
\mathrm{E}\left[ \left( S_N - j \right)_+ \right] &=\mathrm{E}(S_N) - \mathrm{E}[S_N\wedge j]
\end{aligned}
$$

Jadi,

$$
\begin{aligned}
\mathrm{E}\left[ \left(S_N-(j+1) \right) _{+}\right] - \mathrm{E}\left[ ( S_N-j )_{+} \right] 
&= \left\{\mathrm{E}(S_N) - \mathrm{E}(S_N\wedge (j+1)) \right\}   -  \left\{\mathrm{E}(S_N) - \mathrm{E}(S_N\wedge j) \right\} \\
&= \mathrm{E}\left(S_N \wedge j \right) - \mathrm{E}\left[ S \wedge (j+1) \right]
\end{aligned}
$$

Maka kita dapat menulis

$$
\begin{aligned}
\mathrm{E}\left[S_N\wedge (j+1)\right] &= \sum_{x=0}^{j}xf_{S_N}(x) + (j+1)~\Pr(S_N \ge j+1) \\
&= \sum_{x=0}^{j-1}x f_{S_N}(x) + j~\Pr(S_N=j) + (j+1)~\Pr(S_N \ge j+1)
\end{aligned}
$$

Demikian pula,

$$
\begin{aligned}
\mathrm{E}(S_N\wedge j) = \sum_{x=0}^{j-1}xf_{S_N}(x) + j~\Pr(S_N\ge j)
\end{aligned}
$$

Dengan ekspresi ini, kami memiliki

$$
\begin{aligned}
& \mathrm{E}\left[ \left( S_N-(j+1) \right) _{+} \right] - \mathrm{E~}\left[ ( S_N-j )_{+} \right]  \\
&= \mathrm{E}\left(S_N \wedge j \right) - \mathrm{E}\left[ S \wedge (j+1) \right] \\
&= \left\{ \sum_{x=0}^{j-1}xf_{S_N}(x) + j~\Pr(S_N\ge j) \right\}
- \left\{ \sum_{x=0}^{j-1}x f_{S_N}(x) + j~\Pr(S_N=j) + (j+1)~\Pr(S_N \ge j+1) \right\} \\
&= j~\left[\Pr(S_N \geq j) - \Pr(S_N=j) \right]- (j+1)~\Pr(S_N \ge j+1) \\
&= j~\Pr( S_N > j) - (j+1)~\Pr(S_N \ge j+1) ~~~~ \text{ (note } \Pr(S_N > j) = \Pr(S_N \geq j+1) \text{)} \\
&= -\Pr(S_N\ge j+1) = -\left[1 - F_{S_N}(j)\right],
\end{aligned}
$$
sesuai kebutuhan.

### Actuarial Exam Question - Continued

Ingatlah bahwa tujuan dari pertanyaan ini adalah untuk menghitung $E(S_N-15)_+$ . Perhatikan bahwa dukungan dari $S_N$ berjarak sama dengan satuan 5, sehingga pertanyaan ini juga dapat dikerjakan secara rekursif, menggunakan ekspresi di atas dengan langkah-langkah $h=5$ :

- Step 1:

$$\begin{aligned}
\mathrm{E~}(S_N-5)_+ &= \mathrm{E}(S_N) - 5 \left[1-\Pr(S_N \leq 5) \right] \
&= 28 - 5 \left(1 - \frac{1}{3}\right) \
&= 28 - 5 \left(\frac{2}{3}\right) \
&= 28 - \frac{10}{3} \
&= \frac{74}{3} \approx 24.6667.
\end{aligned}$$

- Step 2:


$$
\begin{aligned}
\mathrm{E~}(S_N-10)+ &= \mathrm{E~}(S_N-5)+ - 5 \left[1-\Pr(S_N \leq 10) \right] \
&= \frac{74}{3} - 5\left( 1 - \Pr(S_N > 10) \right) \
&= \frac{74}{3} - 5\left( 1 - \Pr(S_N \geq 11) \right) \
&= \frac{74}{3} - 5\left( 1 - \left(1 - \Pr(S_N \leq 10)\right) \right) \
&= \frac{74}{3} - 5\left( 1 - \left(1 - \left(1 - \Pr(S_N > 10)\right)\right) \right) \
&= \frac{74}{3} - 5\left( 1 - \left(1 - \left(1 - \frac{1}{3}\right)\right) \right) \
&= \frac{74}{3} - 5\left( 1 - \left(1 - \frac{1}{3}\right) \right) \
&= \frac{74}{3} - 5\left( \frac{2}{3} \right) \
&= \frac{74}{3} - \frac{10}{3} \
&= \frac{64}{3} \approx 21.3333.
\end{aligned}
$$

- Step 3:

$$
\begin{aligned}
\mathrm{E~}(S_N-15)+ &= \mathrm{E~}(S_N-10)+ - 5 [1-\Pr(S_N \leq 15)] \
&= \mathrm{E~}(S_N-10)_+ - 5\Pr (S_N\ge 15) \
&= \frac{49}{3} - 5 (1 - \Pr(S_N \leq 15)) \
&= \frac{49}{3} - 5 (1 - 0.5596) \
&= \frac{49}{3} - 5 (0.4404) \
&= \frac{49}{3} - 2.202 \
&= \frac{49}{3} - \frac{22.02}{10} \
&= \frac{490 - 220.2}{30} \
&= \frac{269.8}{30} \
&\approx 8.9933.
\end{aligned}
$$

###  Analytic Results

Terdapat beberapa kombinasi distribusi frekuensi klaim dan tingkat keparahan yang menghasilkan distribusi yang mudah dihitung untuk kerugian agregat. Bagian ini memberikan beberapa contoh sederhana. Meskipun contoh-contoh ini mudah dihitung, namun pada umumnya terlalu sederhana untuk digunakan dalam praktik.

####  Example
Salah satunya adalah ekspresi bentuk tertutup untuk distribusi kerugian agregat dengan mengasumsikan distribusi frekuensi geometris dan distribusi tingkat keparahan eksponensial.


Asumsikan bahwa jumlah klaim $N$ adalah geometrik dengan rata-rata $E(N)=β$ dan jumlah klaim $X$ adalah eksponensial dengan $E(X)=θ$ .Dapat diingat bahwa pgf dari N dan pgf dari X adalah:

$$
\begin{aligned}
P_N (z) &=\frac{1}{1- \beta (z-1)}\\
M_{X}(t) &=\frac{1}{1-\theta t} .
\end{aligned}
$$

Dengan demikian, mgf dari kerugian agregat $S_N$ dapat dinyatakan dengan dua cara

$$
\begin{eqnarray}
M_{S_N}(t) &=& P_N [M_{X}(t)] = \frac{1}{1 - \beta \left( \frac{1}{1-\theta t} - 1\right)} \nonumber\\
&=& 1+ \frac{\beta}{1+\beta} \left([1-\theta(1+\beta)t]^{-1}-1 \right)\\
&=& \frac{1}{1+\beta}(1) +\frac{\beta}{1+\beta}
\left( \frac{1}{1-\theta (1+\beta)t}\right) .
\end{eqnarray}
$$

Sehingga, $S_N$ ekuivalen dengan distribusi majemuk $S_N=X^∗_1+⋯+X^∗_N∗$ dengan $N^∗$ adalah Bernoulli dengan rata-rata $β/(1+β)$ dan $X^∗$ adalah eksponensial dengan mean $θ(1+β)$. Untuk melihat hal ini, kita periksa mgf dari S :

$$
\begin{aligned}
M_{S_N}(t) = P_N [M_{X}(t)] = P_{N^{*}} [M_{X^{*}}(t)],
\end{aligned}
$$

Dimana,

$$
\begin{aligned}
P_{N^*} (z) &=1+ \frac{\beta}{1+ \beta} (z-1),\\
M_{X^*} (t) &=\frac{1}{1- {{\theta(1+\beta)}} t}.
\end{aligned}
$$

$S_N$ juga ekuivalen dengan campuran dua titik dari 0 dan $X^∗$. Secara khusus,

$$
\begin{array}{cl}
S_N &=
\left\{
\begin{array}{cl}
0 & {\rm with~ probability ~Pr}(N^*=0) = 1/(1+\beta) \\
Y^{*} & {\rm with~ probability ~Pr}(N^*=1) = \beta/(1+\beta) .
\end{array}
\right.
\end{array}
$$

Fungsi distribusi $S_N$ dalah

$$
\begin{eqnarray*}
\Pr(S_N=0) &=& \frac{1}{1+\beta}\\
\Pr(S_N>s) &=& \Pr(X^*>s) =\frac{\beta}{1+\beta} \exp\left( -\frac{s}{
\theta (1+\beta)}\right)
\end{eqnarray*}
$$

dengan pdf untuk $s>0$

$$
\begin{eqnarray*}
f_{S_N}(s) = \frac{\beta}{\theta (1+\beta)^2}\exp\left( -\frac{s}{
\theta (1+\beta)}\right) .
\end{eqnarray*}
$$

###  Tweedie Distribution
Pada bagian ini, kita akan membahas distribusi gabungan tertentu di mana jumlah klaim memiliki distribusi Poisson dan jumlah klaim memiliki distribusi gamma. Spesifikasi ini menghasilkan apa yang dikenal sebagai distribusi Tweedie. Distribusi Tweedie memiliki probabilitas massa pada nol dan komponen kontinu untuk nilai positif. Karena fitur ini, distribusi ini banyak digunakan dalam pemodelan klaim asuransi, di mana massa nol ditafsirkan sebagai tidak ada klaim dan komponen positif sebagai jumlah klaim. 


Secara khusus, pertimbangkan model risiko kolektif $S_N = X_1 + ⋯ + X_N$. Dengan menganggap bahwa N memiliki distribusi Poisson dengan mean $λ$ dan masing-masing $X_i$ memiliki distribusi gamma dengan parameter bentuk $α$ dan parameter skala $γ$ . Distribusi Tweedie diturunkan sebagai jumlah Poisson dari variabel gamma. Untuk memahami distribusi $S_N$ pertama-tama kita akan melihat probabilitas massa pada nilai nol. Kerugian agregat adalah nol ketika tidak ada klaim yang terjadi, yaitu

${\rm Pr}(S_N=0)= {\rm Pr}(N=0)=e^{-\lambda}.$

Selain itu, perhatikan bahwa $S_N$ bersyarat pada N = n yang dinotasikan dengan $S_n = X_1 + ⋯ + X_n$ mengikuti distribusi gamma dengan bentuk $nα$ dan skala $γ$ . Dengan demikian, untuk $s>0$ densitas dari distribusi Tweedie dapat dihitung sebagai

$$
\begin{aligned}
f_{S_N}(s)&=\sum_{n=1}^{\infty} p_n f_{S_n}(s)\\
&=\sum_{n=1}^{\infty}e^{-\lambda}\frac{(\lambda)^n}{n!}\frac{\gamma^{na}}{\Gamma(n\alpha)}s^{n\alpha-1}e^{-s\gamma} .
\end{aligned}
$$


Dengan demikian, distribusi Tweedie dapat dianggap sebagai campuran antara distribusi nol dan distribusi bernilai positif, yang membuatnya menjadi alat yang mudah digunakan untuk memodelkan klaim asuransi dan untuk menghitung premi murni. Rata-rata dan varians dari model Poisson gabungan Tweedie adalah:

${\rm E} (S_N)=\lambda\frac{\alpha}{\gamma}~~~~{\rm and}~~~~{\rm Var} (S_N)=\lambda\frac{\alpha(1+\alpha)}{\gamma^2}.$

Sebagai fitur penting lainnya, distribusi Tweedie adalah kasus khusus dari model dispersi eksponensial, sebuah kelas model yang digunakan untuk menggambarkan komponen acak dalam model linier umum. Untuk melihat hal ini, kami mempertimbangkan reparameterisasi berikut:

$$
\begin{equation*}
\lambda=\frac{\mu^{2-p}}{\phi(2-p)},~~~~\alpha=\frac{2-p}{p-1},~~~~\frac{1}{\gamma}=\phi(p-1)\mu^{p-1} .
\end{equation*}
$$

Dengan hubungan di atas, kita dapat menunjukkan bahwa distribusi $S_N$ adalah

$f_{S_N}(s)=\exp\left[\frac{1}{\phi}\left(\frac{-s}{(p-1)\mu^{p-1}}-\frac{\mu^{2-p}}{2-p}\right)+C(s;\phi)\right]$

Dimana

$$
C(s;\phi)=\left\{\begin{array}{ll}
                    \displaystyle 0 & {\rm if}~ s=0 \\
                   \displaystyle \log \sum\limits_{n \ge 1} \left\{\frac{(1/\phi)^{1/(p-1)}s^{(2-p)/(p-1)}}{(2-p)(p-1)^{(2-p)/(p-1)}}\right\}^{n}\frac{1}{n!~\Gamma[n(2-p)/(p-1)]s} & {\rm if}~ s>0 .
                  \end{array}\right.
$$

Oleh karena itu, distribusi $S_N$ termasuk ke dalam keluarga eksponensial dengan parameter $μ$ , $ϕ$ , dan $1<p<2$ , dan kita memiliki

${\rm E} (S_N)=\mu~~~~{\rm and}~~~~{\rm Var} (S_N)=\phi\mu^{p}.$

Hal ini memungkinkan kita untuk menggunakan distribusi Tweedie dengan model linear umum untuk memodelkan klaim. Perlu juga disebutkan dua kasus pembatas dari model Tweedie: $p→1$ menghasilkan distribusi Poisson dan $p → 2$ menghasilkan distribusi gamma. Dengan demikian, model Tweedie mengakomodasi situasi di antara distribusi gamma dan Poisson, yang secara intuitif masuk akal karena merupakan jumlah Poisson dari variabel acak gamma.

=======

## 5.4 Menghitung Distribusi Klaim Agregat

Bagian ini membahas dua pendekatan praktis untuk menghitung distribusi kerugian agregat, yaitu metode rekursif dan simulasi.

### metode rekursif

penggunaan metode rekursif untuk membangun model majemuk dengan komponen frekuensi $N$ yang termasuk dalam kelas $(a,b,0)$ atau $(a,b,1)$, dan komponen tingkat keparahan $X$ yang memiliki distribusi diskrit.

Namun, jika distribusi tingkat keparahan $X$ kontinu, praktik yang umum dilakukan adalah mendiskritkan distribusinya terlebih dahulu agar metode rekursif dapat diterapkan.

Dalam hal ini, diasumsikan bahwa N termasuk dalam kelas $(a,b,1)$, sehingga nilai probabilitas $N$ pada waktu $k$ dinyatakan sebagai $pk = (a + bk) pk-1$. Selanjutnya, diasumsikan bahwa support (nilai yang mungkin) dari $X$ terbatas pada ${0,1,...,m}$, dan distribusinya diskrit. Oleh karena itu, fungsi probabilitas dari $S_N$ dapat dinyatakan dalam 

\begin{aligned}
f_{S_N}(s)&=\Pr (S_N=s) \\
&=\frac{1}{1-af_{X}(0)}\left\{ \left[ p_1 -(a+b)p_{0}\right]
f_X (s)+\sum_{x=1}^{s\wedge m}\left( a+\frac{bx}{s} \right) f_X (x)f_{S_N}(s-x)\right\}.
\end{aligned}

Jika $N$ berada dalam kelas $(a,b,0)$ maka $p1 = (a + b)p0$ dan seterusnya

\begin{align*}
f_{S_N}(s)=\frac{1}{1-af_X (0)}\left\{ \sum_{x=1}^{s\wedge m}\left( a+\frac{bx
}{s}\right) f_X (x)f_{S_N}(s-x)\right\}.
\end{align*}

karena model ARIMA yang digunakan berbeda. Persamaan tersebut hanya memperhitungkan faktor skala $a$ dan $b$ dan mengakumulasi probabilitas dari setiap nilai $x$ dari $X$ hingga mencapai nilai $s$ yang diinginkan

#### contoh

Jumlah klaim dalam suatu periode  $N$ memiliki distribusi geometrik dengan mean 4. Besarnya setiap klaim $X$ mengikuti $Pr(X=x)=0.25$, untuk $x=1,2,3,4$. Jumlah klaim dan jumlah klaim bersifat independen. $S_N$ adalah jumlah klaim keseluruhan pada periode tersebut. 

Hitunglah $F_{S_N}(3)$.

Solusi Distribusi tingkat keparahan $X$ adalah sebagai berikut
$f_X(x)=\frac14$,  $x=1,2,3,4$. Distribusi frekuensi $N$ adalah geometris dengan rata-rata 4, yang merupakan anggota dari kelas $(a,b,0)$ dengan $b=0$, $a=\frac\beta{1+\beta}=\frac45$, dan $p0=\frac1{1+\beta}=\frac15$. nilai dari komponen tingkat keparahan $X$ adalah ${1,…,m=4}$, yang bersifat diskrit dan terbatas. Dengan demikian, kita dapat menggunakan metode rekursif

\begin{aligned}
f_{S_N} (x) &= 1 \sum_{y=1}^{x\wedge m} (a+0) f_X (y) f_{S_N} (x-y) \\
&= \frac{4}{5} \sum_{y=1}^{x\wedge m} f_X (y) f_{S_N} (x-y) .
\end{aligned}

Solusi ditemukan dengan menggunakan metode rekursif, di mana fungsi probabilitas $f_{S_N}(x)$ untuk setiap nilai $x$ dihitung menggunakan rumus $f_{S_N}(x) = \sum_{y=1}^{x\wedge m} (a+0) f_X(y) f_{S_N}(x-y)$, di mana $m=4$ adalah nilai maksimum dari distribusi nilai klaim $X$, dan $a=\frac{\beta}{1+\beta}=\frac{4}{5}$ dan $p_0=\frac{1}{1+\beta}=\frac{1}{5}$ adalah parameter dari distribusi frekuensi geometri yang diberikan.

khususnya kita memiliki

\begin{aligned}
f_{S_N} (0) &= \Pr(N=0) = p_0=\frac{1}{5}\\
f_{S_N} (1) &= \frac{4}{5}\sum_{y=1}^{1} f_X (y) f_{S_N} (1-y) = \frac{4}{5} f_X(1) f_{S_N}(0)\\
&= \frac{4}{5}\left( \frac{1}{4}\right)\left(\frac{1}{5} \right) = \frac{1}{25}\\
f_{S_N} (2) &=  \frac{4}{5}\sum_{y=1}^{2} f_X (y) f_{S_N} (2-y) = \frac{4}{5} \left[ f_X(1)f_{S_N}(1) + f_X(2) f_{S_N}(0) \right] \\
&= \frac{4}{5}\left[ \frac{1}{4} \left( \frac{1}{25} + \frac{1}{5}\right) \right] =
\frac{4}{5}\left( \frac{6}{100}\right) = \frac{6}{125}\\
f_{S_N} (3) &= \frac{4}{5} \left[ f_X(1) f_{S_N}(2) + f_X(2)f_{S_N}(1) + f_X(3) f_{S_N}(0) \right]\\
&= \frac{4}{5}\left[ \frac{1}{4} \left( \frac{1}{25} + \frac{1}{5} +
\frac{6}{125}\right) \right] = \frac{1}{5}\left( \frac{5+25+6}{125}\right) = 0.0576\\
\Rightarrow \ F_{S_N} (3) &= f_{S_N} (0)+f_{S_N} (1)+f_{S_N} (2) +f_{S_N} (3) = 0.3456 .
\end{aligned}

Setelah menghitung nilai $f_{S_N}(0)$, $f_{S_N}(1)$, $f_{S_N}(2)$, dan $f_{S_N}(3)$, fungsi distribusi kumulatif $F_{S_N}(3)$ diperoleh dengan menjumlahkan nilai-nilai tersebut. Hasil akhirnya adalah $F_{S_N}(3) = 0.3456$.

### simulasi

Distribusi kerugian agregat dapat dievaluasi dengan menggunakan simulasi Monte Carlo. Untuk kerugian agregat, Simulasi Monte Carlo digunakan untuk menghasilkan sampel acak dari kerugian keseluruhan berdasarkan distribusi probabilitas yang dianggap sesuai untuk distribusi frekuensi dan tingkat keparahan klaim.

gunanya adalah seseorang dapat menghitung distribusi empiris dari $S_N$ dengan menggunakan sampel acak. Nilai ekspektasi dan varians dari kerugian agregat juga dapat diperkirakan dengan menggunakan rata-rata sampel dan varians sampel dari nilai simulasi.

Sekarang kita rangkum prosedur simulasi untuk model kerugian agregat. Misalkan $m$ adalah ukuran sampel acak yang dihasilkan dari kerugian agregat.

Individual Risk Model: $S_n = X_1 + ⋯ + X_n $

- misalkan $j=1,...,m$ menjadi penghitung, dimulai dari $j = 1$
- Hitung setiap realisasi kerugian individu $x_{ij}$ untuk $i=1,...,n$ . Sebagai contoh, hal ini dapat dilakukan dengan menggunakan metode transformasi invers
- Hitung kerugian keseluruhan $s_j = x_{1j} + ⋯ + x_{nj}$.
- terkahir Ulangi dua langkah di atas untuk $j=2,...,m$ untuk mendapatkan sampel berukuran $m$ dari $S_n$, dengan kata lain ${s_1,...,s_m}$.

Collective Risk Model : $S_n = X_1 + ... + X_n$

- misalkan $j=1,...,m$ menjadi penghitung, dimulai dari $j = 1$
- Hitung jumlah klaim $n_j$ dari distribusi frekuensi $N$.
- Diberikan $n_j$, hasilkan jumlah setiap klaim secara independen dari distribusi tingkat keparahan $X$, dilambangkan dengan $x_{1j},...,x_{{n_j}j}$.
- Hitung kerugian keseluruhan $s_j = x_{1j} + ⋯ + x_{{n_j}j}$.
- Ulangi tiga langkah di atas untuk $j=2,...,m$ untuk mendapatkan sampel berukuran $m$ dari $S_N$, dengan kata lain ${s_1,...,s_m}$

Dengan sampel acak $S$, distribusi empiris dapat dihitung sebagai

\begin{aligned}
\hat{F}_S(s)=\frac{1}{m}\sum_{i=1}^{m}I(s_i\leq s),
\end{aligned}

Untuk individual risk model, kerugian keseluruhan dihitung sebagai jumlah kerugian individu yang acak, 

sedangkan untuk collective Risk Model, kerugian keseluruhan dihitung sebagai jumlah kerugian dari sejumlah klaim. 

Dalam kedua kasus, sampel acak dihasilkan dari distribusi probabilitas yang dianggap sesuai, dan kemudian distribusi empiris dari sampel tersebut dihitung untuk memperkirakan distribusi probabilitas dari kerugian agregat.

dimana $I(\cdot)$ adalah fungsi indikator. distribusi empiris $\hat{F}_S(s)$ akan dikonvergen ke ${F}_S(s)$, dikarenakan ukuran sampel $m\rightarrow \infty$

Dalam perhitungannya, asumsi-asumsi awal dibuat tentang distribusi probabilitas dan parameter-parameternya, kemudian model-model ini diestimasi menggunakan data yang tersedia dan kualitas kecocokan model dievaluasi menggunakan alat validasi model. Proses ini memberikan cara yang berguna untuk memperkirakan risiko yang terkait dengan kerugian agregat, dan dapat membantu perusahaan atau organisasi dalam merencanakan dan mengelola risiko mereka.

Prosedur di atas mengasumsikan bahwa distribusi probabilitas, termasuk nilai parameter, dari distribusi frekuensi dan tingkat keparahan telah diketahui. Dalam praktiknya, kita perlu mengasumsikan distribusi-distribusi ini terlebih dahulu, mengestimasi parameter-parameternya dari data, dan kemudian menilai kualitas kecocokan model dengan menggunakan berbagai alat validasi model. Sebagai contoh, asumsi-asumsi dalam model risiko kolektif menyarankan estimasi dua tahap di mana satu model dikembangkan untuk jumlah klaim $N$ dari data jumlah klaim, dan model lainnya dikembangkan untuk tingkat keparahan klaim $X$ dari data jumlah klaim.

