# Premium Foundations

## Pengenalan Ratemaking

***

Pada bagian ini, Anda akan belajar cara:

- Menggambarkan ekspektasi sebagai metode dasar untuk menentukan premi asuransi
- Menganalisis persamaan akuntansi untuk menghubungkan premi dengan kerugian, biaya, dan keuntungan
- Merangkum strategi untuk memperluas penetapan harga untuk mencakup risiko heterogen dan tren dari waktu ke waktu.

***

Bab ini menjelaskan bagaimana menentukan harga yang tepat untuk produk asuransi, yang dikenal sebagai premi. Premi adalah jumlah uang yang dibebankan untuk perlindungan asuransi terhadap kejadian yang tidak pasti. Dalam asuransi, harga/premi ini dikenal sebagai tarif karena dinyatakan dalam unit standar, misalnya harga per seribu dolar pertanggungan atas rumah atau manfaat jika terjadi kematian.

Namun, keunikan asuransi adalah bahwa biaya perlindungan asuransi tidak diketahui pada saat penjualan kontrak. Biaya mungkin tidak terungkap selama berbulan-bulan atau bertahun-tahun, tergantung pada kejadian yang diasuransikan. Oleh karena itu, penetapan harga asuransi berbeda dengan pendekatan ekonomi pada umumnya.

Dalam pendekatan penetapan harga aktuaria tradisional, harga ditentukan sebagai fungsi dari biaya asuransi. Premi dianggap sebagai sumber pendapatan yang menyediakan pembayaran klaim, biaya kontrak, dan margin operasi, yang dapat dirumuskan dalam persamaan akuntansi:

$$\begin{equation}\small{\text{Premium = Loss + Expense + UW Profit} .}\tag{7.1}\end{equation}$$

Namun, ada pasar asuransi di mana harga aktuaria hanya memberikan masukan untuk harga pasar umum. Untuk memperkuat perbedaan ini, premi berbasis biaya aktuaria kadang-kadang dikenal sebagai harga teknis. Oleh karena itu, keputusan perusahaan seperti penetapan harga harus dievaluasi dengan mengacu pada dampaknya terhadap nilai pasar perusahaan. Tujuan ini lebih komprehensif daripada gagasan statis tentang maksimalisasi laba.

Istilah Biaya dapat dibagi menjadi biaya yang bervariasi berdasarkan premi, seperti komisi penjualan, dan yang tidak, seperti biaya bangunan dan gaji karyawan. Istilah Keuntungan UW adalah singkatan dari keuntungan underwriting dan dapat mencakup biaya modal. Persamaan ini berlaku untuk jumlah banyak kontrak, atau portofolio, dan digunakan untuk membantu menetapkan premi, seperti dengan menetapkan tujuan laba.

Istilah kerugian dalam persamaan tersebut didasarkan pada biaya yang diharapkan, karena sulit untuk memprediksi kerugian yang tepat untuk masing-masing kontrak. Namun, teks tersebut mengakui bahwa pendekatan ini mengasumsikan adanya ketidakpastian dan memperkenalkan prinsip-prinsip premi alternatif yang memasukkan ketidakpastian ke dalam penetapan harga. Bab ini juga memperluas pertimbangan penetapan harga ke kumpulan risiko yang heterogen dan membahas perkembangan dan tren pengalaman kerugian untuk mengembangkan tingkat suku bunga ke depan.

Terakhir, bab ini memperkenalkan metode untuk memilih premi dengan membandingkan metode pemeringkatan premi dengan kerugian dari portofolio yang ditahan dan memilih metode yang menghasilkan kecocokan terbaik dengan data yang ditahan. Bab ini juga mencakup suplemen teknis mengenai peraturan pemerintah tentang tarif asuransi.

## Metode Penentuan Tarif Gabungan

***

Pada bagian ini, Anda akan belajar tentang:

- Definisi pure premium sebagai biaya kerugian serta dalam hal frekuensi dan keparahan.
- Menghitung tarif yang diindikasikan menggunakan pure premiums, biaya, dan beban keuntungan.
- Definisi rasio kerugian.
- Menghitung perubahan tarif yang diindikasikan menggunakan rasio kerugian.
- Membandingkan metode pure premium dan rasio kerugian untuk menentukan premi.

Dalam kasus ini, diasumsikan terdapat $n$ kontrak asuransi dengan kerugian (losses) $X1,...,Xn$. Kontrak-kontrak tersebut memiliki distribusi kerugian yang sama dan dianggap sebagai portofolio homogen yang terdiri dari kontrak-kontrak yang sama. Hal ini dapat diterapkan pada asuransi pribadi seperti asuransi mobil atau asuransi rumah di mana perusahaan asuransi menulis banyak kontrak pada risiko yang sangat mirip. Selain itu, asumsi tentang distribusi yang identik tidak terlalu membatasi karena dalam bagian selanjutnya akan diperkenalkan variabel paparan yang memungkinkan pengalaman dapat diskalakan agar dapat dibandingkan. Dalam kasus ini, diasumsikan bahwa $X1,...,Xn$ adalah iid (independen dan identik terdistribusi).

***

### Metode Penghitungan Premi Murni

Dalam metode ini, diperoleh estimasi kerugian yang diharapkan dengan menghitung rata-rata dari kerugian yang terjadi pada seluruh polis dalam suatu kumpulan (n polis).

$$\begin{equation}\small{\mathrm{E}(X) \approx \frac{\sum_{i=1}^n X_i}{n} =\frac{\text{Kerugian}}{\text{Eksposur}} = \text{Premi Murni}.}\end{equation}$$

Dalam kasus risiko homogen, di mana semua polis dianggap sama, jumlah polis n dapat digunakan sebagai ukuran eksposur. Namun, pada Bagian 7.4.1, konsep eksposur diperluas ketika polis tidak memiliki karakteristik yang sama.

Untuk mendapatkan premi murni, kita juga dapat menggunakan pendekatan frekuensi-keparahan. Dalam hal ini, premi murni dihitung sebagai hasil kali antara frekuensi klaim dan besar kerugian.

$$\begin{equation}\small{\text{Premi Murni} = \frac{\text{jumlah klaim}}{\text{Eksposur}} \times\frac{\text{Kerugian}}{\text{jumlah klaim}} = \text{frekuensi} \times \text{keparahan}.}\end{equation}$$

Ketika menggunakan metode premi murni, dapat digunakan baik rata-rata kerugian (biaya kerugian) maupun pendekatan frekuensi-keparahan untuk menentukan premi.

Untuk lebih mendekatkan diri pada aplikasi dalam praktik, sekarang kita kembali ke persamaan (7.1) yang menyertakan biaya. Persamaan (7.1) juga mengacu pada Laba UW untuk laba underwriting. Ketika diskalakan dengan premi, ini dikenal sebagai pembebanan laba. Karena klaim tidak pasti, perusahaan asuransi harus memiliki modal untuk memastikan bahwa semua klaim dibayar. Memegang modal ekstra ini adalah biaya menjalankan bisnis, investor di perusahaan perlu dikompensasi untuk ini, dengan demikian pemuatan ekstra.

Sekarang kita menguraikan Beban menjadi beban yang bervariasi berdasarkan premi, Variabel, beban yang tidak bervariasi,dan Premi Tetap, sehingga Beban = Variabel + Premi Tetap. Dengan menganggap biaya variabel dan laba sebagai bagian dari premi, kita mendefinisikan

$$\begin{equation}\small{V =  \frac{\text{Variable}}{\text{Premium}} ~~~ \text{and}~~~Q = \frac{\text{UWProfit}}{\text{Premium}} ~.}\end{equation}$$

Dengan definisi dan persamaan (7.1) ini, kita dapat menulis

$$\begin{equation}\small{\begin{matrix}\begin{array}{ll}\text{Premium} &= \text{Losses + Fixed} + \text{Premium} \times \frac{\text{Variable + UW Profit}}{\text{Premium}}  \\& = \text{Losses + Fixed} + \text{Premium} \times (V+Q) .\end{array}\end{matrix}}\end{equation}$$

Penyelesaian untuk hasil premi

$$\begin{equation}\small{\text{Premium} = \frac{\text{Losses + Fixed}}{1-V-Q} .}\end{equation}$$

Dibagi dengan eksposur, tarif dapat dihitung sebagai

$$\begin{equation}\begin{matrix}\begin{array}{ll}\text{Rate} &= \frac{\text{Premium}}{\text{Exposure}} = \frac{\text{Losses/Exposure + Fixed/Exposure}}{1-V-Q} \\&=   \frac{\text{Pure Premium + Fixed/Exposure}}{1-V-Q} ~.\end{array}\end{matrix}\end{equation}$$

Dengan kata lain, ini adalah

$$\begin{equation}\small{\text{Rate} =\frac{\text{pure premium + fixed expense per exposure}}{\text{1 - variable expense factor - profit and contingencies factor}}  .}\end{equation}$$

### Metode Rasio Kerugian

Rasio kerugian adalah rasio jumlah kerugian terhadap premi

$$\begin{equation}\small{\text{Loss Ratio} = \frac{\text{Loss}}{\text{Premium}} .}\end{equation}$$

Ketika menentukan premi, agak berlawanan dengan intuisi untuk menekankan rasio ini karena komponen premi dimasukkan ke dalam penyebut. Seperti yang akan kita lihat, metode rasio kerugian mengembangkan perubahan tingkat daripada tingkat; kita dapat menggunakan perubahan tingkat untuk memperbarui pengalaman masa lalu untuk mendapatkan tingkat saat ini. Untuk melakukan hal ini, perubahan tingkat terdiri dari rasio rasio kerugian pengalaman terhadap rasio kerugian target. Faktor penyesuaian ini kemudian diterapkan pada rate saat ini untuk mendapatkan rate yang baru.

Untuk melihat cara kerjanya dalam konteks yang sederhana, mari kita kembali ke persamaan (7.1) tetapi sekarang abaikan biaya untuk mendapatkan $ Premi = Kerugian + Keuntungan UW $. Membagi dengan premi menghasilkan

$$\begin{equation}\small{\frac{\text{UW Profit}}{\text{Premium}} = 1 - LR = 1 -\frac{\text{Loss}}{\text{Premium}} .}\end{equation}$$

Misalkan kita memiliki pemuatan laba "target" baru, katakanlah $Q_{target}$ . Dengan asumsi bahwa kerugian, eksposur, dan hal-hal lain mengenai kontrak tetap sama, maka untuk mencapai target pemuatan laba yang baru, kita akan menyesuaikan premi. Gunakan ICF untuk faktor perubahan yang ditunjukkan yang didefinisikan melalui ekspresi

$$\begin{equation}\small{\frac{\text{New UW Profit}}{\text{Premium}} = Q_{target} =  1 -\frac{\text{Loss}}{ICF\times \text{Premium}}.}\end{equation}$$

Menyelesaikan untuk $ICF$, kita mendapatkan

$$\small{
ICF =  \frac{\text{Loss}}{\text{Premium} \times (1-Q_{target})} = \frac{LR}{1-Q_{target}}.
}$$

Jadi, sebagai contoh, jika kita memiliki rasio kerugian saat ini = 85% dan target keuntungan $Q_{target} = 0,20$, maka $ICF = 0,85/0,80 = 1,0625$, yang berarti kita meningkatkan premi sebesar 6,25%.

Sekarang mari kita lihat bagaimana hal ini bekerja dengan biaya dalam persamaan (7.1). Kita dapat menggunakan pengembangan yang sama seperti pada Bagian 7.2.1 dan mulai dengan persamaan (7.2), selesaikan pembebanan laba untuk mendapatkan

$$\begin{equation}\small{Q = 1 - \frac{\text{Loss+Fixed}}{\text{Premium}} - V .}\end{equation}$$

Kita menginterpretasikan kuantitas $Rugi + Premi Tetap + V$ sebagai "rasio biaya operasional". Sekarang, tetapkan persentase keuntungan Q pada target dan sesuaikan premi melalui "faktor perubahan yang ditunjukkan" $ ICF

$$\begin{equation}\small{Q_{target} = 1-\frac{\text{Loss + Fixed}}{\text{Premium}\times ICF} - V .}\end{equation}$$

Menyelesaikan untuk hasil $ ICF$

$$\begin{equation}{\small\begin{array}{ll}ICF &= \frac{\text{Loss + Fixed}}{\text{Premium} \times (1 - V -Q_{target})} \\&= \frac{\text{Loss Ratio + Fixed Expense Ratio}}{1 - V - Q_{target}} .\end{array}}\end{equation}$$

Contoh. Faktor Perubahan Indikasi Rasio Kerugian. Anggap informasi berikut:

- Proyeksi rasio kerugian dan LAE akhir = 65%
- Proyeksi rasio biaya tetap = 6,5%
- Biaya variabel = 25%
- Target keuntungan UW = 10%

Dengan asumsi ini, dengan persamaan (7.3), faktor perubahan yang diindikasikan dapat dihitung sebagai berikut:

$$\small{ICF = \frac{\text{(Losses + Fixed)}/\text{Premium}}{ 1 - V - Q_{target}} = \frac{0.65 + 0.065}{1-0.25- 0.10} = 1.10 .}$$

Ini berarti tingkat tarif rata-rata secara keseluruhan harus dinaikkan sebesar 10%.


## Prinsip-prinsip Penetapan Harga

Di bagian ini, Anda akan belajar cara:

- Menjelaskan prinsip-prinsip harga aktuarial yang umum
- Menjelaskan sifat-sifat dari prinsip-prinsip harga
- Memilih prinsip harga berdasarkan sifat yang diinginkan.

***

Pendekatan dalam penetapan harga berbeda-beda tergantung pada jenis kontrak. Sebagai contoh, produk mobil pribadi adalah produk yang tersedia secara luas di seluruh dunia dan dikenal sebagai bagian dari pasar asuransi umum ritel di Inggris. Di sini, kita dapat mengharapkan penetapan harga berdasarkan sejumlah besar kontrak independen, situasi di mana harapan kerugian memberikan titik awal yang sangat baik. Sebaliknya, seorang aktuaris mungkin ingin menetapkan harga untuk kontrak asuransi yang dikeluarkan kepada majikan besar yang mencakup manfaat kesehatan yang kompleks bagi ribuan karyawan. Dalam contoh ini, pengetahuan tentang seluruh distribusi kerugian potensial, bukan hanya nilai yang diharapkan, sangat penting untuk memulai negosiasi penetapan harga. Untuk mencakup berbagai aplikasi potensial, bagian ini menjelaskan prinsip-prinsip premi umum dan sifat-sifatnya yang dapat digunakan untuk memutuskan apakah suatu prinsip tertentu dapat diterapkan dalam situasi yang diberikan atau tidak.

### Prinsip-Prinsip Premi

Bab ini memperkenalkan prinsip-prinsip penetapan harga aktuarial tradisional yang menyediakan harga berdasarkan distribusi kerugian asuransi saja; harga tidak tergantung pada permintaan asuransi atau aspek biaya lainnya seperti biaya-biaya. Diasumsikan bahwa kerugian $X$ memiliki fungsi distribusi $F(⋅)$
dan bahwa ada beberapa aturan (yang dalam matematika dikenal sebagai fungsi), katakanlah $H$, yang mengambil $F(⋅)$ ke dalam garis bilangan real positif, dilambangkan sebagai $P=H(F)$. Untuk tujuan notasi, seringkali lebih nyaman untuk menggantikan variabel acak $X$ dengan fungsinya dan menuliskan $P=H(X)$. Tabel 7.1 menyediakan beberapa contoh.

**Tabel 7.1.** Prinsip-Prinsip Premi yang Umum

$$\small{
\begin{array}{ll}
\text{Description } & \text{Definition } (H(X)) \\\hline
\text{Net (pure) premium} &  {\rm E}[X] \\
\text{Expected value} & (1+\alpha){\rm E}[X]\\
\text{Standard deviation}  & {\rm E}[X]+\alpha ~SD(X)\\
\text{Variance} & {\rm E}[X]+\alpha ~{\rm Var}(X)\\
\text{Zero utility}  & \text{solution of }u(w) = {\rm E} [u(w + P - X)]\\
\text{Exponential}  & \frac{1}{\alpha} \log {\rm E} [e^{\alpha X}]\\
\hline
\end{array}
}$$

Sebuah prinsip premi mirip dengan *ukuran risiko* yang diperkenalkan pada Bagian 10.3. Secara matematis, keduanya adalah aturan yang memetakan variabel acak kerugian yang diminati menjadi nilai numerik. Dari sudut pandang praktis, prinsip premi memberikan panduan seberapa banyak asuransi akan membebankan biaya untuk menerima risiko $X$. Sebaliknya, ukuran risiko mengkuantifikasi tingkat ketidakpastian, atau tingkat risiko, yang dapat digunakan oleh asuransi untuk memutuskan tingkat modal yang harus dipertahankan untuk tetap solvent.

Premi net, atau murni, pada dasarnya mengasumsikan tidak adanya ketidakpastian. Prinsip nilai harapan, deviasi standar, dan varian masing-masing menambahkan beban eksplisit untuk ketidakpastian melalui parameter risiko $α≥0$. Untuk prinsip nol utilitas, kita menganggap perusahaan asuransi dengan fungsi utilitas $u(⋅)$ dan kekayaan *w* sama-sama tidak peduli untuk menerima dan tidak menerima risiko $X$. Dalam hal ini, $P$ dikenal sebagai harga kesetaraan atau, dalam ekonomi, harga reservasi. Dengan utilitas eksponensial, prinsip nol utilitas berkurang menjadi prinsip premi eksponensial, yaitu, mengasumsikan $u(x)=(1−e−αx)/α$.

Untuk nilai parameter risiko yang kecil, prinsip varian hampir sama dengan prinsip premi eksponensial, seperti yang diilustrasikan dalam kasus khusus berikut.

### Sifat Prinsip Premium

Sifat-sifat dari prinsip-prinsip premi membantu memandu pemilihan prinsip premi dalam aplikasi. Tabel 7.2 menyediakan contoh-contoh sifat-sifat dari prinsip-prinsip premi.

**Tabel 7.2.** Properti Umum dari Prinsip-prinsip Premium.

$$\small{
\begin{array}{ll}
\text{Description } & \text{Definition }\\\hline
\text{Nonnegative loading} & H(X) \ge {\rm E}[X] \\
\text{Additivity} & H(X_1+X_2) = H(X_1) + H(X_2), \text{ for independent }X_1, X_2  \\
\text{Scale invariance}  & H(cX) = c H(X), \text{ for }c \ge 0 \\
\text{Consistency} & H(c+X) = c + H(X)\\
\text{No rip-off }  & H(X) \le \max \{X\}\\
\hline
\end{array}
}$$

Ini hanya merupakan subset dari banyak properti yang dikutip dalam literatur aktuaria. Sebagai contoh, makalah tinjauan dari Young (2014) mencantumkan 15 properti. Lihat juga properti yang dijelaskan sebagai aksioma kohesif yang kami perkenalkan untuk pengukur risiko dalam Bagian 10.3.

Beberapa properti yang tercantum di Tabel 7.2 ringan dalam arti bahwa properti tersebut hampir selalu terpenuhi. Misalnya, properti tidak ada penipuan menunjukkan bahwa biaya premi akan lebih kecil dari nilai kerugian maksimal $X$ (di sini, kami menggunakan notasi $max{X}$ untuk nilai maksimal ini yang didefinisikan sebagai "essential supremum" dalam matematika). Properti lain mungkin tidak begitu ringan. Sebagai contoh, untuk portofolio risiko independen, aktuaris mungkin ingin agar properti aditivitas terpenuhi. Mudah dilihat bahwa properti ini terpenuhi untuk prinsip premi nilai harapan, varians, dan eksponensial tetapi tidak untuk prinsip simpangan baku. Contoh lain adalah properti konsistensi yang tidak terpenuhi untuk prinsip nilai harapan ketika parameter pemuatan risiko $α$ positif.

Prinsip invariansi skala dikenal sebagai homogenitas derajat satu dalam ekonomi. Misalnya, ini memungkinkan kita untuk bekerja dengan mata uang yang berbeda (misalnya, dari dolar ke euro) serta sejumlah aplikasi lainnya dan akan dibahas lebih lanjut dalam Bagian 7.4 berikutnya. Meskipun prinsip yang secara umum diterima, kami mencatat bahwa prinsip ini tidak berlaku untuk nilai besar $X$ yang mungkin berbatasan dengan kendala surplus dari perusahaan asuransi; jika perusahaan asuransi memiliki probabilitas besar menjadi tidak likuid, maka perusahaan asuransi tersebut mungkin tidak ingin menggunakan penetapan harga linear. Mudah diperiksa bahwa prinsip ini terpenuhi untuk prinsip nilai harapan dan simpangan baku, meskipun tidak untuk prinsip varians dan eksponensial.

## Risiko Heterogen
***

Di bagian ini, Anda akan belajar bagaimana:

- Mendeskripsikan paparan asuransi dalam hal distribusi skala
- Menjelaskan paparan dalam hal jenis-jenis asuransi umum seperti asuransi mobil dan asuransi pemilik rumah
- Mendeskripsikan bagaimana faktor rating dapat digunakan untuk memperhitungkan heterogenitas di antara risiko dalam suatu kumpulan
- Mengukur dampak faktor rating melalui relativitas

***

Seperti yang dicatat di Bagian 7.1, terdapat banyak variasi dalam risiko yang diasuransikan, fitur kontrak, dan orang yang diasuransikan. Sebagai contoh, Anda mungkin memiliki saudara kembar yang bekerja di kota yang sama dan menghasilkan jumlah uang yang relatif sama. Namun, ketika memilih pilihan dalam asuransi sewa untuk mengasuransikan isi apartemen Anda, Anda dapat membayangkan perbedaan dalam jumlah isi yang akan diasuransikan, pilihan deductible untuk jumlah risiko yang ditanggung, dan mungkin juga perbedaan tingkat ketidakpastian mengingat tingkat keamanan lingkungan tempat tinggal Anda. Orang-orang dan risiko yang mereka asuransikan berbeda.

Ketika memikirkan tentang kumpulan risiko yang berbeda (heterogen), satu opsi adalah untuk menetapkan harga sama untuk semua risiko. Hal ini umum terjadi dalam program asuransi banjir atau kesehatan yang disponsori oleh pemerintah. Namun, hal ini juga umum terjadi untuk menetapkan harga yang berbeda di mana perbedaan tersebut sebanding dengan risiko yang diasuransikan.

### Paparan Risiko

Salah satu cara untuk membuat risiko heterogen dapat dibandingkan adalah melalui konsep exposure. Untuk menjelaskan exposure, mari gunakan distribusi skala yang telah dipelajari pada Bab 3. Untuk mengingat kembali distribusi skala, misalkan $X$ memiliki distribusi parametrik dan kita mendefinisikan versi yang diskalakan sebagai $R=X/E, E>0$ . Jika $R$ ada dalam keluarga parametrik yang sama dengan $X$ , maka distribusinya dikatakan sebagai distribusi skala. Seperti yang telah kita lihat, distribusi gamma, eksponensial, dan Pareto adalah contoh dari distribusi skala.

Secara intuitif, ide di balik exposure adalah untuk membuat risiko lebih dapat dibandingkan satu sama lain. Misalnya, mungkin terdapat risiko $X_1,...,X_n$ berasal dari distribusi yang berbeda dan namun, dengan memilih exposure yang tepat, tarif $R_1,...,R_n$ berasal dari distribusi yang sama. Di sini, kita menafsirkan tarif $R_i=X_i/E_i$ sebagai kerugian dibagi dengan exposure.

Tabel 7.3 menyediakan beberapa contoh. Kami mencatat bahwa tabel ini mengacu pada tahun mobil dan rumah yang "diperoleh", konsep yang akan dijelaskan di Bagian 7.5.

**Tabel 7.3.** Paparan yang Biasa Digunakan dalam Jenis Asuransi yang Berbeda.

$$\small{
\begin{matrix}
\begin{array}{ll}
\text{Type of Insurance} & \text{Exposure Basis} \\\hline
\text{Personal Automobile} &  \text{Earned Car Year, Amount of Insurance Coverage} \\
\text{Homeowners} &  \text{Earned House Year, Amount of Insurance Coverage}\\
\text{Workers Compensation}  & \text{Payroll}\\
\text{Commercial General Liability} &  \text{Sales Revenue, Payroll, Square Footage, Number of Units}\\
\text{Commercial Business Property}  & \text{Amount of Insurance Coverage}\\
\text{Physician's Professional Liability}  & \text{Number of Physician Years}\\
\text{Professional Liability}  & \text{Number of Professionals (e.g., Lawyers or Accountants)}\\
\text{Personal Articles Floater} &  \text{Value of Item} \\
  \hline
\end{array}
\end{matrix}
}$$

Sebuah paparan adalah jenis faktor penilaian, konsep yang kami definisikan secara eksplisit di Bagian selanjutnya, yaitu 7.4.2. Biasanya, ini adalah faktor penilaian yang paling penting, sangat penting sehingga premi dan kerugian dikutip secara "per paparan".

Untuk pemodelan frekuensi dan keparahan, biasanya dipikirkan bahwa aspek frekuensi proporsional terhadap paparan dan aspek keparahan dalam hal kerugian per klaim (tidak bergantung pada paparan). Namun, hal ini tidak mencakup seluruh cerita. Untuk banyak jenis bisnis, paparan yang proporsional terhadap inflasi sangat nyaman. Inflasi biasanya dilihat sebagai tidak terkait dengan frekuensi tetapi proporsional terhadap keparahan.

**Kriteria untuk Memilih Paparan**

Sebuah dasar paparan harus memenuhi kriteria berikut. Ini harus:

- menjadi ukuran yang akurat dari paparan kuantitatif terhadap kerugian,
- mudah bagi perusahaan asuransi untuk menentukan (pada saat kebijakan dimulai) dan tidak dapat dimanipulasi oleh tertanggung,
- mudah dipahami oleh tertanggung dan dapat dihitung oleh perusahaan asuransi,
memperhatikan setiap dasar paparan yang ada sebelumnya yang telah ditetapkan dalam industri, dan
- untuk beberapa jenis bisnis, proporsional terhadap inflasi. Dengan cara ini, tarif tidak sensitif terhadap perubahan nilai uang dari waktu ke waktu karena perubahan ini tercakup dalam dasar paparan.

Untuk menjelaskan, pertimbangkan cakupan mobil pribadi. Sebagai gantinya dari dasar paparan "tahun mobil yang diperoleh", sebuah ukuran yang lebih akurat dari paparan kuantitatif terhadap kerugian mungkin adalah jumlah mil yang dikemudikan. Secara historis, pengukuran ini sulit ditentukan pada saat kebijakan diterbitkan dan rentan terhadap manipulasi oleh tertanggung sehingga masih tidak biasa digunakan. Perangkat modern telematika yang memungkinkan pencatatan mil yang akurat sedang mengubah penggunaan variabel ini di beberapa pasar.

Sebagai contoh lain, ukuran paparan dalam properti bisnis komersial, misalnya asuransi kebakaran, umumnya adalah jumlah cakupan asuransi. Ketika nilai properti tumbuh dengan inflasi, jumlah cakupan asuransi juga akan bertambah. Dengan demikian, tarif yang dikutip per jumlah cakupan asuransi kurang sensitif terhadap inflasi daripada sebaliknya.

### Faktor Penilaian

Faktor penilaian, atau variabel penilaian, adalah karakteristik dari pemegang polis atau risiko yang diasuransikan yang mempengaruhi tarif. Sebagai contoh, ketika Anda membeli asuransi mobil, kemungkinan perusahaan asuransi memiliki tarif yang berbeda berdasarkan usia, jenis kelamin, jenis mobil, tempat parkir mobil, riwayat kecelakaan, dan sebagainya. Variabel-variabel ini dikenal sebagai faktor penilaian. Meskipun beberapa variabel dapat bersifat kontinu, seperti usia, sebagian besar bersifat kategorikal - faktor adalah label yang digunakan untuk variabel kategorikal. Bahkan, bahkan dengan variabel kontinu seperti usia, umumnya dilakukan kategorisasi dengan membuat kelompok seperti "muda", "menengah", dan "tua" untuk tujuan penilaian.

*Tabel 7.4* hanya memberikan sedikit contoh. Di banyak yurisdiksi, pasar asuransi pribadi (seperti asuransi mobil dan rumah) sangat kompetitif - menggunakan 10 atau 20 variabel untuk tujuan penilaian tidak jarang terjadi.

Tabel 7.4. *Faktor Penilaian yang Umum Digunakan dalam Jenis Asuransi yang Berbeda.*

$$\small{
\begin{matrix}
\begin{array}{l|l}\hline
\text{Type of Insurance} & \text{Rating Factors}\\\hline\hline
\text{Personal Automobile}  & \text{Driver Age and Gender, Model Year, Accident History}\\
\text{Homeowners}  & \text{Amount of Insurance, Age of Home, Construction Type}\\
\text{Workers Compensation}  & \text{Occupation Class Code}\\
\text{Commercial General Liability}  & \text{Classification, Territory, Limit of Liability}\\
\text{Medical Malpractice}  & \text{Specialty, Territory, Limit of Liability}\\
\text{Commercial Automobile}  & \text{Driver Class, Territory, Limit of Liability}\\
  \hline
\end{array}
\end{matrix}
}$$

*Contoh. Kerugian dan Premi Berdasarkan Jumlah Asuransi dan Wilayah*. Untuk mengilustrasikan, Tabel 7.5 menyajikan satu set data fiktif kecil dari Werner dan Modlin (2016). Data terdiri dari kerugian dan biaya penyesuaian kerugian (LossLAE), yang didekomposisi berdasarkan tiga tingkat jumlah asuransi (AOI), dan tiga wilayah (Terr). Untuk setiap kombinasi AOI dan Terr, kami juga memiliki jumlah kebijakan yang dikeluarkan, yang diberikan sebagai Exposure.

Tabel 7.5. *Kerugian dan Premi Berdasarkan Jumlah Asuransi dan Wilayah.*

$$\small{
\begin{matrix}
\begin{array}{cc|rrr}
\hline
       AOI &       Terr &   Exposure &    LossLAE &    Premium \\\hline
       \text{Low} &          1 &          7 &     210.93 &     335.99 \\
    \text{Medium} &          1 &        108 &   4,458.05 &   6,479.87 \\
      \text{High} &          1 &        179 &  10,565.98 &  14,498.71 \\\hline
       \text{Low} &          2 &        130 &   6,206.12 &  10,399.79 \\
    \text{Medium} &          2 &        126 &   8,239.95 &  12,599.75 \\
      \text{High} &          2 &        129 &  12,063.68 &  17,414.65 \\\hline
       \text{Low} &          3 &        143 &   8,441.25 &  14,871.70 \\
    \text{Medium} &          3 &        126 &  10,188.70 &  16,379.68 \\
      \text{High} &          3 &         40 &   4,625.34 &   7,019.86 \\
      \hline
       \text{Total}    &       & 988 &  65,000.00 &     99,664.01   \\\hline
\hline
\end{array}
\end{matrix}
}$$

Dalam kasus ini, faktor penilaian AOI dan Terr menghasilkan sembilan sel. Perhatikan bahwa kita dapat menggabungkan sel "wilayah satu dengan jumlah asuransi rendah" dengan sel lain karena hanya ada 7 kebijakan di sel tersebut. Melakukan hal ini adalah wajar - pertimbangan semacam ini merupakan salah satu tugas utama analis. Garis besar dalam pemilihan variabel dijelaskan pada Bab 8, termasuk Pelengkap Teknis TS 8.B. Sebagai alternatif, kita juga dapat memperkuat informasi tentang sel (Terr 1, AOI Rendah) dengan "meminjam" informasi dari sel tetangga (misalnya, wilayah lain dengan AOI yang sama, atau jumlah AOI yang berbeda di dalam Terr 1). Ini adalah subjek kredibilitas yang diperkenalkan dalam Bab 9.

***

Untuk memahami dampak faktor penilaian, umumnya digunakan relatif. Relatif membandingkan risiko yang diharapkan pada tingkat faktor penilaian tertentu dengan nilai dasar yang diterima. Dalam buku ini, kami bekerja dengan relatif yang didefinisikan melalui rasio; juga mungkin untuk mendefinisikan relatif melalui selisih aritmatika. Oleh karena itu, relatif kami didefinisikan sebagai:

$$\text{Relativity}_j = \frac{\text{(Loss/Exposure)}_j}{\text{(Loss/Exposure)}_{Base}} .$$

***

*Contoh. Kerugian dan Premi Berdasarkan Jumlah Asuransi dan Wilayah - Lanjutan*. Metode klasifikasi tradisional hanya mempertimbangkan satu variabel klasifikasi pada satu waktu - mereka univariat. Oleh karena itu, jika kami ingin mendapatkan relatif untuk kerugian dan biaya penyesuaian kerugian (LossLAE) berdasarkan jumlah asuransi, kami mungkin akan menjumlahkan wilayah untuk mendapatkan informasi yang ditampilkan di Tabel 7.6.

Tabel 7.6. *Kerugian dan Relatifitas berdasarkan Jumlah Asuransi*.

$$\small{
\begin{matrix}
\begin{array}{c|rrrr}
\hline
       AOI &   Exposure &    LossLAE & Loss/Exp &Relativity \\\hline
       \text{Low} &        280 &    14858.3 &   53.065   &0.835 \\
    \text{Medium} &        360 &    22886.7 &    63.574  &1.000 \\
      \text{High} &        348 &      27255.0 &   78.319  & 1.232 \\\hline
       \text{Total}    &        988 &  65,000.0 &            \\\hline
\hline
\end{array}
\end{matrix}
}$$

Oleh karena itu, kerugian dan biaya penyesuaian kerugian per unit paparan adalah 23,2% lebih tinggi untuk risiko dengan jumlah asuransi tinggi dibandingkan dengan yang memiliki jumlah asuransi sedang. Relatifitas ini tidak mengontrol wilayah.

***

Pengenalan faktor rating memungkinkan analis untuk membuat sel yang mendefinisikan koleksi risiko kecil - tujuannya adalah memilih kombinasi faktor rating yang tepat sehingga semua risiko dalam sel dapat diperlakukan secara sama. Dalam terminologi statistik, kita ingin semua risiko dalam sel memiliki distribusi yang sama (tergantung pada penskalaan oleh variabel paparan). Ini adalah dasar dari penetapan harga asuransi. Semua risiko dalam sel memiliki harga yang sama per paparan, namun risiko dari sel yang berbeda dapat memiliki harga yang berbeda.

Dengan kata lain, perusahaan asuransi diizinkan untuk menetapkan tarif yang berbeda untuk risiko yang berbeda; diskriminasi risiko legal dan dilakukan secara rutin. Namun demikian, dasar diskriminasi, pemilihan faktor risiko, adalah subjek dari debat yang luas. Komunitas aktuaria, manajemen asuransi, regulator, dan advokat konsumen semua merupakan peserta aktif dalam debat ini. Lampiran Teknis TS 7.A menjelaskan masalah ini dari sudut pandang regulasi.

Selain kriteria statistik untuk menilai signifikansi faktor rating, analis harus memperhatikan masalah bisnis perusahaan (misalnya, apakah mahal untuk menerapkan faktor rating?), kriteria sosial (apakah variabel berada di bawah kendali pemegang polis?), kriteria hukum (apakah ada regulasi yang melarang penggunaan faktor rating seperti gender?), dan masalah sosial lainnya. Pertanyaan-pertanyaan ini sebagian besar di luar cakupan teks ini. Namun demikian, karena mereka sangat mendasar untuk penetapan harga asuransi, gambaran singkat diberikan di Bab 8, termasuk Lampiran Teknis TS 8.B.
