# Experience Rating Using Credibility Theory
## Pengantar Aplikasi Teori Kredibilitas

Berapa premi yang harus dibebankan untuk menyediakan asuransi? Jawabannya tergantung pada eksposur risiko kerugian. Metode yang umum digunakan untuk menghitung premi asuransi adalah dengan menilai tertanggung menggunakan <abbr title="Rencana pemeringkatan yang menggunakan karakterisitik risiko tertanggung untuk menentukan">**rencana peringkat klasifikasi**.</abbr>  Rencana klasifikasi digunakan untuk memilih tarif asuransi berdasarkan karakteristik peringkat tertanggung seperti wilayah geografis, usia, dll. Semua rencana pemeringkatan klasifikasi menggunakan seperangkat kriteria terbatas untuk mengelompokkan tertanggung ke dalam "kelas" dan akan ada variasi risiko kerugian di antara tertanggung di dalam kelas tersebut.

Rencana pemeringkatan pengalaman mencoba untuk menangkap beberapa variasi dalam risiko kerugian di antara tertanggung dalam kelas pemeringkatan dengan menggunakan pengalaman kerugian tertanggung sendiri untuk melengkapi tingkat dari rencana pemeringkatan klasifikasi. Salah satu cara untuk melakukan hal ini adalah dengan menggunakan <abbr title="Bobot yang diberikan pada pengalaman kerugian historis tertanggung untuk tujuan menentukan premi mereka dalam rencana pemeringkatan pengalaman">**bobot kredibilitas** </abbr> $Z$ dengan $0\leq Z \leq 1$ untuk menghitung 

$$\hat{R}=Z\bar{X}+(1-Z)M,$$
$$\begin{eqnarray*}
\hat{R}&=&\textrm{tingkat bobot kredibilitas untuk risiko,}\\
           \bar{X}&=&\textrm{kerugian rata-rata untuk risiko selama periode waktu tertentu,}\\
                  M&=&\textrm{tingkat untuk kelompok klasifikasi, sering disebut tingkat manual.}\\
\end{eqnarray*}$$

Untuk risiko yang pengalaman kerugiannya stabil dari tahun ke tahun, $Z$ mungkin mendekati $1$. Untuk risiko yang kerugiannya sangat bervariasi dari tahun ke tahun, $Z$ mungkin mendekati $0$.

Teori kredibilitas juga digunakan untuk menghitung tingkat untuk masing-masing kelas dalam rencana peringkat klasifikasi. Ketika tingkat rencana klasifikasi sedang ditentukan, beberapa atau banyak kelompok mungkin tidak memiliki data yang cukup untuk menghasilkan tingkat yang stabil dan dapat diandalkan. Pengalaman kerugian aktual untuk suatu kelompok akan diberi bobot kredibilitas $Z$ dan <abbr title="Sisa bobot yang tidak diberikan pada pengalaman kerugian historis tertanggung dalam rencana pemeringkatan pengalaman">**komplemen kredibilitas** </abbr> $1-Z$ dapat diberikan pada pengalaman rata-rata untuk risiko di seluruh kelas. Atau, jika rencana pemeringkatan kelas sedang diperbarui, komplemen kredibilitas dapat diberikan pada <abbr title="Tingkat rata-rata per eksposur untuk tertanggung dalam kelompok klasifikasi tertentu">**tingkat kelas** </abbr> saat ini. Teori kredibilitas juga dapat diterapkan pada perhitungan frekuensi dan tingkat keparahan yang diharapkan.

Menghitung nilai numerik untuk $Z$ membutuhkan analisis dan pemahaman data. Apa saja varians dalam jumlah kerugian dan ukuran kerugian untuk risiko? Berapa varians antara nilai yang diharapkan di seluruh risiko?

## Limited Fluctuation Credibility

Di bagian ini, kita akan mempelajari cara:

- Hitung standar kredibilitas penuh untuk jumlah klaim, ukuran rata-rata klaim, dan kerugian agregat.
- Pelajari bagaimana hubungan antara sarana dan varians distribusi yang mendasari mempengaruhi standar kredibilitas penuh.
- Menentukan bobot kredibilitas  $Z$ menggunakan rumus kredibilitas parsial akar kuadrat.

<abbr title="Metode kredibilitas yang berupaya membatasi fluktuasi dalam perkiraannya">**Kredibilitas fluktuasi terbatas**</abbr>, juga disebut "kredibilitas klasik" dan "kredibilitas Amerika", diberi nama ini karena metode ini secara eksplisit mencoba untuk membatasi fluktuasi dalam estimasi frekuensi klaim, tingkat keparahan, atau kerugian. Sebagai contoh, anggaplah Anda ingin memperkirakan jumlah klaim yang diharapkan sebanyak $N$ untuk sekelompok risiko dalam suatu kelas peringkat asuransi. Berapa banyak risiko yang diperlukan dalam kelas tersebut untuk memastikan bahwa tingkat akurasi tertentu dapat dicapai dalam estimasi? Pertama, pertanyaan ini akan dipertimbangkan dari perspektif berapa banyak klaim yang dibutuhkan.

### Kredibilitas Penuh untuk Frekuensi Klaim

Misalkan N adalah variabel acak yang mewakili jumlah klaim untuk sekelompok risiko, misalnya, risiko dalam klasifikasi peringkat tertentu. Jumlah klaim yang teramati akan digunakan untuk mengestimasi $\mu_N=\mathrm{E}[N]$, jumlah klaim yang diharapkan. Seberapa besar $μ_N$ yang dibutuhkan untuk mendapatkan estimasi yang baik? Salah satu cara untuk mengukur keakuratan estimasi adalah dengan pernyataan seperti: "Nilai $N$ yang teramati harus berada dalam rentang 5% dari μN setidaknya 90% dari waktu." Menuliskan ini sebagai ekspresi matematis akan menghasilkan $\Pr[0.95 \mu_N \leq N \leq 1.05 \mu_N] \geq 0.90$. Menggeneralisasi pernyataan ini dengan membiarkan parameter rentang k menggantikan 5% dan tingkat probabilitas $p$ menggantikan 0,90 memberikan persamaan

$$\begin{equation}
\Pr[(1-k) \mu_N \leq N \leq (1+k) \mu_N] \geq p .
\tag{9.1}
\end{equation}$$

Jumlah klaim yang diharapkan yang diperlukan agar probabilitas di sisi kiri (9.1) sama dengan $p$ disebut standar kredibilitas penuh.

Jika jumlah klaim yang diharapkan lebih besar atau sama dengan standar kredibilitas penuh maka kredibilitas penuh dapat diberikan pada data sehingga $Z = 1$ . Biasanya nilai yang diharapkan $μ_N$ tidak diketahui sehingga kredibilitas penuh akan diberikan pada data jika jumlah klaim aktual yang diamati $n$ lebih besar atau sama dengan standar kredibilitas penuh. Nilai $k$ dan $p$ harus dipilih dan aktuaris dapat mengandalkan pengalaman, penilaian, dan faktor-faktor lain dalam membuat pilihan.

Mengurangkan $μ_N$ dari setiap suku dalam (9.1) dan membaginya dengan deviasi standar $σ_N$ dari $N$ memberikan

$$\begin{equation}
\Pr\left[\frac{-k\mu_N}{\sigma_N}\leq \frac{N-\mu_N}{\sigma_N} \leq \frac{k\mu_N}{\sigma_N}\right] \geq p.
\tag{9.2}
\end{equation}$$

Dalam kredibilitas fluktuasi terbatas, distribusi normal standar digunakan untuk mendekati distribusi $(N-\mu_N)/\sigma_N$ . Jika $N$ adalah jumlah dari banyak klaim dari sekelompok besar risiko yang sama dan klaim-klaim tersebut independen, maka perkiraannya mungkin masuk akal.

Biarkan $y_p$ adalah nilai yang sedemikian rupa sehingga

$$\Pr[-y_p\leq \frac{N-\mu_N}{\sigma_N} \leq y_p]=\Phi(y_p)-\Phi(-y_p)=p$$

di mana $Φ()$ adalah <abbr title="Fungsi densitas kumulatif untuk distribusi normal dengan mean 0 dan standar deviasi 1">**fungsi distribusi kumulatif  dari normal standar**</abbr>. Karena $\Phi(-y_p)=1-\Phi(y_p)$ persamaan tersebut dapat ditulis ulang sebagai $2\Phi(y_p)-1=p$ . Penyelesaian untuk $y_p$ memberikan $y_p=\Phi^{-1}((p+1)/2)$ dimana $\Phi^{-1}( )$ adalah kebalikan dari $Φ()$ .

Persamaan (9.2) akan terpenuhi jika $k\mu_N/\sigma_N \geq y_p$ dengan mengasumsikan aproksimasi normal. Pertama, kita akan mempertimbangkan ketidaksamaan ini untuk kasus ketika $N$ memiliki distribusi Poisson: $\Pr[N=n] = \lambda^n\textrm{e}^{-\lambda}/n!$ . Karena $\lambda=\mu_N=\sigma_N^2$ untuk Poisson, mengambil akar kuadrat menghasilkan $\mu_N^{1/2}=\sigma_N$ . Jadi, $k\mu_N/\mu_N^{1/2} \geq y_p$ yang setara dengan $\mu_N \geq (y_p/k)^2$ . Mari kita definisikan $\lambda_{kp}$ sebagai nilai dari $μ_N$ yang mana kesetaraan berlaku. Maka standar kredibilitas penuh untuk distribusi Poisson adalah

$$\begin{equation}
\lambda_{kp} = \left(\frac{y_p}{k}\right)^2 \textrm{with } y_p=\Phi^{-1}((p+1)/2).
\tag{9.3}
\end{equation}$$

Jika jumlah klaim yang diharapkan $μ_N$ lebih besar atau sama dengan $\lambda_{kp}$ maka persamaan (9.1) diasumsikan berlaku dan kredibilitas penuh dapat diberikan pada data. Sebagaimana disebutkan sebelumnya, karena $μ_N$ biasanya tidak diketahui, kredibilitas penuh diberikan jika jumlah klaim yang diamati $n$ memenuhi $n≥\lambda_{kp}$.
 
**Contoh 9.2.1**. Standar kredibilitas penuh ditetapkan sehingga jumlah klaim yang teramati berada dalam kisaran 5% dari nilai yang diharapkan dengan probabilitas $p = 0.95$ . Jika jumlah klaim berdistribusi Poisson, tentukan jumlah klaim yang dibutuhkan untuk kredibilitas penuh.

**Solusi**. Mengacu pada tabel distribusi normal standar,
$y_p=\Phi^{-1}((p+1)/2)=\Phi^{-1}((0.95+1)/2)$$\Phi^{-1}(0.975)=1.960$. Dengan menggunakan nilai ini dan $k=.05$ lalu $\lambda_{kp} = (y_p/k)^{2}=(1.960/0.05)^{2}=1,536.64$. Setelah dibulatkan, standar kredibilitas penuhnya adalah 1.537.

### Kredibilitas Penuh untuk Kerugian Agregat dan Premi Murni

Kerugian agregat adalah total dari semua jumlah kerugian untuk risiko atau kelompok risiko. Membiarkan  $S$ mewakili kerugian agregat

$$S=X_1+X_2+\cdots+X_N.$$

Variabel acak $N$ mewakili jumlah kerugian dan variabel acak $X_1, X_2,\ldots,X_N$ adalah jumlah kerugian individu. Pada bagian ini diasumsikan bahwa $N$ tidak bergantung pada jumlah kerugian dan bahwa $X_1, X_2,\ldots,X_N$ adalah Independen dan berdistribusi identik.

Rata-rata dan varians dari $S$ adalah

$$\mu_S=\mathrm{E}(S)=\mathrm{E}(N)\mathrm{E}(X)=\mu_N\mu_X$$

dan

$$\sigma^{2}_S=\mathrm{Var}(S)=\mathrm{E}(N)\mathrm{Var}(X)+[\mathrm{E}(X)]^{2}\mathrm{Var}(N)=\mu_N\sigma^{2}_X+\mu^{2}_X\sigma^{2}_N ,$$

dimana $X$ adalah jumlah kerugian tunggal. Lihat diskusi tentang model risiko kolektif

Kerugian yang teramati $S$ akan digunakan untuk mengestimasi kerugian yang diharapkan $μ_S = E(S)$ . Seperti halnya model frekuensi pada bagian sebelumnya, kerugian yang teramati harus mendekati kerugian yang diharapkan seperti yang dikuantifikasikan dalam persamaan

$$\Pr[(1-k)\mu_S\leq S \leq(1+k)\mu_S] \geq p.$$

Setelah mengurangi rata-rata dan membaginya dengan deviasi standar,

$$\Pr\left[\frac{-k\mu_S}{\sigma_S}\leq (S-\mu_S)/\sigma_S \leq \frac{k\mu_S}{\sigma_S}\right] \geq p .$$

Seperti yang dilakukan pada bagian sebelumnya, diasumsikan bahwa distribusi $(S-\mu_S)/\sigma_S$ adalah standar normal dan $k\mu_S/\sigma_S=y_p=\Phi^{-1}((p+1)/2)$. Persamaan ini dapat ditulis ulang sebagai $\mu_S^2=(y_p/k)^2\sigma_S^2$. Dengan menggunakan rumus sebelumnya untuk $μ_S$ dan $\sigma_{S}^2$, maka didapatkan $(\mu_N\mu_X)^2=(y_p/k)^2(\mu_N\sigma^{2}_X+\mu^{2}_X\sigma^{2}_N)$. Dengan membagi kedua sisi dengan $\mu_N\mu_X^2$ dan mengurutkan sisi kanan, maka didapatkan standar kredibilitas penuh $n_S$ untuk kerugian agregat.

$$\begin{equation}
n_S=\left(\frac{y_p}{k}\right)^2\left[\left(\frac{\sigma_N^2}{\mu_N}\right)+\left(\frac{\sigma_X}{\mu_X}\right)^2\right]=\lambda_{kp}\left[\left(\frac{\sigma_N^2}{\mu_N}\right)+\left(\frac{\sigma_X}{\mu_X}\right)^2\right].
\tag{9.5}
\end{equation}$$

**Contoh 9.2.5**. Jumlah klaim memiliki distribusi Poisson. Jumlah kerugian individu didistribusikan secara independen dan identik dengan distribusi Pareto $F(x)=1-[\theta/(x+\theta)]^{\alpha}$. Jumlah klaim dan jumlah kerugian adalah independen. Jika kerugian agregat yang diamati harus berada dalam 5% dari nilai yang diharapkan dengan probabilitas $p=0.95$, berapa banyak kerugian yang diperlukan untuk kredibilitas penuh?

**Solusi**. Karena jumlah klaim berdistribusi Poisson, maka $(\sigma_N^2/\mu_N)=1$. Rata-rata dari distribusi Pareto adalah $\mu_X=\theta/(\alpha-1)$ dan variansinya adalah $\sigma_X^2=\theta^{2}\alpha/[(\alpha-1)^{2}(\alpha-2)]$, sehingga $(\sigma_X/\mu_X)^2=\alpha/(\alpha-2)$. Menggabungkan istilah frekuensi dan severity memberikan $[(\sigma_N^2/\mu_N)+(\sigma_X/\mu_X)^2]=2(\alpha-1)/(\alpha-2)$. Dari tabel distribusi normal standar, didapatkan $y_p=\Phi^{-1}((0.95+1)/2)=1.960$. Standar kredibilitas penuh adalah $n_S=(1.96/0.05)^{2}[2(\alpha-1)/(\alpha-2)]=3,073.28(\alpha-1)/(\alpha-2)$. Jika $α=3$ maka $n_S=6,146.56$ untuk standar kredibilitas penuh sebesar 6.147. Perlu diperhatikan bahwa jumlah klaim yang jauh lebih banyak diperlukan untuk kredibilitas penuh untuk kerugian agregat dibandingkan dengan frekuensi saja.

### Kredibilitas Penuh untuk Tingkat Keparahan

Misalkan X adalah variabel acak yang merepresentasikan besarnya satu klaim. Severity klaim adalah $\mu_X=\mathrm{E}(X)$. Anggaplah ${X_1,X_2, \ldots, X_n}$ adalah sampel acak dari n klaim yang akan digunakan untuk mengestimasi severity klaim $μ_X$. Klaim-klaim tersebut diasumsikan iid. Nilai rata-rata dari sampel adalah

$$\bar{X}=\frac{1}{n}\left(X_1+X_2+\cdots+X_n\right).$$

Seberapa besar nilai n yang diperlukan untuk mendapatkan estimasi yang baik? Perhatikan bahwa n bukanlah variabel acak sedangkan di model kerugian agregat ia adalah variabel acak.

Pada Bagian 9.2.1, akurasi sebuah estimator untuk frekuensi didefinisikan dengan menentukan agar jumlah klaim berada di dalam interval tertentu sekitar rata-rata jumlah klaim dengan probabilitas tertentu. Untuk severity, persyaratan ini adalah

$$\Pr[(1-k)\mu_X\leq \bar{X} \leq(1+k)\mu_X ]\geq p ,$$

dimana $k$ dan $p$ harus ditentukan. Dengan mengikuti langkah-langkah pada Bagian 9.2.1, rata-rata severity klaim $μ_X$ dikurangi dari setiap termin dan simpangan baku estimator severity klaim $\sigma_{\bar{X}}$ dibagi ke dalam setiap termin sehingga diperoleh

$$\Pr\left[\frac{-k~\mu_X}{\sigma_{\bar{X}}}\leq (\bar{X}-\mu_X)/\sigma_{\bar{X}} \leq \frac{k~\mu_X}{\sigma_{\bar{X}}}\right] \geq p .$$

Seperti pada bagian sebelumnya, diasumsikan bahwa $(\bar{X}-\mu_X)/\sigma_{\bar{X}}$ secara kasar terdistribusi normal dan persamaan sebelumnya terpenuhi jika $k\mu_X/\sigma_{\bar{X}}\geq y_p$ dengan $y_p=\Phi^{-1}((p+1)/2)$. Karena $\bar{X}$ adalah rata-rata klaim individual $X_1, X_2,\dots, X_n$, simpangan baku X¯ sama dengan simpangan baku klaim individual dibagi $\sigma_{\bar{X}}=\sigma_X/\sqrt{n}$. Sehingga, $k\mu_X/(\sigma_X/\sqrt{n})\geq y_p$ dan dengan sedikit aljabar, persamaan ini dapat dituliskan ulang sebagai $n \geq (y_p/k)^2(\sigma_X/\mu_X)^2$. Standar kredibilitas penuh untuk keparahan adalah

$$\begin{equation}
n_X=\left(\frac{y_p}{k}\right)^2\left(\frac{\sigma_X}{\mu_X}\right)^2=\lambda_{kp}\left(\frac{\sigma_X}{\mu_X}\right)^2.
\tag{9.6}
\end{equation}$$

Perhatikan bahwa istilah $\sigma_X/\mu_X$ adalah koefisien variasi untuk klaim individual. Meskipun $\lambda_{kp}$ adalah standar kredibilitas penuh untuk frekuensi dengan diasumsikan distribusi Poisson, tidak ada asumsi tentang distribusi untuk jumlah klaim.

**Contoh 9.2.6**. Besaran klaim individual didistribusikan secara independen dan identik dengan distribusi Pareto Tipe $F(x)=1-[\theta/(x+\theta)]^{\alpha}$. Berapa banyak klaim yang dibutuhkan agar rata-rata keparahan klaim yang diamati berada dalam 5% dari nilai harapan dengan probabilitas $p=0.95$?

**Solusi**. Rata-rata Pareto adalah $\mu_X=\theta/(\alpha-1)$ dan variansnya adalah $\sigma_X^2=\theta^{2}\alpha/[(\alpha-1)^{2}(\alpha-2)]$ sehingga $(\sigma_X/\mu_X)^2=\alpha/(\alpha-2)$. Dari tabel distribusi normal standar, kita dapat menggunakan $y_p=\Phi^{-1}((0.95+1)/2)=1.960$. Standar kredibilitas penuh adalah $n_X=(1.96/0.05)^{2}[\alpha/(\alpha-2)]=1,536.64\alpha/(\alpha-2)$. Misalkan $α=3$ maka $n_X=4,609.92$ untuk standar kredibilitas penuh sebesar 4.610.

### Kredibilitas parsial

Pada bagian sebelumnya, standar kredibilitas penuh dihitung untuk memperkirakan frekuensi ($n_f$), premi murni ($n_{PP}$), dan tingkat keparahan ($n_X$) - pada bagian ini, standar kredibilitas penuh ini akan ditandai dengan $n_0$. Dalam setiap kasus, standar kredibilitas penuh adalah jumlah klaim yang diharapkan untuk mencapai tingkat akurasi tertentu saat menggunakan data empiris untuk memperkirakan nilai yang diharapkan. Jika jumlah klaim yang diamati lebih besar atau sama dengan standar kredibilitas penuh, maka bobot kredibilitas penuh $Z = 1$ diberikan pada data.

Dalam kredibilitas fluktuasi terbatas, bobot kredibilitas $Z$ yang ditugaskan pada data adalah:

$$Z=
\left\{
\begin{array}{ll}
\sqrt{n /n_{0}} &\textrm{if }   n < n_{0} \\ 
1 & \textrm{if }   n \ge n_{0} ,
\end{array}
\right.$$

Di mana $n_0$ merupakan standar kredibilitas penuh. Jumlah klaim $n$ merupakan jumlah klaim untuk data yang digunakan untuk memperkirakan frekuensi yang diharapkan, tingkat keparahan, atau premi murni.

**Contoh 9.2.7**. Jumlah klaim memiliki distribusi Poisson. Jumlah kerugian individu didistribusikan secara independen dan identik dengan distribusi Pareto Tipe II $F(x)=1-[\theta/(x+\theta)]^{\alpha}$. Dalam hal ini, $α=3$. Jumlah klaim dan jumlah kerugian adalah independen. Standar kredibilitas penuh adalah bahwa premi murni yang diamati harus berada dalam 5% dari nilai yang diharapkan dengan probabilitas $p=0.95$. Berapa kredibilitas $Z$ yang diberikan untuk premi murni yang dihitung dari 1.000 klaim?

**Solusi**. Karena jumlah klaim adalah Poisson,
$$\frac{\mathrm{E}(X^2)}{[\mathrm{E}~(X)]^2}
=\frac{\sigma_N^2}{\mu_N}+\left(\frac{\sigma_X}{\mu_X}\right)^2.$$
Rata-rata dari Pareto adalah $μX=θ/(α−1)$ dan momen kedua adalah $\mathrm{E}(X^2)=2\theta^{2}/[(\alpha-1)(\alpha-2)]$ sehingga $\mathrm{E}(X^2)/[\mathrm{E}~(X)]^2=2(\alpha-1)/(\alpha-2)$. Dari tabel distribusi normal standar, $y_p=\Phi^{-1}((0.95+1)/2)=1.960$. Standar kredibilitas penuh adalah
$$n_{PP}=(1.96/0.05)^{2}[2(\alpha-1)/(\alpha-2)]=3,073.28(\alpha-1)/(\alpha-2)$$ dan jika $α=3$, maka $n_0=n_{PP}=6,146.56$ atau 6.147 jika dibulatkan ke atas. Kredibilitas yang diberikan untuk 1.000 klaim adalah $Z=(1,000/6,147)^{1/2}=0.40$.

Kredibilitas fluktuasi terbatas menggunakan rumus $Z=\sqrt{n/n_0}$ untuk membatasi fluktuasi dalam perkiraan yang diboboti kredibilitas untuk sesuai dengan fluktuasi yang diizinkan untuk data dengan jumlah klaim yang diharapkan pada standar kredibilitas penuh. Varians atau simpangan baku digunakan sebagai ukuran fluktuasi. Selanjutnya, kami akan menunjukkan contoh untuk menjelaskan mengapa rumus akar kuadrat digunakan.

Misalkan tingkat keparahan klaim rata-rata sedang diestimasi dari sampel ukuran $n$ yang lebih kecil dari standar kredibilitas penuh $n_0=n_X$. Dengan menerapkan teori kredibilitas, perkiraan $\hat{\mu}_X$ akan menjadi:


$$\hat{\mu}_X=Z\bar{X}+(1-Z)M_X ,$$

dengan $\bar{X}=(X_1+X_2+\cdots+X_n)/n$ dan variabel acak iid $X_i$ yang mewakili ukuran klaim individu. Kredibilitas komplementer diterapkan pada $M_X$ yang bisa menjadi perkiraan tingkat keparahan rata-rata tahun lalu yang disesuaikan dengan inflasi, rata-rata tingkat keparahan untuk kumpulan risiko yang jauh lebih besar, atau kuantitas relevan lainnya yang dipilih oleh aktuaris. Diasumsikan bahwa varians dari $M_X$ adalah nol atau bisa diabaikan. Dengan asumsi ini,

$$\mathrm{Var}(\hat{\mu}_X)=\mathrm{Var}(Z\bar{X})=Z^2\mathrm{Var}(\bar{X})=\frac{n}{n_0}\mathrm{Var}(\bar{X}).$$

Karena $\bar{X}=(X_1+X_2+\cdots+X_n)/n$ maka berlaku bahwa $\mathrm{Var}(\bar{X})=\mathrm{Var}(X_i)/n$ di mana variabel acak $X_i$ adalah satu klaim. Oleh karena itu,

$$\mathrm{Var}(\hat{\mu}_X)=\frac{n}{n_0}\mathrm{Var}(\bar{X})=\frac{n}{n_0}\frac{\mathrm{Var}(X_i)}{n}=\frac{\mathrm{Var}(X_i)}{n_0}.$$

Term terakhir adalah varians tepat dari rata-rata sampel $\bar{X}$ ketika ukuran sampel sama dengan standar kredibilitas penuh $n_0=n_X$.

## Bühlmann Credibility

***

Dalam bagian ini, kita akan mempelajari:

- Menghitung perkiraan yang ditimbang kredibilitas untuk kerugian yang diharapkan untuk suatu risiko atau kelompok risiko.
- Menentukan kredibilitas $Z$ yang diberikan kepada pengamatan.
- Menghitung nilai yang diperlukan dalam kredibilitas Bühlmann, termasuk Nilai Harapan Variansi Proses $( EPV )$, Variansi Rata-rata Hipotetis $( VHM )$ dan rata-rata kolektif $μ$ .
- Mengenali situasi di mana model Bühlmann sesuai.

***

Rencana peringkat klasifikasi mengelompokkan pemegang polis ke dalam kelas berdasarkan karakteristik risiko. Meskipun pemegang polis dalam satu kelas memiliki kesamaan, mereka tidak identik dan kerugian yang diharapkan tidak akan sama persis. Rencana peringkat pengalaman dapat melengkapi rencana peringkat kelas dengan menimbang kredibilitas pengalaman kerugian individu pemegang polis dengan tarif kelas untuk menghasilkan tarif yang lebih akurat bagi pemegang polis.

Dalam penyajian kredibilitas Bühlmann, disarankan untuk menetapkan parameter risiko $θ$ untuk setiap pemegang polis. Kerugian $X$ untuk pemegang polis akan memiliki fungsi distribusi yang umum $Fθ(x)$ dengan rata-rata $μ(θ)=E(X|θ)$ dan varians $σ2(θ)=Var(X|θ)$. Kerugian $X$ dapat mewakili premi murni, kerugian agregat, jumlah klaim, keparahan klaim, atau ukuran kerugian lainnya untuk periode waktu, seringkali selama satu tahun. Parameter risiko $θ$ dapat bersifat kontinu atau diskrit dan dapat multivariat tergantung pada model yang digunakan.

Jika seorang pemegang polis dengan parameter risiko $θ$ mengalami kerugian $X1,...,Xn$ selama $n$ periode waktu, maka tujuannya adalah untuk menemukan $E(μ(θ)|X1,...,Xn)$, yaitu ekspektasi bersyarat dari $μ(θ)$ yang diberikan $X1,...,Xn$. Perkiraan yang ditimbang kredibilitas Bühlmann untuk $E(μ(θ)|X1,...,Xn)$ untuk pemegang polis adalah sebagai berikut:

$$\begin{equation}\hat{\mu}(\theta)=Z\bar{X}+(1-Z)\mu \tag{9.7}\end{equation}$$

Dengan :

$$\begin{eqnarray*} 
\theta&=&\textrm{a risk parameter that identifies a policyholder's risk level}\\
\hat{\mu}(\theta)&=&\textrm{estimated expected loss for a policyholder with parameter }\theta\\
 & & \textrm{and loss experience } \bar{X}\\
\bar{X}&=&(X_1+\cdots+X_n)/n \textrm{ is the average of $n$ observations of the policyholder } \\
 Z&=&\textrm{credibility assigned to $n$ observations } \\
\mu&=&\textrm{the expected loss for a randomly chosen policyholder in the class.}\\
\end{eqnarray*}$$

Untuk pemegang polis yang dipilih, asumsi variabel acak $Xj$ dianggap iid untuk $j=1,...,n$ karena diasumsi8kan bahwa paparan pemegang polis terhadap kerugian tidak berubah dari waktu ke waktu. Kuantitas $\bar{X}$ adalah rata-rata dari $n$ pengamatan dan $E(\bar{X}|θ)=E(Xj|θ)=μ(θ)$.

Jika seorang pemegang polis dipilih secara acak dari kelas dan tidak ada informasi kerugian tentang risiko, maka kerugian yang diharapkan adalah $μ=E(μ(θ))$ di mana harapan diambil dari semua $θ$ dalam kelas. Dalam situasi ini, $Z=0$ dan kerugian yang diharapkan adalah $μ^(θ)=μ$ untuk risiko tersebut. Kuantitas $μ$ juga dapat ditulis sebagai $μ=E(Xj)$ atau $μ=E(\bar{X})$ dan sering disebut sebagai mean keseluruhan atau collective mean. Perhatikan bahwa $E(Xj)$ dievaluasi dengan hukum total ekspektasi: $E(Xj)=E(E[Xj|θ])$.

**Example 9.3.1** Jumlah klaim $X$ untuk seorang tertanggung dalam suatu kelas memiliki distribusi Poisson dengan mean $θ>0$. Parameter risiko $θ$ didistribusikan secara eksponensial di dalam kelas dengan pdf $f(θ)=e−θ$. Berapakah jumlah klaim yang diharapkan untuk seorang tertanggung yang dipilih secara acak dari kelas tersebut?

**Solusi**
Variabel acak $X$ memiliki distribusi Poisson dengan parameter $θ$ dan $E(X|θ)=θ$. Jumlah klaim yang diharapkan untuk seorang tertanggung yang dipilih secara acak adalah $μ=E(μ(θ))=E(E(X|θ))=E(θ)=∫∞0θe−θdθ=1$.

Pada contoh di atas, parameter risiko $θ$ adalah variabel acak dengan distribusi eksponensial. Pada contoh berikutnya, terdapat tiga jenis risiko dan parameter risiko memiliki distribusi diskrit.

**Example 9.3.2** Untuk setiap risiko (pemegang polis) dalam populasi, jumlah kerugian $N$ dalam setahun memiliki distribusi Poisson dengan parameter $λ$. Jumlah kerugian individu $Xi$ untuk sebuah risiko independen dari $N$ dan identik dan memiliki distribusi Pareto Tipe II dengan $F(x) = 1 - [θ / (x + θ)]α$. Ada tiga jenis risiko dalam populasi sebagai berikut:

$$\small{
\begin{array}{|c|c|c|c|}
\hline
\text{Risk } & \text{Percentage} & \text{Poisson} & \text{Pareto} \\
\text{Type} & \text{of Population} & \text{Parameter} & \text{Parameters} \\
\hline
A & 50\% & \lambda=0.5 & \theta=1000, \alpha=2.0 \\
B & 30\% & \lambda=1.0 & \theta=1500, \alpha=2.0 \\  
C & 20\% & \lambda=2.0 & \theta=2000, \alpha=2.0 \\              
\hline
\end{array}
}$$

Jika sebuah risiko dipilih secara acak dari populasi tersebut, berapa kerugian total yang diharapkan dalam setahun?

**Solusi**
Untuk suatu risiko, jumlah klaim yang diharapkan adalah $E(N|λ) = λ$. Nilai harapan dari suatu variabel acak yang didistribusikan Pareto adalah $E(X|θ,α) = θ/(α-1)$. Nilai harapan dari variabel acak kehilangan agregat $S = X1 +⋯+XN$ untuk risiko dengan parameter $λ$, $α$, dan $θ$ adalah $E(S) = E(N)E(X) = λθ/(α-1)$. Kerugian agregat yang diharapkan untuk suatu risiko jenis A adalah $E(SA) = (0,5)(1000)/(2-1) = 500$. Kerugian agregat yang diharapkan untuk suatu risiko yang dipilih secara acak dari populasi adalah $E(S) = 0,5[(0,5)(1000)]+0,3[(1,0)(1500)]+0,2[(2,0)(2000)] = 1500$.

***

Berapa parameter risiko untuk suatu risiko (pemegang polis) pada contoh sebelumnya? Dapat dikatakan bahwa parameter risiko memiliki tiga komponen $(λ, θ, α)$ dengan nilai mungkin (0,5, 1000, 2,0), (1,0, 1500, 2,0), dan (2,0, 2000, 2,0) tergantung pada jenis risiko.

Perlu diperhatikan bahwa pada kedua contoh tersebut, parameter risiko adalah kuantitas acak dengan distribusi probabilitasnya sendiri. Kita tidak tahu nilai parameter risiko untuk risiko yang dipilih secara acak.

Meskipun formula (9.7) diperkenalkan dengan menggunakan rating pengalaman sebagai contoh, model kredibilitas Bühlmann memiliki aplikasi yang lebih luas. Misalkan ada rencana rating dengan beberapa kelas. Formula kredibilitas (9.7) dapat digunakan untuk menentukan tarif kelas individu. Rata-rata keseluruhan $μ$ akan menjadi rata-rata kerugian untuk semua kelas yang digabungkan, $\bar{X}$ akan menjadi pengalaman untuk kelas individu, dan $μ^(θ)$ akan menjadi perkiraan kerugian untuk kelas tersebut.

### Credibility Z, EPV, and VHM

Ketika menghitung estimasi kredibilitas $μ^(θ)=Z\bar{X}+(1−Z)μ$, berapa bobot $Z$ yang harus diberikan pada pengalaman $\bar{X}$ dan berapa bobot $(1−Z)$ pada rata-rata keseluruhan $μ$? Dalam kredibilitas Bühlmann, terdapat tiga faktor yang perlu dipertimbangkan:

1. Berapa variasi dalam satu pengamatan $Xj$ untuk risiko yang dipilih? Dengan $\bar{X} = (X1 + ⋯ + Xn) / n$ dan dengan asumsi bahwa pengamatan adalah iid kondisional pada $θ$, maka mengikuti bahwa $Var(\bar{X}|θ) = Var(Xj|θ) / n$. Untuk $Var(\bar{X}|θ)$ yang lebih besar, bobot kredibilitas $Z$ yang lebih kecil harus diberikan pada pengalaman $\bar{X}$. Nilai Harapan dari Varians Proses, disingkat $EPV$, adalah nilai harapan dari $Var(Xj|θ)$ di seluruh risiko:

$EPV = \mathrm{E}(\mathrm{Var}(X_j|\theta)).$

karena $Var(\bar{X}|θ) = Var(Xj|θ)/n)$ maka berlaku bahwa $E(Var(\bar{X}|θ))=EPV/n$.

2. Seberapa homogen populasi risiko yang pengalaman kerugiannya digabungkan untuk menghitung rata-rata keseluruhan $μ$? Jika semua risiko memiliki potensi kerugian yang serupa, maka bobot yang lebih besar $(1-Z)$ diberikan pada rata-rata keseluruhan $μ$ karena $μ$ adalah rata-rata untuk sekelompok risiko yang serupa dan rata-rata $μ(θ)$ tidak terlalu jauh. Homogenitas atau heterogenitas populasi diukur dengan Variance of the Hypothetical Means dengan singkatan $VHM$:

$$VHM=\mathrm{Var}(\mathrm{E}(X_j|\theta))=\mathrm{Var}(\mathrm{E}(\bar{X}|\theta)).$$

Perhatikan bahwa kita menggunakan $E(\bar{X}|θ)=E(Xj|θ)$ untuk kesamaan kedua.

3. Berapa banyak pengamatan n yang digunakan untuk menghitung $\bar{X}$? Sampel yang lebih besar akan menghasilkan $Z$ yang lebih besar.

**Example 9.3.3** Jumlah klaim $N$ dalam setahun untuk suatu risiko dalam populasi memiliki distribusi Poisson dengan mean $λ>0$. Parameter risiko $λ$ didistribusikan secara seragam di selang (0,2). Hitung $EPV$ dan $VHM$ untuk populasi.

**Solusi**

Variabel acak N berdistribusi Poisson dengan parameter λ sehingga Var(N|λ)=λ . Nilai harapan dari varian proses adalah EPV=E(Var(N|λ)) = E(λ)=∫20λ12dλ=1 . Varians dari rata-rata hipotetis adalah $VHM=Var(E(N|λ)) = Var(λ)=E(λ^2)−(E(λ))^2 = \int_{0}^{2}\lambda^2 \frac{1}{2} d\lambda-(1)^2=\frac{1}{3}$

Formula kepercayaan Bühlmann meliputi nilai untuk $n$, $EPV$, dan $VHM$:

$$\begin{equation}
Z=\frac{n}{n+K} \quad , \quad K =\frac{EPV}{VHM}. 
\tag{9.8} 
\end{equation}$$

Jika $VHM$ meningkat maka $Z$ juga meningkat. Jika $EPV$ meningkat maka $Z$ menjadi lebih kecil. Berbeda dengan kredibilitas fluktuasi terbatas di mana $Z=1$ ketika jumlah klaim yang diharapkan lebih besar dari standar kredibilitas penuh, $Z$ dapat mendekati tetapi tidak sama dengan 1 ketika jumlah pengamatan n mendekati tak hingga.

Jika Anda mengalikan pembilang dan penyebut rumus $Z$ dengan $( VHM/n )$, maka $Z$ dapat ditulis kembali sebagai:

$$Z=\frac{VHM}{VHM+(EPV/n)} .$$

Jumlah pengamatan $n$ tertangkap dalam istilah $(EPV/n)$. Seperti yang ditunjukkan di bullet (1) di awal bagian, $E(Var(\bar{X}|θ)) = EPV/n$. Seiring dengan bertambahnya jumlah pengamatan, varians yang diharapkan dari $\bar{X}$ menjadi lebih kecil dan kredibilitas $Z$ meningkat sehingga lebih banyak bobot diberikan pada $\bar{X}$ dalam perkiraan yang dibobotkan kredibilitas $μ^(θ)$.

## Bühlmann-Straub Credibility

***

Di bagian ini, Anda akan belajar cara:

- Menghitung perkiraan bobot kredibilitas untuk kerugian yang diharapkan untuk risiko atau kelompok risiko menggunakan model Bühlmann-Straub.
- Menentukan kredibilitas $Z$ yang diberikan kepada pengamatan.
- Menghitung nilai yang dibutuhkan termasuk Expected Value of the Process Variance $(EPV)$, Variance of the Hypothetical Means $(VHM)$, dan mean kolektif $μ$.
- Mengenali situasi di mana model Bühlmann-Straub sesuai.

***

Dengan kredibilitas Bühlmann standar atau least-squares seperti yang dijelaskan pada bagian sebelumnya, kerugian $X1,…,Xn$ yang timbul dari pemegang polis yang dipilih diasumsikan sebagai iid. Jika subskrip menunjukkan tahun 1, tahun 2, dan seterusnya hingga tahun $n$, maka asumsi iid berarti bahwa pemegang polis memiliki paparan kerugian yang sama setiap tahun.

Misalkan ada pemegang polis komersial yang menggunakan armada kendaraan dalam bisnisnya. Pada tahun 1, ada $m1$ kendaraan dalam armada, $m2$ kendaraan pada tahun 2, .., dan $mn$ kendaraan pada tahun n. Paparan kerugian dari kepemilikan dan penggunaan armada ini akan tidak konstan dari tahun ke tahun. Kerugian tahunan untuk armada tersebut tidak dapat didefinisikan sebagai iid. Maka untuk permisalan tersebut  $Yjk$ didefinisikan sebagai kerugian untuk kendaraan ke-k dalam armada untuk tahun ke-j. Kemudian, total kerugian untuk armada pada tahun ke-j adalah $Yj1+⋯+Yjmj$, di mana kita menambahkan kerugian untuk masing-masing dari $mj$ kendaraan.

Sedangkan dalam model Bühlmann-Straub, diasumsikan bahwa variabel acak $Yjk$, iid di semua kendaraan dan tahun untuk pemegang polis. Dengan asumsi ini, rata-rata $E(Yjk|θ)=μ(θ)$ dan variansi $Var(Yjk|θ)=σ2(θ)$ sama untuk semua kendaraan dan tahun. Jumlah $μ(θ)$ adalah kerugian yang diharapkan dan $σ2(θ)$ adalah varians pada kerugian untuk satu tahun untuk satu kendaraan untuk pemegang polis dengan parameter risiko $θ$.

Jika $Xj$ adalah kerugian rata-rata per unit paparan pada tahun ke-j, $Xj=(Yj1+⋯+Yjmj)/mj$, maka $E(Xj|θ)=μ(θ)$ dan $Var(Xj|θ)=σ^2(θ)/mj$ untuk pemegang polis dengan parameter risiko $θ$. Kerugian rata-rata per kendaraan untuk seluruh periode $n$ tahun adalah:

$$\begin{equation*}
\bar{X}= \frac{1}{m} \sum_{j=1}^{n} m_j X_{j} \quad , \quad  m=\sum_{j=1}^{n}  m_j. 
\end{equation*}$$

Maka berikutnya $E (\bar{X}|θ)=μ(θ)$ dan $Var(\bar{X}|θ)=σ2(θ)/m$ di mana $μ(θ)$ dan $σ^2(θ)$ adalah rata-rata dan varians untuk satu kendaraan selama satu tahun untuk pemegang polis. 

**Example 9.4.1** Prove that $Var(\bar{X}|θ)=σ^2(θ)/m$ for a risk with risk parameter $θ$.

**Solusi**

$$\begin{eqnarray*}
\mathrm{Var}(\bar{X}|\theta)&=&\mathrm{Var}\left(\frac{1}{m} \sum_{j=1}^{n} m_j X_j|\theta \right)\\
                                  &=&\frac{1}{m^2}\sum_{j=1}^{n} \mathrm{Var}(m_j X_{j}|\theta)=\frac{1}{m^2}\sum_{j=1}^{n} m_j^2 \mathrm{Var}(X_j|\theta)\\
                                  &=&\frac{1}{m^2}\sum_{j=1}^{n} m_j^2 (\sigma^2(\theta)/m_j)=\frac{\sigma^2(\theta)}{m^2}\sum_{j=1}^{n} m_j=\sigma^2(\theta)/m.\\
\end{eqnarray*}$$

***

Dimana Buhlmann-Straub credibility adalah:

$$\begin{equation}\hat{\mu}(\theta)=Z\bar{X}+(1-Z)\mu 
\tag{9.9} 
\end{equation}$$

Dengan :

$$\begin{eqnarray*} 
\theta&=&\textrm{a risk parameter that identifies a policyholder's risk level}\\
\hat{\mu}(\theta)&=&\textrm{estimated expected loss for one exposure for the policyholder}\\
 & & \textrm{with loss experience } \bar{X}\\
\bar{X}&=& \frac{1}{m} \sum_{j=1}^{n} m_j X_j \textrm{ is the average loss per exposure for $m$ exposures.}\\
 & & \textrm{$X_j$ is the average loss per exposure and $m_j$ is the number of exposures in year $j$.} \\
Z&=&\textrm{credibility assigned to $m$ exposures } \\
 \mu&=&\textrm{expected loss for one exposure for randomly chosen}\\
 & & \textrm{ policyholder from population.}\\
\end{eqnarray*}$$

Perlu diperhatikan bahwa $μ^(θ)$ merupakan estimator untuk kerugian yang diharapkan untuk satu paparan. Jika pemegang polis memiliki mj paparan maka kerugian yang diharapkan adalah $mjμ^(θ)$.