<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Bab 6 Simulation and Resampling | Analisis Resiko</title>
  <meta name="description" content="Loss Data Analytics adalah teks yang interaktif, online, tersedia secara bebas. - Versi online akan berisi banyak objek interaktif (kuis, demonstrasi komputer, grafik interaktif, video, dan sejenisnya) untuk mempromosikan pembelajaran yang lebih dalam. - Sebagian dari buku ini akan tersedia dalam format pdf untuk pencetakan dengan biaya rendah. - Teks online akan tersedia dalam berbagai bahasa untuk mempromosikan akses ke audiens di seluruh dunia." />
<<<<<<< HEAD
  <meta name="generator" content="bookdown 0.32 and GitBook 2.6.7" />
=======
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />
>>>>>>> ba9f0d39632695941ca33dd0e276ee6d6606a0e5

  <meta property="og:title" content="Bab 6 Simulation and Resampling | Analisis Resiko" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Loss Data Analytics adalah teks yang interaktif, online, tersedia secara bebas. - Versi online akan berisi banyak objek interaktif (kuis, demonstrasi komputer, grafik interaktif, video, dan sejenisnya) untuk mempromosikan pembelajaran yang lebih dalam. - Sebagian dari buku ini akan tersedia dalam format pdf untuk pencetakan dengan biaya rendah. - Teks online akan tersedia dalam berbagai bahasa untuk mempromosikan akses ke audiens di seluruh dunia." />
  <meta name="github-repo" content="dsciencelabs/Bookdown-Tempalate_R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Bab 6 Simulation and Resampling | Analisis Resiko" />
  
  <meta name="twitter:description" content="Loss Data Analytics adalah teks yang interaktif, online, tersedia secara bebas. - Versi online akan berisi banyak objek interaktif (kuis, demonstrasi komputer, grafik interaktif, video, dan sejenisnya) untuk mempromosikan pembelajaran yang lebih dalam. - Sebagian dari buku ini akan tersedia dalam format pdf untuk pencetakan dengan biaya rendah. - Teks online akan tersedia dalam berbagai bahasa untuk mempromosikan akses ke audiens di seluruh dunia." />
  

<meta name="author" content="Bakti Siregar, M.Sc" />


<meta name="date" content="2023-06-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="aggregate-loss-models.html"/>
<link rel="next" href="premium-foundations.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="images/Logo.png" alt="logo" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html"><i class="fa fa-check"></i>Kata Pengantar</a>
<ul>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#deskripsi-buku"><i class="fa fa-check"></i>Deskripsi Buku</a>
<ul>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#petunjuk-penggunaan"><i class="fa fa-check"></i>Petunjuk Penggunaan</a></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#manfaat"><i class="fa fa-check"></i>Manfaat</a></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#mengapa-analisa-resiko"><i class="fa fa-check"></i>Mengapa Analisa Resiko?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#ucapan-terima-kasih"><i class="fa fa-check"></i>Ucapan Terima Kasih</a></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#kontributor"><i class="fa fa-check"></i>Kontributor</a></li>
<li class="chapter" data-level="" data-path="kata-pengantar.html"><a href="kata-pengantar.html#kritik-saran"><i class="fa fa-check"></i>Kritik &amp; Saran</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html"><i class="fa fa-check"></i><b>1</b> Pengantar Analitika Data Kerugian</a>
<ul>
<li class="chapter" data-level="1.1" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#relevansi-analitika-dalam-aktivitas-asuransi"><i class="fa fa-check"></i><b>1.1</b> Relevansi Analitika dalam Aktivitas Asuransi</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#sifat-dan-relevansi-asuransi"><i class="fa fa-check"></i><b>1.1.1</b> Sifat dan Relevansi Asuransi</a></li>
<li class="chapter" data-level="1.1.2" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#apa-itu-analitika"><i class="fa fa-check"></i><b>1.1.2</b> Apa itu Analitika?</a></li>
<li class="chapter" data-level="1.1.3" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#proses-asuransi"><i class="fa fa-check"></i><b>1.1.3</b> Proses Asuransi</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#operasi-perusahaan-asuransi"><i class="fa fa-check"></i><b>1.2</b> Operasi Perusahaan Asuransi</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#memulai-asuransi"><i class="fa fa-check"></i><b>1.2.1</b> Memulai Asuransi</a></li>
<li class="chapter" data-level="1.2.2" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#memperbarui-asuransi"><i class="fa fa-check"></i><b>1.2.2</b> Memperbarui Asuransi</a></li>
<li class="chapter" data-level="1.2.3" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#pengelolaan-klaim-dan-produk"><i class="fa fa-check"></i><b>1.2.3</b> Pengelolaan Klaim dan Produk</a></li>
<li class="chapter" data-level="1.2.4" data-path="pengantar-analitika-data-kerugian.html"><a href="pengantar-analitika-data-kerugian.html#penyisihan-klaim"><i class="fa fa-check"></i><b>1.2.4</b> Penyisihan Klaim</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="frequency-modeling.html"><a href="frequency-modeling.html"><i class="fa fa-check"></i><b>2</b> Frequency Modeling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="frequency-modeling.html"><a href="frequency-modeling.html#goodness-of-fit"><i class="fa fa-check"></i><b>2.1</b> Goodness of Fit</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html"><i class="fa fa-check"></i><b>3</b> Modeling Loss Severity</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#basic-distributional-quantities"><i class="fa fa-check"></i><b>3.1</b> Basic Distributional Quantities</a></li>
<li class="chapter" data-level="3.2" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#modifikasi-pertanggungan"><i class="fa fa-check"></i><b>3.2</b> modifikasi pertanggungan</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#policy-deductibles"><i class="fa fa-check"></i><b>3.2.1</b> policy deductibles</a></li>
<li class="chapter" data-level="3.2.2" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#policy-limit"><i class="fa fa-check"></i><b>3.2.2</b> 2. Policy Limit</a></li>
<li class="chapter" data-level="3.2.3" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#policy-deductible-and-policy-limit"><i class="fa fa-check"></i><b>3.2.3</b> policy deductible and policy limit</a></li>
<li class="chapter" data-level="3.2.4" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#coinsurance-and-inflation"><i class="fa fa-check"></i><b>3.2.4</b> Coinsurance and inflation</a></li>
<li class="chapter" data-level="3.2.5" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#reinsurance"><i class="fa fa-check"></i><b>3.2.5</b> Reinsurance</a></li>
<li class="chapter" data-level="3.2.6" data-path="modeling-loss-severity.html"><a href="modeling-loss-severity.html#coinsurance-and-reinsurance"><i class="fa fa-check"></i><b>3.2.6</b> Coinsurance and Reinsurance</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="model-selection-and-estimation.html"><a href="model-selection-and-estimation.html"><i class="fa fa-check"></i><b>4</b> Model Selection and Estimation</a></li>
<li class="chapter" data-level="5" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html"><i class="fa fa-check"></i><b>5</b> Aggregate Loss Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#moments-and-distribution"><i class="fa fa-check"></i><b>5.2</b> Moments and Distribution</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#stop-loss-insurance"><i class="fa fa-check"></i><b>5.2.1</b> 5.3.2 Stop-loss Insurance</a></li>
<li class="chapter" data-level="5.2.2" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#actuarial-exam-question---continued"><i class="fa fa-check"></i><b>5.2.2</b> 5.3.7. Actuarial Exam Question - Continued</a></li>
<li class="chapter" data-level="5.2.3" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#analytic-results"><i class="fa fa-check"></i><b>5.2.3</b> 5.3.4 Analytic Results</a></li>
<li class="chapter" data-level="5.2.4" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#tweedie-distribution"><i class="fa fa-check"></i><b>5.2.4</b> 5.3.4 Tweedie Distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#menghitung-distribusi-klaim-agregat"><i class="fa fa-check"></i><b>5.3</b> 5.4 Menghitung Distribusi Klaim Agregat</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#metode-rekursif"><i class="fa fa-check"></i><b>5.3.1</b> metode rekursif</a></li>
<li class="chapter" data-level="5.3.2" data-path="aggregate-loss-models.html"><a href="aggregate-loss-models.html#simulasi"><i class="fa fa-check"></i><b>5.3.2</b> simulasi</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html"><i class="fa fa-check"></i><b>6</b> Simulation and Resampling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#dasar-dasar-simulasi"><i class="fa fa-check"></i><b>6.1</b> Dasar-Dasar Simulasi</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#menghasilkan-pengamatan-seragam-independen"><i class="fa fa-check"></i><b>6.1.1</b> Menghasilkan Pengamatan Seragam Independen</a></li>
<li class="chapter" data-level="6.1.2" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#metode-transformasi-invers"><i class="fa fa-check"></i><b>6.1.2</b> Metode Transformasi Invers</a></li>
<li class="chapter" data-level="6.1.3" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#presisi-simulasi"><i class="fa fa-check"></i><b>6.1.3</b> (6.1.3) Presisi Simulasi</a></li>
<li class="chapter" data-level="6.1.4" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#simulasi-dan-inferensi-statistik"><i class="fa fa-check"></i><b>6.1.4</b> Simulasi dan Inferensi Statistik</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#bootstrap-dan-resampling"><i class="fa fa-check"></i><b>6.2</b> Bootstrap dan Resampling</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#dasar-dasar-bootstrap"><i class="fa fa-check"></i><b>6.2.1</b> Dasar-dasar Bootstrap</a></li>
<li class="chapter" data-level="6.2.2" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#presisi-bootstrap-bias-standar-deviasi-dan-mean-square-error"><i class="fa fa-check"></i><b>6.2.2</b> Presisi Bootstrap: Bias, Standar Deviasi, dan Mean Square Error</a></li>
<li class="chapter" data-level="6.2.3" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#interval-keyakinan"><i class="fa fa-check"></i><b>6.2.3</b> Interval Keyakinan</a></li>
<li class="chapter" data-level="6.2.4" data-path="simulation-and-resampling.html"><a href="simulation-and-resampling.html#bootstrap-parametrik"><i class="fa fa-check"></i><b>6.2.4</b> Bootstrap Parametrik</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="premium-foundations.html"><a href="premium-foundations.html"><i class="fa fa-check"></i><b>7</b> Premium Foundations</a>
<ul>
<li class="chapter" data-level="7.1" data-path="premium-foundations.html"><a href="premium-foundations.html#pengenalan-ratemaking"><i class="fa fa-check"></i><b>7.1</b> Pengenalan Ratemaking</a></li>
<li class="chapter" data-level="7.2" data-path="premium-foundations.html"><a href="premium-foundations.html#metode-penentuan-tarif-gabungan"><i class="fa fa-check"></i><b>7.2</b> Metode Penentuan Tarif Gabungan</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="premium-foundations.html"><a href="premium-foundations.html#metode-penghitungan-premi-murni"><i class="fa fa-check"></i><b>7.2.1</b> Metode Penghitungan Premi Murni</a></li>
<li class="chapter" data-level="7.2.2" data-path="premium-foundations.html"><a href="premium-foundations.html#metode-rasio-kerugian"><i class="fa fa-check"></i><b>7.2.2</b> Metode Rasio Kerugian</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="risk-classification.html"><a href="risk-classification.html"><i class="fa fa-check"></i><b>8</b> Risk Classification</a></li>
<li class="chapter" data-level="9" data-path="experience-rating-using-credibility-theory.html"><a href="experience-rating-using-credibility-theory.html"><i class="fa fa-check"></i><b>9</b> Experience Rating Using Credibility Theory</a></li>
<li class="chapter" data-level="10" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html"><i class="fa fa-check"></i><b>10</b> Insurance Portfolio Management including Reinsurance</a>
<ul>
<li class="chapter" data-level="10.1" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#introduction-to-insurance-portfolios"><i class="fa fa-check"></i><b>10.1</b> Introduction to Insurance Portfolios</a></li>
<li class="chapter" data-level="10.2" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#tails-of-distributions"><i class="fa fa-check"></i><b>10.2</b> Tails of Distributions</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#classification-based-on-moments"><i class="fa fa-check"></i><b>10.2.1</b> Classification Based on Moments</a></li>
<li class="chapter" data-level="10.2.2" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#comparison-based-on-limiting-tail-behavior"><i class="fa fa-check"></i><b>10.2.2</b> Comparison Based on Limiting Tail Behavior</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#risk-measures"><i class="fa fa-check"></i><b>10.3</b> Risk Measures</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#coherent-risk-measures"><i class="fa fa-check"></i><b>10.3.1</b> Coherent Risk Measures</a></li>
<li class="chapter" data-level="10.3.2" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#value-at-risk"><i class="fa fa-check"></i><b>10.3.2</b> Value-at-Risk</a></li>
<li class="chapter" data-level="10.3.3" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#example-10.3.2.-var-for-the-normal-distribution."><i class="fa fa-check"></i><b>10.3.3</b> Example 10.3.2. VaR for the normal distribution.</a></li>
<li class="chapter" data-level="10.3.4" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#tail-value-at-risk"><i class="fa fa-check"></i><b>10.3.4</b> Tail Value-at-Risk</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#reinsurance-1"><i class="fa fa-check"></i><b>10.4</b> Reinsurance</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#proportional-reinsurance"><i class="fa fa-check"></i><b>10.4.1</b> Proportional Reinsurance</a></li>
<li class="chapter" data-level="10.4.2" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#non-proportional-reinsurance"><i class="fa fa-check"></i><b>10.4.2</b> Non-Proportional Reinsurance</a></li>
<li class="chapter" data-level="10.4.3" data-path="insurance-portfolio-management-including-reinsurance.html"><a href="insurance-portfolio-management-including-reinsurance.html#additional-reinsurance-treaties"><i class="fa fa-check"></i><b>10.4.3</b> Additional Reinsurance Treaties</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="loss-reserving.html"><a href="loss-reserving.html"><i class="fa fa-check"></i><b>11</b> Loss Reserving</a></li>
<li class="chapter" data-level="12" data-path="experience-rating-using-bonus-malus.html"><a href="experience-rating-using-bonus-malus.html"><i class="fa fa-check"></i><b>12</b> Experience Rating using Bonus-Malus</a></li>
<li class="chapter" data-level="13" data-path="aggregate-loss-models-1.html"><a href="aggregate-loss-models-1.html"><i class="fa fa-check"></i><b>13</b> Aggregate Loss Models</a></li>
<li class="chapter" data-level="14" data-path="dependence-modeling.html"><a href="dependence-modeling.html"><i class="fa fa-check"></i><b>14</b> Dependence Modeling</a></li>
<li class="chapter" data-level="15" data-path="appendix-a-review-of-statistical-inference.html"><a href="appendix-a-review-of-statistical-inference.html"><i class="fa fa-check"></i><b>15</b> Appendix A: Review of Statistical Inference</a></li>
<li class="chapter" data-level="16" data-path="appendix-b-iterated-expectations.html"><a href="appendix-b-iterated-expectations.html"><i class="fa fa-check"></i><b>16</b> Appendix B: Iterated Expectations</a></li>
<li class="chapter" data-level="17" data-path="appendix-c-maximum-likelihood-theory.html"><a href="appendix-c-maximum-likelihood-theory.html"><i class="fa fa-check"></i><b>17</b> Appendix C: Maximum Likelihood Theory</a></li>
<li class="chapter" data-level="18" data-path="appendix-d-summary-of-distributions.html"><a href="appendix-d-summary-of-distributions.html"><i class="fa fa-check"></i><b>18</b> Appendix D: Summary of Distributions</a></li>
<li class="chapter" data-level="19" data-path="appendix-e-conventions-for-notation.html"><a href="appendix-e-conventions-for-notation.html"><i class="fa fa-check"></i><b>19</b> Appendix E: Conventions for Notation</a></li>
<li><a href="section.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/dsciencelabs/Analisa_Resiko" target="blank">Published with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis Resiko</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simulation-and-resampling" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Bab 6</span> Simulation and Resampling<a href="simulation-and-resampling.html#simulation-and-resampling" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ul>
<li><p>Bagian 6.1 memperkenalkan simulasi, alat komputasi luar biasa yang sangat berguna dalam pengaturan multivariat yang kompleks.</p></li>
<li><p>Bagian 6.2 memperkenalkan resampling dalam konteks bootstrap untuk menentukan ketepatan estimator. Resampling merupakan proses simulasi untuk menggambar dari distribusi empiris.</p></li>
</ul>
<div id="dasar-dasar-simulasi" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Dasar-Dasar Simulasi<a href="simulation-and-resampling.html#dasar-dasar-simulasi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Menghasilkan sekitar realisasi independen yang terdistribusi secara merata</p></li>
<li><p>Ubah realisasi yang terdistribusi secara seragam menjadi pengamatan dari distribusi probabilitas yang menarik</p></li>
<li><p>Hitung jumlah bunga dan tentukan ketepatan jumlah yang dihitung</p></li>
</ol>
<div id="menghasilkan-pengamatan-seragam-independen" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Menghasilkan Pengamatan Seragam Independen<a href="simulation-and-resampling.html#menghasilkan-pengamatan-seragam-independen" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>Generator Kongruensi Linier.</code></p>
<p>Linear Congruential Generators (LCG) adalah sebuah metode yang membangkitkan bilangan acak yang banyak dipergunakan dalam program komputer. Pada metode ini, dilakukan perulangan pada periode waktu tertentu atau setelah sekian kali pembangkitan.Untuk menghasilkan urutan angka acak, mulailah dengan <span class="math inline">\(B_0\)</span> , nilai awal yang dikenal sebagai ‘seed’ . Nilai ini diperbarui menggunakan hubungan rekursif</p>
<p><span class="math display">\[B_{n+1} = (a B_n + c)  \text{ modulo }m, ~~ n=0, 1, 2, \ldots .\]</span></p>
<p>Algoritma ini disebut <span class="math inline">\(a\)</span>. Kasus <span class="math inline">\(c = 0\)</span> disebut generator kongruensial perkalian</p>
<p>Untuk nilai ilustrasi dari <span class="math inline">\(a\)</span> Dan $m4 , menggunakan Microsoft Visual Basic <span class="math inline">\(m=2^{24}\)</span> , <span class="math inline">\(a = 1 , 140 , 671 , 485\)</span> , Dan <span class="math inline">\(c = 12 , 820 , 163\)</span>. Ini adalah mesin yang mendasari pembuatan angka acak dalam program Microsoft Excel.</p>
<p>Urutan yang digunakan oleh analis didefinisikan sebagai <span class="math inline">\(U_n=B_n/m.\)</span>. Analis dapat menginterpretasikan urutan <span class="math inline">\(U_{i}\)</span> menjadi (kira-kira) identik dan independen terdistribusi secara seragam pada interval (0,1). Untuk mengilustrasikan algoritme, maka pertimbangkan hal berikut.</p>
<p><img src="images/enamsatu.png" width="100%" style="display: block; margin: auto;" /></p>
<p><code>Contoh 6.1.2.</code> Menghasilkan Nomor Acak Seragam di <em>R</em>. Kode berikut menunjukkan cara menghasilkan tiga angka seragam (0,1) dalam R menggunakan perintah <em>runif</em>. Fungsi <em>set.seed()</em> di R digunakan untuk membuat hasil yang dapat direproduksi saat menulis kode yang melibatkan pembuatan variabel yang mengambil nilai acak.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="simulation-and-resampling.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb1-2"><a href="simulation-and-resampling.html#cb1-2" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">3</span>)</span>
<span id="cb1-3"><a href="simulation-and-resampling.html#cb1-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(U, <span class="at">digits=</span><span class="dv">5</span>, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>, <span class="at">col.names =</span> <span class="st">&quot;Uniform&quot;</span>)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="center">Uniform</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0.92424</td>
</tr>
<tr class="even">
<td align="center">0.53718</td>
</tr>
<tr class="odd">
<td align="center">0.46920</td>
</tr>
</tbody>
</table>
</div>
<div id="metode-transformasi-invers" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Metode Transformasi Invers<a href="simulation-and-resampling.html#metode-transformasi-invers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Metode transformasi invers digunakan untuk membangkitkan data acak dari distribusi peluang kontinu yang diketahui bentuk fungsinya.</p>
<p>Dengan urutan bilangan acak seragam, kemudian diubah menjadi distribution of interest (<span class="math inline">\(F\)</span>).</p>
<p><span class="math display">\[X_i=F^{-1}\left( U_i \right) .\]</span></p>
<p><span class="math display">\[F^{-1}(y) = \inf_x ~ \{ F(x) \ge y \}\]</span></p>
<p><em>inf</em> singkatan dari *infimum atau batas bawah terbesar. Ini pada dasarnya adalah nilai <span class="math inline">\(x\)</span> terkecil yang memenuhi pertidaksamaan <span class="math inline">\(\{F(x) \ge y\}\)</span>. Hasilnya adalah urutan <span class="math inline">\(X_{i}\)</span> kira-kira iid dengan fungsi distribusi <span class="math inline">\(F\)</span> jika <span class="math inline">\(U_{i}\)</span> adalah iid dengan fungsi distribusi seragam ( 0 , 1 ).</p>
<p><code>Contoh 6.1.3.</code> Menghasilkan Bilangan Acak Eksponensial. Misalkan ingin menghasilkan pengamatan dari distribusi eksponensial dengan parameter skala <span class="math inline">\(θ\)</span> sehingga <span class="math inline">\(F(x) = 1 - e^{-x/\theta}\)</span>. Untuk menghitung transformasi invers, maka dapat menggunakan langkah-langkah berikut:</p>
<p><span class="math display">\[\begin{aligned}
y = F(x) &amp;\Leftrightarrow  y = 1-e^{-x/\theta} \\
  &amp;\Leftrightarrow -\theta \ln(1-y) = x = F^{-1}(y) .
\end{aligned}\]</span></p>
<p>Jadi, jika <span class="math inline">\(U\)</span> memiliki distribusi seragam (0,1), maka <span class="math inline">\(X = -\theta \ln(1-U)\)</span> memiliki distribusi eksponensial dengan parameter <span class="math inline">\(θ\)</span>.</p>
<p>Seperti pada Contoh 6.1.2 kemudian mengubahnya menjadi variabel acak terdistribusi eksponensial independen dengan rata-rata <span class="math inline">\(10\)</span>. Sebagai alternatif, menggunakan fungsi <em>rexp</em> pada R digunakan untuk mensimulasikan sekumpulan bilangan acak yang diambil dari distribusi eksponensial.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="simulation-and-resampling.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb2-2"><a href="simulation-and-resampling.html#cb2-2" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">3</span>)</span>
<span id="cb2-3"><a href="simulation-and-resampling.html#cb2-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">10</span><span class="sc">*</span><span class="fu">log</span>(<span class="dv">1</span><span class="sc">-</span>U)</span>
<span id="cb2-4"><a href="simulation-and-resampling.html#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb2-5"><a href="simulation-and-resampling.html#cb2-5" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">3</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="images/6.1.2-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p><code>Contoh 6.1.4.</code> Menghasilkan Angka Acak Pareto. Misalkan ingin menghasilkan pengamatan dari distribusi Pareto dengan parameter <span class="math inline">\(α\)</span> dan <span class="math inline">\(θ\)</span> sehingga <span class="math inline">\(F(x) = 1 - \left(\frac{\theta}{x+\theta} \right)^{\alpha}\)</span>. Untuk menghitung transformasi invers, maka dapat menggunakan langkah-langkah berikut:</p>
<p><span class="math display">\[\begin{aligned}
y = F(x) &amp;\Leftrightarrow 1-y = \left(\frac{\theta}{x+\theta} \right)^{\alpha} \\
  &amp;\Leftrightarrow \left(1-y\right)^{-1/\alpha} = \frac{x+\theta}{\theta} = \frac{x}{\theta} +1 \\
    &amp;\Leftrightarrow \theta \left((1-y)^{-1/\alpha} - 1\right) = x = F^{-1}(y) .\end{aligned}\]</span></p>
<p>Dengan demikian, <span class="math inline">\(X = \theta \left((1-U)^{-1/\alpha} - 1\right)\)</span> memiliki distribusi Pareto dengan parameter <span class="math inline">\(α\)</span> dan <span class="math inline">\(θ\)</span> .</p>
<p><code>Contoh 6.1.5.</code> Menghasilkan Bilangan Acak Bernoulli. Misalkan ingin mensimulasikan variabel acak dari distribusi Bernoulli dengan parameter <span class="math inline">\(Q= 0,85\)</span>.</p>
<p><img src="images/6.1.2-2.png" width="100%" style="display: block; margin: auto;" />
Grafik fungsi distribusi kumulatif pada Gambar diatas menunjukkan bahwa fungsi kuantil dapat ditulis sebagai berikut.</p>
<p><span class="math display">\[\begin{aligned}
F^{-1}(y) = \left\{ \begin{array}{cc}
              0 &amp; 0&lt;y \leq 0.85 \\
              1 &amp; 0.85 &lt; y  \leq  1.0 .
            \end{array} \right.
\end{aligned}\]</span></p>
<p>Jadi, dengan transformasi invers kita dapat mendefinisikan</p>
<p><span class="math display">\[\begin{aligned}
X = \left\{ \begin{array}{cc}
              0 &amp; 0&lt;U \leq 0.85  \\
              1 &amp;  0.85 &lt; U  \leq  1.0
            \end{array} \right.
\end{aligned}\]</span></p>
<p>Misalnya, ingin menghasilkan tiga angka acak untuk diperoleh</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="simulation-and-resampling.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb3-2"><a href="simulation-and-resampling.html#cb3-2" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">3</span>)</span>
<span id="cb3-3"><a href="simulation-and-resampling.html#cb3-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(U <span class="sc">&gt;</span> <span class="fl">0.85</span>)</span></code></pre></div>
<p><img src="images/6.1.2-3.png" width="100%" style="display: block; margin: auto;" />
<code>Contoh 6.1.6.</code> Menghasilkan Angka Acak dari Distribusi Diskrit. Pertimbangkan waktu kegagalan mesin dalam lima tahun pertama. Distribusi waktu kegagalan diberikan sebagai:</p>
<p><img src="images/6.1.2-4.png" width="100%" style="display: block; margin: auto;" /></p>
<p><img src="images/6.1.2-5.png" width="100%" style="display: block; margin: auto;" />
Dengan menggunakan grafik fungsi distribusi pada gambar diatas , dengan transformasi invers dapat definisikan</p>
<p><span class="math display">\[\small{
\begin{aligned}
X = \left\{ \begin{array}{cc}
              1 &amp;   0&lt;U  \leq 0.1  \\
              2 &amp;  0.1 &lt; U  \leq  0.3\\
              3 &amp;  0.3 &lt; U  \leq  0.4\\
              4 &amp;  0.4 &lt; U  \leq  0.8  \\
              5 &amp;  0.8 &lt; U  \leq  1.0     .
            \end{array} \right.
\end{aligned}
}\]</span></p>
<p>Untuk variabel acak diskrit umum mungkin tidak ada urutan hasil. Misalnya, seseorang dapat memiliki salah satu dari lima jenis produk asuransi jiwa dan dapat menggunakan algoritme berikut untuk menghasilkan hasil acak:</p>
<p><span class="math display">\[{\small
\begin{aligned}
X = \left\{ \begin{array}{cc}
  \textrm{whole life} &amp;   0&lt;U  \leq 0.1  \\
\textrm{endowment} &amp;  0.1 &lt; U  \leq  0.3\\
\textrm{term life} &amp;  0.3 &lt; U  \leq  0.4\\
  \textrm{universal life} &amp;  0.4 &lt; U  \leq  0.8  \\
  \textrm{variable life} &amp;  0.8 &lt; U  \leq  1.0 .
            \end{array} \right.
\end{aligned}
}\]</span></p>
<p>Analis lain dapat menggunakan prosedur alternatif seperti:</p>
<p><span class="math display">\[{\small
\begin{aligned}
X = \left\{ \begin{array}{cc}
  \textrm{whole life} &amp;   0.9&lt;U&lt;1.0  \\
\textrm{endowment} &amp;  0.7 \leq U &lt; 0.9\\
\textrm{term life} &amp;  0.6 \leq U &lt; 0.7\\
  \textrm{universal life} &amp;  0.2 \leq U &lt; 0.6  \\
  \textrm{variable life} &amp;  0 \leq U &lt; 0.2 .
            \end{array} \right.
\end{aligned}
}\]</span></p>
<p>Kedua algoritma menghasilkan (dalam jangka panjang) probabilitas yang sama, misalnya, <span class="math inline">\(\Pr(\textrm{whole life})=0.1\)</span> , Dan seterusnya. Jadi, tidak ada yang salah ini menunjukkan bahwa ada lebih dari satu cara untuk mencapai suatu tujuan. Demikian pula, dapat menggunakan algoritme alternatif untuk hasil yang diurutkan (seperti waktu kegagalan 1, 2, 3, 4, atau 5, di atas).</p>
<p><code>Contoh 6.1.7.</code> Menghasilkan Angka Acak dari Distribusi Hybrid. Pertimbangkan variabel acak yaitu 0 dengan probabilitas 70% dan terdistribusi secara eksponensial dengan parameter <span class="math inline">\(\theta= 10,000\)</span> dengan probabilitas 30%. Dalam aplikasi asuransi, ini mungkin sesuai dengan peluang 70% tidak memiliki klaim asuransi dan peluang klaim 30% - jika klaim terjadi, maka itu didistribusikan secara eksponensial. Fungsi distribusi, digambarkan pada gambar dibawah ini , diberikan sebagai</p>
<p><span class="math display">\[\begin{aligned}
F(y) = \left\{ \begin{array}{cc}
              0 &amp;  x&lt;0  \\
              1 - 0.3 \exp(-x/10000) &amp; x \ge 0 .
            \end{array} \right.
\end{aligned}\]</span></p>
<p><img src="images/6.1.2-6.png" width="100%" style="display: block; margin: auto;" />
Dari Gambar diatas dapat dilihat bahwa transformasi invers untuk membangkitkan variabel acak dengan fungsi distribusi ini adalah</p>
<p><span class="math display">\[\begin{aligned}
X = F^{-1}(U) = \left\{ \begin{array}{cc}
              0 &amp;  0&lt; U  \leq  0.7  \\
              -1000 \ln (\frac{1-U}{0.3}) &amp; 0.7 &lt; U &lt; 1 .
            \end{array} \right.
\end{aligned}\]</span></p>
</div>
<div id="presisi-simulasi" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> (6.1.3) Presisi Simulasi<a href="simulation-and-resampling.html#presisi-simulasi" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Setelah mengetahui cara menghasilkan realisasi simulasi independen dari distribusi bunga, maka dapat menyusun distribusi empiris (distribusi empiris mengelompokkan data ke dalam suatu interval, di mana frekuensi data dalam setiap interval dapat digunakan untuk menentukan frekuensi relatifnya) dan memperkirakan distribusi yang diperlukan.</p>
<p>Banyak dari aplikasi ini dapat direduksi menjadi masalah perkiraan <span class="math inline">\(\mathrm{E~}[h(X)]\)</span> , Di mana <span class="math inline">\(h(\cdot)\)</span> adalah beberapa fungsi yang diketahui. Berdasarkan simulasi R (replikasi), sehingga didapatkan <span class="math inline">\(X_1,\ldots,X_R\)</span>. Dari sampel yang disimulasikan ini, dapat menghitung rata-rata sebagai berikut.</p>
<p><span class="math display">\[\overline{h}_R=\frac{1}{R}\sum_{i=1}^{R} h(X_i)\]</span></p>
<p>sebagai perkiraan simulasi dari <span class="math inline">\(\mathrm{E~}[h(X)]\)</span>. Untuk memperkirakan ketepatan perkiraan tersebut, maka menggunakan varians simulasi</p>
<p><span class="math display">\[s_{h,R}^2 = \frac{1}{R-1} \sum_{i=1}^{R}\left( h(X_i) -\overline{h}_R
\right) ^2.\]</span></p>
<p>Dari independensi, kesalahan standar estimasi adalah <span class="math inline">\(s_{h,R}/\sqrt{R}\)</span>. Kesalahan standar estimasi dapat dibuat sekecil dengan meningkatkan jumlah replikasi <span class="math inline">\(R\)</span>.</p>
<p><code>Contoh 6.1.8.</code> Manajemen portofolio. Pada Bagian 3.4 telah mempelajari cara menghitung nilai ekspektasi polis dengan deductible. Sebagai contoh dari sesuatu yang tidak dapat dilakukan dengan ekspresi bentuk tertutup, kemudian akan mempertimbangkan dua risiko. (Ini adalah variasi dari contoh yang lebih kompleks yang akan dibahas sebagai Contoh 10.3.6).</p>
<p>Dengan mempertimbangkan dua risiko properti dari perusahaan telekomunikasi:</p>
<ul>
<li><p><span class="math inline">\(X_1\)</span> - bangunan, dimodelkan menggunakan distribusi gamma dengan rata-rata 200 dan parameter skala 100.</p></li>
<li><p><span class="math inline">\(X_2\)</span> - kendaraan bermotor, dimodelkan menggunakan distribusi gamma dengan mean 400 dan parameter skala 200.</p></li>
</ul>
<p>Nyatakan risiko total sebagai <span class="math inline">\(X = X_1 + X_2\)</span>. Untuk penyederhanaan, dapat diasumsikan bahwa risiko ini tidak bergantung.</p>
<p>Untuk mengelola risiko maka diperlukan perlindungan atau penjamin asuransi dan bersedia mempertahankan jumlah bangunan dan kendaraan bermotor kecil secara internal, hingga <span class="math inline">\(M\)</span>. Jumlah acak lebih dari <span class="math inline">\(M\)</span> akan memiliki pengaruh yang tidak terduga pada anggaran dan karenanya untuk jumlah ini dapat mencari perlindungan asuransi. Dinyatakan secara matematis, risiko yang dipertahankan adalah <span class="math inline">\(Y_{retained}=\min(X_1 + X_2,M)\)</span> dan bagian penanggung adalah <span class="math inline">\(Y_{insurer} = X- Y_{retained}\)</span>.</p>
<p>Misalnya <span class="math inline">\(M= 400\)</span> serta <span class="math inline">\(R = 1000000\)</span>.</p>
<p><code>A.</code> Dengan pengaturan tersebut, ingin menentukan perkiraan jumlah klaim dan standar deviasi terkait dari (i) yang ditahan, (ii) yang diterima oleh perusahaan asuransi, dan (iii) total jumlah keseluruhan.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="simulation-and-resampling.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate the risks</span></span>
<span id="cb4-2"><a href="simulation-and-resampling.html#cb4-2" aria-hidden="true" tabindex="-1"></a>nSim <span class="ot">&lt;-</span> <span class="fl">1e6</span>  <span class="co">#number of simulations</span></span>
<span id="cb4-3"><a href="simulation-and-resampling.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>) <span class="co">#set seed to reproduce work </span></span>
<span id="cb4-4"><a href="simulation-and-resampling.html#cb4-4" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(nSim ,alpha1,<span class="at">scale =</span> theta1)  </span>
<span id="cb4-5"><a href="simulation-and-resampling.html#cb4-5" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(nSim ,alpha2,<span class="at">scale =</span> theta2) </span>
<span id="cb4-6"><a href="simulation-and-resampling.html#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="simulation-and-resampling.html#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Portfolio Risks</span></span>
<span id="cb4-8"><a href="simulation-and-resampling.html#cb4-8" aria-hidden="true" tabindex="-1"></a>X         <span class="ot">&lt;-</span> X1 <span class="sc">+</span> X2 </span>
<span id="cb4-9"><a href="simulation-and-resampling.html#cb4-9" aria-hidden="true" tabindex="-1"></a>Yretained <span class="ot">&lt;-</span> <span class="fu">pmin</span>(X, M)</span>
<span id="cb4-10"><a href="simulation-and-resampling.html#cb4-10" aria-hidden="true" tabindex="-1"></a>Yinsurer  <span class="ot">&lt;-</span> X <span class="sc">-</span> Yretained</span></code></pre></div>
<p>Kemudian jumlah klaim yang diharapkan adalah</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="simulation-and-resampling.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected Claim Amounts</span></span>
<span id="cb5-2"><a href="simulation-and-resampling.html#cb5-2" aria-hidden="true" tabindex="-1"></a>ExpVec <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">as.matrix</span>(<span class="fu">c</span>(<span class="fu">mean</span>(Yretained),<span class="fu">mean</span>(Yinsurer),<span class="fu">mean</span>(X))))</span>
<span id="cb5-3"><a href="simulation-and-resampling.html#cb5-3" aria-hidden="true" tabindex="-1"></a>sdVec <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">as.matrix</span>(<span class="fu">c</span>(<span class="fu">sd</span>(Yretained),<span class="fu">sd</span>(Yinsurer),<span class="fu">sd</span>(X))))</span>
<span id="cb5-4"><a href="simulation-and-resampling.html#cb5-4" aria-hidden="true" tabindex="-1"></a>outMat <span class="ot">&lt;-</span> <span class="fu">rbind</span>(ExpVec, sdVec)</span>
<span id="cb5-5"><a href="simulation-and-resampling.html#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(outMat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Retained&quot;</span>, <span class="st">&quot;Insurer&quot;</span>,<span class="st">&quot;Total&quot;</span>)</span>
<span id="cb5-6"><a href="simulation-and-resampling.html#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(outMat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Mean&quot;</span>,<span class="st">&quot;Standard Deviation&quot;</span>)</span>
<span id="cb5-7"><a href="simulation-and-resampling.html#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(outMat,<span class="at">digits=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="images/6.1.3-1.png" width="100%" style="display: block; margin: auto;" />
<code>B.</code> Untuk klaim yang diasuransikan, kesalahan standar perkiraan simulasi adalah <span class="math inline">\(s_{h,R}/\sqrt{1000000} =/\sqrt{1000000} =0.281\)</span>. Untuk contoh ini, simulasi cepat dan nilai yang besar seperti 1000000 adalah pilihan yang mudah. Namun, untuk masalah yang lebih kompleks, ukuran simulasi mungkin menjadi masalah.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="simulation-and-resampling.html#cb6-1" aria-hidden="true" tabindex="-1"></a>Yinsurefct <span class="ot">&lt;-</span> <span class="cf">function</span>(numSim){</span>
<span id="cb6-2"><a href="simulation-and-resampling.html#cb6-2" aria-hidden="true" tabindex="-1"></a>X1 <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(numSim,alpha1,<span class="at">scale =</span> theta1)  </span>
<span id="cb6-3"><a href="simulation-and-resampling.html#cb6-3" aria-hidden="true" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(numSim,alpha2,<span class="at">scale =</span> theta2)  </span>
<span id="cb6-4"><a href="simulation-and-resampling.html#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Portfolio Risks</span></span>
<span id="cb6-5"><a href="simulation-and-resampling.html#cb6-5" aria-hidden="true" tabindex="-1"></a>X         <span class="ot">&lt;-</span> X1 <span class="sc">+</span> X2 </span>
<span id="cb6-6"><a href="simulation-and-resampling.html#cb6-6" aria-hidden="true" tabindex="-1"></a>Yinsurer <span class="ot">&lt;-</span> X <span class="sc">-</span> <span class="fu">pmin</span>(X, M)</span>
<span id="cb6-7"><a href="simulation-and-resampling.html#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">return</span>(Yinsurer)</span>
<span id="cb6-8"><a href="simulation-and-resampling.html#cb6-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-9"><a href="simulation-and-resampling.html#cb6-9" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fl">1e3</span></span>
<span id="cb6-10"><a href="simulation-and-resampling.html#cb6-10" aria-hidden="true" tabindex="-1"></a>nPath <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb6-11"><a href="simulation-and-resampling.html#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb6-12"><a href="simulation-and-resampling.html#cb6-12" aria-hidden="true" tabindex="-1"></a>simU <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">Yinsurefct</span>(R<span class="sc">*</span>nPath),R,nPath)</span>
<span id="cb6-13"><a href="simulation-and-resampling.html#cb6-13" aria-hidden="true" tabindex="-1"></a>sumP2 <span class="ot">&lt;-</span> <span class="fu">apply</span>(simU, <span class="dv">2</span>, cumsum)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>R)</span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="simulation-and-resampling.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(<span class="dv">1</span><span class="sc">:</span>R,sumP2[,<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>],<span class="at">type=</span><span class="st">&quot;l&quot;</span>,<span class="at">col=</span><span class="fu">rgb</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">2</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">400</span>),</span>
<span id="cb7-2"><a href="simulation-and-resampling.html#cb7-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Number of Simulations (&quot;</span>, <span class="fu">italic</span>(<span class="st">&#39;R&#39;</span>), <span class="st">&quot;)&quot;</span>)), </span>
<span id="cb7-3"><a href="simulation-and-resampling.html#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">&quot;Expected Insurer Claims&quot;</span>)</span>
<span id="cb7-4"><a href="simulation-and-resampling.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(Yinsurer),<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb7-5"><a href="simulation-and-resampling.html#cb7-5" aria-hidden="true" tabindex="-1"></a>bonds <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(Yinsurer)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>R)),<span class="sc">-</span><span class="fl">1.96</span><span class="sc">*</span><span class="fu">sd</span>(Yinsurer)<span class="sc">*</span><span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">:</span>R)))</span>
<span id="cb7-6"><a href="simulation-and-resampling.html#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">matlines</span>(<span class="dv">1</span><span class="sc">:</span>R,bonds<span class="sc">+</span><span class="fu">mean</span>(Yinsurer),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="images/6.1.3-2.png" width="100%" style="display: block; margin: auto;" />
Dari grafik diatas dapat dilihat, semakin banyak jumlah simulasi R maka semakin sedikit jumlah klaim yang diharapkan.</p>
<p><code>Penentuan Jumlah Simulasi</code></p>
<p>Misalkan ingin berada dalam 1% dari rata-rata dengan kepastian 95%. Artinya, <span class="math inline">\(\Pr \left( |\overline{h}_R - \mathrm{E~}[h(X)]| \le 0.01 \mathrm{E~}[h(X)] \right) \ge 0.95\)</span>. Menurut teorema limit pusat, perkiraan harus terdistribusi secara normal dan mengharapkan R cukup besar untuk <span class="math inline">\(0.01 \mathrm{E~}[h(X)]/\sqrt{\mathrm{Var~}[h(X)]/R}) \ge 1.96\)</span> . (Ingat bahwa 1,96 adalah persentil ke-97,5 dari distribusi normal standar.) Mengganti <span class="math inline">\(\mathrm{E~}[h(X)]\)</span> Dan <span class="math inline">\(\mathrm{Var~}[h(X)]\)</span> dengan estimasi,sehingga</p>
<p><span class="math display">\[\frac{.01\overline{h}_R}{s_{h,R}/\sqrt{R}}\geq 1.96\]</span></p>
<p><span class="math display">\[\begin{equation}
R \geq 38,416\frac{s_{h,R}^2}{\overline{h}_R^2}.
\tag{6.1}
\end{equation}\]</span></p>
<p><code>Contoh 6.1.9.</code> Pilihan Perkiraan.</p>
<p>Sebuah aplikasi penting dari simulasi adalah pendekatan dari <span class="math inline">\(\mathrm{E~}[h(X)]\)</span>. Dalam contoh ini, kami menunjukkan bahwa pilihan dari <span class="math inline">\(h(\cdot)\)</span> fungsi dan distribusi <span class="math inline">\(X\)</span> dapat berperan.</p>
<p>Pertimbangkan pertanyaan berikut: apa itu <span class="math inline">\(\Pr[X&gt;2]\)</span>. Kapan <span class="math inline">\(X\)</span> mempunyai sebuah distribusi Cauchy (distribusi probabilitas kontinu), dengan fungsi kepadatan <span class="math inline">\(f(x) =\left(\pi(1+x^2)\right)^{-1}\)</span>, pada garis sebenarnya? Nilai sebenarnya adalah</p>
<p><span class="math display">\[\Pr\left[X&gt;2\right] = \int_2^\infty \frac{dx}{\pi(1+x^2)} .\]</span></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="simulation-and-resampling.html#cb8-1" aria-hidden="true" tabindex="-1"></a>true_value <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(x) <span class="dv">1</span><span class="sc">/</span>(pi<span class="sc">*</span>(<span class="dv">1</span><span class="sc">+</span>x<span class="sc">^</span><span class="dv">2</span>)),<span class="at">lower=</span><span class="dv">2</span>,<span class="at">upper=</span><span class="cn">Inf</span>)<span class="sc">$</span>value</span>
<span id="cb8-2"><a href="simulation-and-resampling.html#cb8-2" aria-hidden="true" tabindex="-1"></a>true_value </span></code></pre></div>
<pre><code>## [1] 0.1475836</code></pre>
<p><code>Perkiraan 1.</code> Sebagai alternatif, seseorang dapat menggunakan teknik simulasi untuk memperkirakan besaran tersebut. Dari kalkulus, dapat memeriksa bahwa fungsi kuantil dari distribusi Cauchy adalah <span class="math inline">\(F^{-1}(y) = \tan \left( \pi(y-0.5) \right)\)</span> . Kemudian, dengan variasi seragam (0,1) yang disimulasikan, <span class="math inline">\(U_1, \ldots, U_R\)</span>, sehingga dapat membangun estimator</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="simulation-and-resampling.html#cb10-1" aria-hidden="true" tabindex="-1"></a>Q <span class="ot">&lt;-</span> <span class="cf">function</span>(u) <span class="fu">tan</span>(pi<span class="sc">*</span>(u<span class="fl">-.5</span>))</span>
<span id="cb10-2"><a href="simulation-and-resampling.html#cb10-2" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fl">1e6</span></span>
<span id="cb10-3"><a href="simulation-and-resampling.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb10-4"><a href="simulation-and-resampling.html#cb10-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">Q</span>(<span class="fu">runif</span>(R))</span>
<span id="cb10-5"><a href="simulation-and-resampling.html#cb10-5" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(X<span class="sc">&gt;</span><span class="dv">2</span>)</span>
<span id="cb10-6"><a href="simulation-and-resampling.html#cb10-6" aria-hidden="true" tabindex="-1"></a>se.p1 <span class="ot">&lt;-</span> <span class="fu">sd</span>(X<span class="sc">&gt;</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">sqrt</span>(R)</span>
<span id="cb10-7"><a href="simulation-and-resampling.html#cb10-7" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div>
<pre><code>## [1] 0.147439</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="simulation-and-resampling.html#cb12-1" aria-hidden="true" tabindex="-1"></a>se.p1</span></code></pre></div>
<pre><code>## [1] 0.0003545432</code></pre>
<p>Dengan satu juta simulasi, diperoleh estimasi sebesar 0,14744 dengan standard error 0,355 (dibagi 1000). Dapat dibuktikan bahwa varian dari <span class="math inline">\(P_1\)</span> teratur <span class="math inline">\(0.127/R\)</span>.</p>
<p><code>Perkiraan 2.</code> Dengan pilihan lain dari <span class="math inline">\(h(\cdot)\)</span> Dan <span class="math inline">\(f(\cdot)\)</span> adalah mungkin untuk mengurangi ketidakpastian bahkan dengan menggunakan jumlah simulasi yang sama <span class="math inline">\(R\)</span> . Untuk memulai, seseorang dapat menggunakan simetri distribusi Cauchy untuk menulis <span class="math inline">\(\Pr[X&gt;2]=0.5\cdot\Pr[|X|&gt;2]\)</span> . Dengan ini, dapat membuat estimator baru</p>
<p><span class="math display">\[p_2 = \frac{1}{2R}\sum_{i=1}^R \mathrm{I}(|F^{-1}(U_i)|&gt;2) .\]</span></p>
<p>Dengan satu juta simulasi, diperoleh estimasi sebesar 0,14748 dengan standard error 0,228 (dibagi 1000). Dapat dibuktikan bahwa varian dari <span class="math inline">\(P_2\)</span> teratur <span class="math inline">\(0.052/R\)</span>.</p>
<p><code>Perkiraan 3.</code> Integral tak wajar dapat ditulis dengan sifat simetri sederhana (karena fungsinya simetris dan integral pada garis real sama dengan 1 ).</p>
<p><span class="math display">\[\int_2^\infty \frac{dx}{\pi(1+x^2)}=\frac{1}{2}-\int_0^2\frac{dx}{\pi(1+x^2)} .\]</span></p>
<p><span class="math display">\[p_3 = \frac{1}{2}-\frac{1}{R}\sum_{i=1}^R h_3(2U_i), ~~~~~~\text{where}~h_3(x)=\frac{2}{\pi(1+x^2)} .\]</span></p>
<p>Dengan satu juta simulasi, diperoleh estimasi sebesar 0,14756 dengan standard error 0,169 (dibagi 1000). Dapat dibuktikan bahwa varian dari <span class="math inline">\(P_3\)</span> teratur <span class="math inline">\(0,0285 / R\)</span>.</p>
<p><code>Perkiraan 4.</code> Akhirnya, seseorang juga dapat mempertimbangkan beberapa perubahan variabel dalam integral.</p>
<p><span class="math display">\[\int_2^\infty \frac{dx}{\pi(1+x^2)}=\int_0^{1/2}\frac{y^{-2}dy}{\pi(1-y^{-2})} .\]</span></p>
<p><span class="math display">\[p_4 = \frac{1}{R}\sum_{i=1}^R h_4(U_i/2),~~~~~\text{where}~h_4(x)=\frac{1}{2\pi(1+x^2)} .\]</span></p>
<p>Dengan satu juta simulasi, diperoleh estimasi sebesar 0,14759 dengan standard error 0,01 (dibagi 1000). Dapat dibuktikan bahwa varian dari <span class="math inline">\(P_4\)</span> teratur <span class="math inline">\(0,00009 / R\)</span> , yang jauh lebih kecil dari yang lainnya.</p>
<p>Tabel berikut merupakan rangkuman dari empat pilihan <span class="math inline">\(h(\cdot)\)</span> Dan <span class="math inline">\(f(\cdot)\)</span>) untuk memperkirakan <span class="math inline">\(\Pr[X&gt;2] = 0,14758\)</span>. Kesalahan standar bervariasi. Jadi, jika memiliki tingkat akurasi yang diinginkan, maka jumlah simulasi sangat bergantung pada bagaimana menulis integral yang akan diaproksimasi.</p>
<p><img src="images/6.1.3-3.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="simulasi-dan-inferensi-statistik" class="section level3 hasAnchor" number="6.1.4">
<h3><span class="header-section-number">6.1.4</span> Simulasi dan Inferensi Statistik<a href="simulation-and-resampling.html#simulasi-dan-inferensi-statistik" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Simulasi tidak hanya membantu dalam memperkirakan nilai yang diharapkan tetapi juga berguna dalam menghitung aspek lain dari fungsi distribusi. Secara khusus, ini sangat berguna ketika distribusi statistik uji terlalu rumit untuk diturunkan. Dalam hal ini, seseorang dapat menggunakan simulasi untuk memperkirakan distribusi referensi.</p>
<p><code>Contoh 6.1.10.</code> Uji Distribusi Kolmogorov-Smirnov.</p>
<p>Misalkan terdapata <span class="math inline">\(n = 100\)</span> observasi <span class="math inline">\(\{x_1,\cdots,x_n\}\)</span> yang, tidak diketahui oleh analis, dihasilkan dari distribusi gamma dengan parameter <span class="math inline">\(\alpha = 6\)</span> Dan <span class="math inline">\(\theta=2\)</span> . Analis percaya bahwa data berasal dari distribusi lognormal dengan parameter 1 dan 0,4 dan ingin menguji asumsi ini.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="simulation-and-resampling.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb14-2"><a href="simulation-and-resampling.html#cb14-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb14-3"><a href="simulation-and-resampling.html#cb14-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(n, <span class="dv">6</span>, <span class="dv">2</span>)</span>
<span id="cb14-4"><a href="simulation-and-resampling.html#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="simulation-and-resampling.html#cb14-5" aria-hidden="true" tabindex="-1"></a>u<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">7</span>,<span class="at">by=</span>.<span class="dv">01</span>)</span>
<span id="cb14-6"><a href="simulation-and-resampling.html#cb14-6" aria-hidden="true" tabindex="-1"></a>vx <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fu">sort</span>(x))</span>
<span id="cb14-7"><a href="simulation-and-resampling.html#cb14-7" aria-hidden="true" tabindex="-1"></a>vy <span class="ot">=</span> (<span class="dv">0</span><span class="sc">:</span>n)<span class="sc">/</span>n</span></code></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="simulation-and-resampling.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb15-2"><a href="simulation-and-resampling.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x,<span class="at">probability =</span> <span class="cn">TRUE</span>,<span class="at">main=</span><span class="st">&quot;Histogram&quot;</span>, <span class="at">col=</span><span class="st">&quot;light blue&quot;</span>,</span>
<span id="cb15-3"><a href="simulation-and-resampling.html#cb15-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">border=</span><span class="st">&quot;white&quot;</span>,<span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">7</span>),<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">4</span>))</span>
<span id="cb15-4"><a href="simulation-and-resampling.html#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(u,<span class="fu">dlnorm</span>(u,<span class="dv">1</span>,.<span class="dv">4</span>),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb15-5"><a href="simulation-and-resampling.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vx,vy,<span class="at">type=</span><span class="st">&quot;l&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;x&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Cumulative Distribution&quot;</span>,<span class="at">main=</span><span class="st">&quot;Empirical cdf&quot;</span>)</span>
<span id="cb15-6"><a href="simulation-and-resampling.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(u,<span class="fu">plnorm</span>(u,<span class="dv">1</span>,.<span class="dv">4</span>),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Analisa_Resiko_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Dari grafik diatas dapat dilihat bahwa garis putus-putus merah tersebut sesuai dengan distribusi lognormal yang dihipotesiskan.</p>
<p>Perlu digaris bawahi bahwa statistik Kolmogorov-Smirnov sama dengan perbedaan terbesar antara distribusi empiris dan hipotesis. Ini <span class="math inline">\(\max_x |F_n(x)-F_0(x)|\)</span>, Di mana <span class="math inline">\(F_0\)</span> adalah distribusi lognormal yang dihipotesiskan, sehingga</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="simulation-and-resampling.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test statistic</span></span>
<span id="cb16-2"><a href="simulation-and-resampling.html#cb16-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="cf">function</span>(data, F0){</span>
<span id="cb16-3"><a href="simulation-and-resampling.html#cb16-3" aria-hidden="true" tabindex="-1"></a>   F <span class="ot">&lt;-</span> <span class="fu">Vectorize</span>(<span class="cf">function</span>(x) <span class="fu">mean</span>((data<span class="sc">&lt;=</span>x)))</span>
<span id="cb16-4"><a href="simulation-and-resampling.html#cb16-4" aria-hidden="true" tabindex="-1"></a>   n <span class="ot">&lt;-</span> <span class="fu">length</span>(data)</span>
<span id="cb16-5"><a href="simulation-and-resampling.html#cb16-5" aria-hidden="true" tabindex="-1"></a>   x <span class="ot">&lt;-</span> <span class="fu">sort</span>(data)</span>
<span id="cb16-6"><a href="simulation-and-resampling.html#cb16-6" aria-hidden="true" tabindex="-1"></a>   d1<span class="ot">=</span><span class="fu">abs</span>(<span class="fu">F</span>(x<span class="fl">+1e-6</span>)<span class="sc">-</span><span class="fu">F0</span>(x<span class="fl">+1e-6</span>))</span>
<span id="cb16-7"><a href="simulation-and-resampling.html#cb16-7" aria-hidden="true" tabindex="-1"></a>   d2<span class="ot">=</span><span class="fu">abs</span>(<span class="fu">F</span>(x<span class="fl">-1e-6</span>)<span class="sc">-</span><span class="fu">F0</span>(x<span class="fl">-1e-6</span>))</span>
<span id="cb16-8"><a href="simulation-and-resampling.html#cb16-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">return</span>(<span class="fu">max</span>(<span class="fu">c</span>(d1,d2)))</span>
<span id="cb16-9"><a href="simulation-and-resampling.html#cb16-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-10"><a href="simulation-and-resampling.html#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="fu">D</span>(x,<span class="cf">function</span>(x) <span class="fu">plnorm</span>(x,<span class="dv">1</span>,.<span class="dv">4</span>))</span></code></pre></div>
<pre><code>## [1] 0.09703627</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="simulation-and-resampling.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(x, plnorm, <span class="at">mean=</span><span class="dv">1</span>, <span class="at">sd=</span><span class="fl">0.4</span>)</span></code></pre></div>
<pre><code>## 
##  Asymptotic one-sample Kolmogorov-Smirnov test
## 
## data:  x
## D = 0.097037, p-value = 0.3031
## alternative hypothesis: two-sided</code></pre>
<p>Secara khusus, untuk menghitung P-value, maka hasilkan ribuan sampel acak dari <span class="math inline">\(LN(1,0.4)\)</span> distribusi (dengan ukuran yang sama), dan menghitung secara empiris distribusi statistik,</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="simulation-and-resampling.html#cb20-1" aria-hidden="true" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fl">1e4</span></span>
<span id="cb20-2"><a href="simulation-and-resampling.html#cb20-2" aria-hidden="true" tabindex="-1"></a>d_KS <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>,ns)</span>
<span id="cb20-3"><a href="simulation-and-resampling.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the test statistics for a large (ns) number of simulated samples</span></span>
<span id="cb20-4"><a href="simulation-and-resampling.html#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>ns) d_KS[s] <span class="ot">&lt;-</span> <span class="fu">D</span>(<span class="fu">rlnorm</span>(n,<span class="dv">1</span>,.<span class="dv">4</span>),<span class="cf">function</span>(x) <span class="fu">plnorm</span>(x,<span class="dv">1</span>,.<span class="dv">4</span>))</span>
<span id="cb20-5"><a href="simulation-and-resampling.html#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="simulation-and-resampling.html#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(d_KS<span class="sc">&gt;</span><span class="fu">D</span>(x,<span class="cf">function</span>(x) <span class="fu">plnorm</span>(x,<span class="dv">1</span>,.<span class="dv">4</span>)))</span></code></pre></div>
<pre><code>## [1] 0.2843</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="simulation-and-resampling.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(d_KS,<span class="at">probability =</span> <span class="cn">TRUE</span>,<span class="at">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="at">border=</span><span class="st">&quot;white&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Test Statistic&quot;</span>,<span class="at">main=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb22-2"><a href="simulation-and-resampling.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(d_KS),<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb22-3"><a href="simulation-and-resampling.html#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">D</span>(x,<span class="cf">function</span>(x) <span class="fu">plnorm</span>(x,<span class="dv">1</span>,.<span class="dv">4</span>)),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="Analisa_Resiko_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Distribusi yang disimulasikan berdasarkan 10.000 sampel acak dirangkum grafik diatas. Di sini, statistik melebihi nilai empiris (0,09704) dalam 28,43%, sedangkan P-value adalah 0,3031. Baik untuk simulasi maupun teoretis P-value, kesimpulannya adalah data tidak memberikan bukti yang cukup untuk menolak hipotesis distribusi lognormal.</p>
<p>Meskipun hanya perkiraan, pendekatan simulasi bekerja dalam berbagai distribusi dan uji statistik tanpa perlu mengembangkan nuansa teori yang mendasari untuk setiap situasi. Berikut ringkasan prosedur untuk mengembangkan distribusi simulasi dan p-value sebagai berikut:</p>
<ol style="list-style-type: decimal">
<li><p>Gambarlah sampel berukuran n , katakanlah, <span class="math inline">\(X_1, \ldots, X_n\)</span>, dari fungsi distribusi yang diketahui <span class="math inline">\(F\)</span>. Hitung statistik minat, dilambangkan sebagai <span class="math inline">\(\hat{\theta}(X_1, \ldots, X_n)\)</span>. Panggil ini <span class="math inline">\(\hat{\theta}^r\)</span> untuk replikasi ke -r .</p></li>
<li><p>Ulangi ini <span class="math inline">\(r=1, \ldots, R\)</span> kali untuk mendapatkan sampel statistik, <span class="math inline">\(\hat{\theta}^1, \ldots,\hat{\theta}^R\)</span>.</p></li>
<li><p>Dari sampel statistik pada Langkah 2, <span class="math inline">\(\{\hat{\theta}^1, \ldots,\hat{\theta}^R\}\)</span>, hitung ukuran ringkasan minat, seperti p-value.</p></li>
</ol>
</div>
</div>
<div id="bootstrap-dan-resampling" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Bootstrap dan Resampling<a href="simulation-and-resampling.html#bootstrap-dan-resampling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Subbab ini akan mempelajari :</p>
<ol style="list-style-type: decimal">
<li><p>Hasilkan distribusi bootstrap nonparametrik untuk statistik minat</p></li>
<li><p>Gunakan distribusi bootstrap untuk menghasilkan estimasi presisi untuk statistik yang diminati, termasuk bias, standar deviasi, dan interval kepercayaan</p></li>
<li><p>Lakukan analisis bootstrap untuk distribusi parametrik</p></li>
</ol>
<div id="dasar-dasar-bootstrap" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Dasar-dasar Bootstrap<a href="simulation-and-resampling.html#dasar-dasar-bootstrap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Metode bootstrap adalah metode berbasis resampling data sampel dengan syarat pengembalian pada datanya dalam menyelesaikan statistik ukuran suatu sampel dengan harapan sampel tersebut mewakili data populai sebenarnya, biasanya ukuran resampling diambil secara ribuan kali agar dapat mewakili data populasinya. Algoritma resamplign umum dengan <span class="math inline">\(\{X_1, \ldots, X_n\}\)</span> untuk menunjukkan sampel asli dan <span class="math inline">\(\{X_1^*, \ldots, X_n^*\}\)</span> menunjukkan undian yang disimulasikan.</p>
<p>Untuk setiap sampel, <span class="math inline">\(n\)</span> merupakan undian simulasi, jumlah yang sama dengan ukuran sampel asli. Untuk membedakan prosedur ini dari simulasi, biasanya digunakan <span class="math inline">\(B\)</span> (untuk bootstrap) sebagai jumlah sampel yang disimulasikan. Sehingga dapat dituliskan <span class="math inline">\(\{X_1^{(b)}, \ldots, X_n^{(b)}\}\)</span>.</p>
<p>Ada dua metode resampling dasar, model-free dan model-based , masing-masing sebagai nonparametrik dan parametrik . Pengundian yang disimulasikan berasal dari fungsi distribusi empiris <span class="math inline">\(F_n(\cdot)\)</span> , jadi setiap undian berasal <span class="math inline">\(\{X_1, \ldots, X_n\}\)</span> dengan probabilitas <span class="math inline">\(1/n\)</span>.</p>
<p><code>Bootstrap Nonparametrik</code></p>
<p>Gagasan bootstrap nonparametrik adalah menggunakan metode transformasi terbalik <span class="math inline">\(F_N\)</span> , fungsi distribusi kumulatif empiris, digambarkan pada grafik dibawah ini.</p>
<p><img src="images/6.2.1-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Karena <span class="math inline">\(F_N\)</span> adalah step-function, <span class="math inline">\(F_n^{-1}\)</span> subtitusi nilai-nilai <span class="math inline">\(\{x_1,\cdots,x_n\}\)</span> sehingga</p>
<ol style="list-style-type: decimal">
<li><p>jika <span class="math inline">\(y\in(0,1/n)\)</span> (dengan probabilitas <span class="math inline">\(1 / n\)</span> ) dengan menggambar nilai terkecil ( <span class="math inline">\(\min\{x_i\}\)</span> )</p></li>
<li><p>jika <span class="math inline">\(y\in(1/n,2/n)\)</span> (dengan probabilitas <span class="math inline">\(1 / n\)</span> ) dengan menggambar nilai terkecil kedua,</p></li>
</ol>
<p>…</p>
<ol start="3" style="list-style-type: decimal">
<li>jika <span class="math inline">\(y\in((n-1)/n,1)\)</span> (dengan probabilitas <span class="math inline">\(1 / n\)</span> ) kami menggambar nilai terbesar ( <span class="math inline">\(\max\{x_i\}\)</span> )</li>
</ol>
<p><img src="images/6.2.1-2.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Menggunakan metode transformasi terbalik dengan <span class="math inline">\(F_N\)</span> berarti pengambilan sampel dari <span class="math inline">\(\{x_1,\cdots,x_n\}\)</span>, dengan probabilitas <span class="math inline">\(1 / n\)</span> . Menghasilkan sampel ukuran bootstrap <span class="math inline">\(B\)</span> berarti pengambilan sampel dari <span class="math inline">\(\{x_1,\cdots,x_n\}\)</span> , dengan probabilitas <span class="math inline">\(1 / n\)</span> , dengan penggantian.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="simulation-and-resampling.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb23-2"><a href="simulation-and-resampling.html#cb23-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb23-3"><a href="simulation-and-resampling.html#cb23-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rexp</span>(n, <span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span>
<span id="cb23-4"><a href="simulation-and-resampling.html#cb23-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb23-5"><a href="simulation-and-resampling.html#cb23-5" aria-hidden="true" tabindex="-1"></a>bootvalues <span class="ot">&lt;-</span> <span class="fu">sample</span>(x, <span class="at">size=</span>m, <span class="at">replace=</span><span class="cn">TRUE</span>)</span></code></pre></div>
</div>
<div id="presisi-bootstrap-bias-standar-deviasi-dan-mean-square-error" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Presisi Bootstrap: Bias, Standar Deviasi, dan Mean Square Error<a href="simulation-and-resampling.html#presisi-bootstrap-bias-standar-deviasi-dan-mean-square-error" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Berikut adalah rangkuman prosedur bootstrap nonparametrik sebagai berikut:</p>
<ol style="list-style-type: decimal">
<li><p>Dari sampel <span class="math inline">\(\{X_1, \ldots, X_n\}\)</span>, gambar sampel berukuran n (dengan penggantian), katakanlah, <span class="math inline">\(X_1^*, \ldots, X_n^*\)</span> . Dari undian yang disimulasikan, hitung statistik minat, dilambangkan sebagai <span class="math inline">\(\hat{\theta}(X_1^*, \ldots, X_n^*)\)</span> . Panggil ini <span class="math inline">\(\hat{\theta}_b^*\)</span> untuk ulangan ke-b .</p></li>
<li><p>Ulangi ini <span class="math inline">\(b=1, \ldots, B\)</span> kali untuk mendapatkan sampel statistik <span class="math inline">\(\hat{\theta}_1^*, \ldots,\hat{\theta}_B^*\)</span>.</p></li>
<li><p>Dari sampel statistik pada Langkah 2,<span class="math inline">\(\{\hat{\theta}_1^*, \ldots, \hat{\theta}_B^*\}\)</span> hitung ukuran ringkasan minat.</p></li>
</ol>
<p>Pada bagian ini, ada tiga langkah ringkasan yaitu bias, standar deviasi, dan mean square error ( MSE ). Tabel dibawah ini merangkum ketiga ukuran. Di Sini, <span class="math inline">\(\overline{\hat{\theta^*}}\)</span> adalah rata-rata dari <span class="math inline">\(\{\hat{\theta}_1^*, \ldots,\hat{\theta}_B^*\}\)</span>.</p>
<p><img src="images/6.2.1-3.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="simulation-and-resampling.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example from Derrig et al</span></span>
<span id="cb24-2"><a href="simulation-and-resampling.html#cb24-2" aria-hidden="true" tabindex="-1"></a>BIData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Data/DerrigResampling.csv&quot;</span>, <span class="at">header =</span>T)</span>
<span id="cb24-3"><a href="simulation-and-resampling.html#cb24-3" aria-hidden="true" tabindex="-1"></a>BIData<span class="sc">$</span>Censored <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(BIData<span class="sc">$</span>AmountPaid <span class="sc">&gt;=</span> BIData<span class="sc">$</span>PolicyLimit)</span>
<span id="cb24-4"><a href="simulation-and-resampling.html#cb24-4" aria-hidden="true" tabindex="-1"></a>BIDataUncensored <span class="ot">&lt;-</span> <span class="fu">subset</span>(BIData, Censored <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb24-5"><a href="simulation-and-resampling.html#cb24-5" aria-hidden="true" tabindex="-1"></a>LER.boot <span class="ot">&lt;-</span> <span class="cf">function</span>(ded, data, indices){</span>
<span id="cb24-6"><a href="simulation-and-resampling.html#cb24-6" aria-hidden="true" tabindex="-1"></a>  resample.data <span class="ot">&lt;-</span> data[indices,]</span>
<span id="cb24-7"><a href="simulation-and-resampling.html#cb24-7" aria-hidden="true" tabindex="-1"></a>  sumClaims <span class="ot">&lt;-</span> <span class="fu">sum</span>(resample.data<span class="sc">$</span>AmountPaid)</span>
<span id="cb24-8"><a href="simulation-and-resampling.html#cb24-8" aria-hidden="true" tabindex="-1"></a>  sumClaims_d <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">pmin</span>(resample.data<span class="sc">$</span>AmountPaid,ded))</span>
<span id="cb24-9"><a href="simulation-and-resampling.html#cb24-9" aria-hidden="true" tabindex="-1"></a>  LER <span class="ot">&lt;-</span>   sumClaims_d<span class="sc">/</span>sumClaims</span>
<span id="cb24-10"><a href="simulation-and-resampling.html#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(LER)  </span>
<span id="cb24-11"><a href="simulation-and-resampling.html#cb24-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-12"><a href="simulation-and-resampling.html#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="simulation-and-resampling.html#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="do">##Derrig et al</span></span>
<span id="cb24-14"><a href="simulation-and-resampling.html#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2019</span>)</span>
<span id="cb24-15"><a href="simulation-and-resampling.html#cb24-15" aria-hidden="true" tabindex="-1"></a>dVec2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4000</span>, <span class="dv">5000</span>, <span class="dv">10500</span>, <span class="dv">11500</span>, <span class="dv">14000</span>, <span class="dv">18500</span>)</span>
<span id="cb24-16"><a href="simulation-and-resampling.html#cb24-16" aria-hidden="true" tabindex="-1"></a>OutBoot <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="fu">length</span>(dVec2),<span class="dv">6</span>)</span>
<span id="cb24-17"><a href="simulation-and-resampling.html#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(dVec2)) {</span>
<span id="cb24-18"><a href="simulation-and-resampling.html#cb24-18" aria-hidden="true" tabindex="-1"></a>OutBoot[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> dVec2[i]</span>
<span id="cb24-19"><a href="simulation-and-resampling.html#cb24-19" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data=</span>BIDataUncensored, <span class="at">statistic=</span>LER.boot, <span class="at">R=</span><span class="dv">1000</span>, <span class="at">ded=</span>dVec2[i])</span>
<span id="cb24-20"><a href="simulation-and-resampling.html#cb24-20" aria-hidden="true" tabindex="-1"></a>OutBoot[i,<span class="dv">2</span>] <span class="ot">&lt;-</span> results<span class="sc">$</span>t0</span>
<span id="cb24-21"><a href="simulation-and-resampling.html#cb24-21" aria-hidden="true" tabindex="-1"></a>biasboot <span class="ot">&lt;-</span> <span class="fu">mean</span>(results<span class="sc">$</span>t)<span class="sc">-</span>results<span class="sc">$</span>t0 <span class="ot">-&gt;</span> OutBoot[i,<span class="dv">3</span>]</span>
<span id="cb24-22"><a href="simulation-and-resampling.html#cb24-22" aria-hidden="true" tabindex="-1"></a>sdboot <span class="ot">&lt;-</span> <span class="fu">sd</span>(results<span class="sc">$</span>t) <span class="ot">-&gt;</span> OutBoot[i,<span class="dv">4</span>]</span>
<span id="cb24-23"><a href="simulation-and-resampling.html#cb24-23" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(results)</span>
<span id="cb24-24"><a href="simulation-and-resampling.html#cb24-24" aria-hidden="true" tabindex="-1"></a>OutBoot[i,<span class="dv">5</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">2</span>]</span>
<span id="cb24-25"><a href="simulation-and-resampling.html#cb24-25" aria-hidden="true" tabindex="-1"></a>OutBoot[i,<span class="dv">6</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">3</span>]</span>
<span id="cb24-26"><a href="simulation-and-resampling.html#cb24-26" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="images/6.2.1-4.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Berdasarkan tabel diatas hasil estimasi bootstrap. Misalnya, di D= 14000 , estimasi nonparametrik LER adalah 0,97678. Ini memiliki perkiraan bias 0,00018 dengan standar deviasi 0,00701. Untuk beberapa aplikasi, mungkin ingin menerapkan estimasi bias ke estimasi asli untuk memberikan estimator yang dikoreksi bias. Untuk ilustrasi ini, biasnya kecil sehingga koreksi semacam itu tidak relevan.</p>
<p>Standar deviasi bootstrap memberikan ukuran presisi. Untuk satu penerapan standar deviasi dapat menggunakan pendekatan normal untuk membuat selang kepercayaan. Misalnya, pada <em>R</em> fungsi <em>boot.ci</em> menghasilkan interval kepercayaan normal sebesar 95%. Ini dihasilkan dengan membuat interval dua kali panjang standar deviasi bootstrap 1,95994, berpusat di sekitar estimator yang dikoreksi bias (1,95994 adalah kuantil ke-97,5 dari distribusi normal). Misalnya, CI 95% normal yang lebih rendah di <span class="math inline">\(D= 14000\)</span> adalah <span class="math inline">\((0.97678-0.00018)- 1.95994*0.00701\)</span>.</p>
<p><code>Contoh 6.2.2.</code> Memperkirakan <span class="math inline">\(\exp(\mu)\)</span> . Bootstrap dapat digunakan untuk mengukur bias estimator, misalnya. Pertimbangkan di sini sampel <span class="math inline">\(\mathbf{x}=\{x_1,\cdots,x_n\}\)</span> adalah rata-rata μ .</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="simulation-and-resampling.html#cb25-1" aria-hidden="true" tabindex="-1"></a>sample_x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.46</span>,<span class="fl">2.80</span>,<span class="fl">3.28</span>,<span class="fl">3.86</span>,<span class="fl">2.85</span>,<span class="fl">3.67</span>,<span class="fl">3.37</span>,<span class="fl">3.40</span>,<span class="fl">5.22</span>,<span class="fl">2.55</span>,</span>
<span id="cb25-2"><a href="simulation-and-resampling.html#cb25-2" aria-hidden="true" tabindex="-1"></a>              <span class="fl">2.79</span>,<span class="fl">4.50</span>,<span class="fl">3.37</span>,<span class="fl">2.88</span>,<span class="fl">1.44</span>,<span class="fl">2.56</span>,<span class="fl">2.00</span>,<span class="fl">2.07</span>,<span class="fl">2.19</span>,<span class="fl">1.77</span>)</span></code></pre></div>
<p>Misalkan kuantitas bunga adalah <span class="math inline">\(\theta=\exp(\mu)\)</span>. Penaksir alami akan menjadi <span class="math inline">\(\widehat{\theta}_1=\exp(\overline{x})\)</span>. Estimator ini bias (karena ketidaksetaraan Jensen) tetapi tidak bias secara asimtotik. Untuk sampel, perkiraannya adalah sebagai berikuT</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="simulation-and-resampling.html#cb26-1" aria-hidden="true" tabindex="-1"></a>(theta_1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">mean</span>(sample_x)))</span></code></pre></div>
<pre><code>## [1] 19.13463</code></pre>
<p>Seseorang dapat menggunakan teorema limit pusat untuk mendapatkan koreksi menggunakan</p>
<p><span class="math display">\[\overline{X}\approx\mathcal{N}\left(\mu,\frac{\sigma^2}{n}\right)\text{ where }\sigma^2=\text{Var}[X_i] ,\]</span></p>
<p>sehingga dengan fungsi pembangkit momen normal didapatkan</p>
<p><span class="math display">\[\mathrm{E}~\left[\exp(\overline{X})\right] \approx \exp\left(\mu+\frac{\sigma^2}{2n}\right) .\]</span></p>
<p>Oleh karena itu, seseorang dapat mempertimbangkan secara alami</p>
<p><span class="math display">\[\widehat{\theta}_2=\exp\left(\overline{x}-\frac{\widehat{\sigma}^2}{2n}\right) .\]</span></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="simulation-and-resampling.html#cb28-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(sample_x)</span>
<span id="cb28-2"><a href="simulation-and-resampling.html#cb28-2" aria-hidden="true" tabindex="-1"></a>(theta_2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">mean</span>(sample_x)<span class="sc">-</span><span class="fu">var</span>(sample_x)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>n)))</span></code></pre></div>
<pre><code>## [1] 18.73334</code></pre>
<p>Sebagai strategi lain, seseorang juga dapat menggunakan pendekatan Taylor untuk mendapatkan penaksir yang lebih akurat (seperti dalam metode delta)</p>
<p><span class="math display">\[g(\overline{x})=g(\mu)+(\overline{x}-\mu)g&#39;(\mu)+(\overline{x}-\mu)^2\frac{g&#39;&#39;(\mu)}{2}+\cdots\]</span></p>
<p>Alternatif selanjutnya adalah menggunakan strategi bootstrap dengan sampel bootstrap <span class="math inline">\(\mathbf{x}^{\ast}_{b}\)</span> sehingga <span class="math inline">\(\overline{x}^{\ast}_{b}\)</span>.</p>
<p><span class="math display">\[\widehat{\theta}_3=\frac{1}{B}\sum_{b=1}^B\exp(\overline{x}^{\ast}_{b}) .\]</span></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="simulation-and-resampling.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb30-2"><a href="simulation-and-resampling.html#cb30-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data=</span>sample_x, </span>
<span id="cb30-3"><a href="simulation-and-resampling.html#cb30-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">statistic=</span><span class="cf">function</span>(y,indices) <span class="fu">exp</span>(<span class="fu">mean</span>(y[indices])), </span>
<span id="cb30-4"><a href="simulation-and-resampling.html#cb30-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">R=</span><span class="dv">1000</span>)</span>
<span id="cb30-5"><a href="simulation-and-resampling.html#cb30-5" aria-hidden="true" tabindex="-1"></a>theta_3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(results<span class="sc">$</span>t)</span></code></pre></div>
<p><img src="images/6.2.2-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p><img src="images/6.2.2-2.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Ini menghasilkan tiga estimator, estimator mentah <span class="math inline">\(\widehat{\theta}_1=19.135\)</span>, koreksi urutan kedua <span class="math inline">\(\widehat{\theta}_2= 18.733\)</span>, dan estimator bootstrap <span class="math inline">\(\widehat{\theta}_3= 19.388\)</span>.</p>
<p>Bagaimana cara kerjanya dengan ukuran sampel yang berbeda? Diasumsikan bahwa <span class="math inline">\(X_i\)</span> dihasilkan dari distribusi lognormal <span class="math inline">\(LN(0,1)\)</span> , sehingga <span class="math inline">\(\mu = \exp(0 + 1/2) = 1.648721\)</span> Dan <span class="math inline">\(\theta = \exp(1.648721)= 5,200326\)</span>. Dengan menggunakan simulasi untuk menggambar ukuran sampel.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="simulation-and-resampling.html#cb31-1" aria-hidden="true" tabindex="-1"></a>param <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb31-2"><a href="simulation-and-resampling.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb31-3"><a href="simulation-and-resampling.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  theta_1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">mean</span>(x))</span>
<span id="cb31-4"><a href="simulation-and-resampling.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  theta_2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">mean</span>(x)<span class="sc">-</span><span class="fu">var</span>(x)<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>n))</span>
<span id="cb31-5"><a href="simulation-and-resampling.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data=</span>x, </span>
<span id="cb31-6"><a href="simulation-and-resampling.html#cb31-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">statistic=</span><span class="cf">function</span>(y,indices) <span class="fu">exp</span>(<span class="fu">mean</span>(y[indices])), </span>
<span id="cb31-7"><a href="simulation-and-resampling.html#cb31-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">R=</span><span class="dv">999</span>)</span>
<span id="cb31-8"><a href="simulation-and-resampling.html#cb31-8" aria-hidden="true" tabindex="-1"></a>  theta_3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(results<span class="sc">$</span>t)</span>
<span id="cb31-9"><a href="simulation-and-resampling.html#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(theta_1,theta_2,theta_3))</span>
<span id="cb31-10"><a href="simulation-and-resampling.html#cb31-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-11"><a href="simulation-and-resampling.html#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2074</span>)</span>
<span id="cb31-12"><a href="simulation-and-resampling.html#cb31-12" aria-hidden="true" tabindex="-1"></a>ns<span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb31-13"><a href="simulation-and-resampling.html#cb31-13" aria-hidden="true" tabindex="-1"></a>est <span class="ot">&lt;-</span> <span class="cf">function</span>(n){</span>
<span id="cb31-14"><a href="simulation-and-resampling.html#cb31-14" aria-hidden="true" tabindex="-1"></a>call_param <span class="ot">&lt;-</span> <span class="cf">function</span>(i) <span class="fu">param</span>(<span class="fu">rlnorm</span>(n,<span class="dv">0</span>,<span class="dv">1</span>))</span>
<span id="cb31-15"><a href="simulation-and-resampling.html#cb31-15" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="fu">Vectorize</span>(call_param)(<span class="dv">1</span><span class="sc">:</span>ns)</span>
<span id="cb31-16"><a href="simulation-and-resampling.html#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(V,<span class="dv">1</span>,median)</span>
<span id="cb31-17"><a href="simulation-and-resampling.html#cb31-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-18"><a href="simulation-and-resampling.html#cb31-18" aria-hidden="true" tabindex="-1"></a>VN<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">15</span>,<span class="dv">100</span>,<span class="at">by=</span><span class="dv">5</span>)</span>
<span id="cb31-19"><a href="simulation-and-resampling.html#cb31-19" aria-hidden="true" tabindex="-1"></a>Est <span class="ot">&lt;-</span> <span class="fu">Vectorize</span>(est)(VN)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="simulation-and-resampling.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">matplot</span>(VN,<span class="fu">t</span>(Est),<span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">lty=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">ylim=</span><span class="fu">exp</span>(<span class="fu">exp</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>))<span class="sc">+</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb32-2"><a href="simulation-and-resampling.html#cb32-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;sample size (n)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;estimator&quot;</span>)</span>
<span id="cb32-3"><a href="simulation-and-resampling.html#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">exp</span>(<span class="fu">exp</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">2</span>)),<span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="dv">1</span>)</span>
<span id="cb32-4"><a href="simulation-and-resampling.html#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;raw estimator&quot;</span>, <span class="st">&quot;second order correction&quot;</span>, <span class="st">&quot;bootstrap&quot;</span>),</span>
<span id="cb32-5"><a href="simulation-and-resampling.html#cb32-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>,<span class="at">lty=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">bty=</span><span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<p><img src="images/6.2.2-3.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Hasil perbandingan dirangkum dalam gambar diatas menunjukkan bahwa estimator bootstrap mendekati nilai parameter sebenarnya untuk hampir semua ukuran sampel. Bias dari ketiga estimator berkurang dengan meningkatnya ukuran sampel.</p>
</div>
<div id="interval-keyakinan" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Interval Keyakinan<a href="simulation-and-resampling.html#interval-keyakinan" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Prosedur bootstrap menghasilkan <span class="math inline">\(B\)</span> bentuk ulang dari <span class="math inline">\(\hat{\theta}_1^*, \ldots,\hat{\theta}_B^*\)</span> dari penaksir <span class="math inline">\(\hat{\theta}\)</span> . Dalam Contoh 6.2.1, dapat dilihat bagaimana menggunakan pendekatan normal standar untuk membuat interval kepercayaan untuk parameter yang diinginkan. Namun, mengingat poin utamanya adalah menggunakan bootstrapping untuk menghindari ketergantungan pada asumsi perkiraan normalitas, tidak mengherankan jika tersedia interval kepercayaan alternatif.</p>
<p>Untuk estimator <span class="math inline">\(\hat{\theta}\)</span> , interval kepercayaan bootstrap dasar adalah</p>
<p><span class="math display">\[\begin{equation}
  \left(2 \hat{\theta} - q_U, 2 \hat{\theta} - q_L \right) ,
\tag{6.2}
\end{equation}\]</span></p>
<p>Di mana <span class="math inline">\(q_L\)</span> Dan <span class="math inline">\(q_U\)</span> adalah kuantil 2,5% bawah dan atas dari sampel bootstrap <span class="math inline">\(\hat{\theta}_1^*, \ldots,\hat{\theta}_B^*\)</span></p>
<p>Untuk melihat dari mana asalnya, mula-mula <span class="math inline">\((q_L, q_U)\)</span> menyediakan interval 95% untuk <span class="math inline">\(\hat{\theta}_1^*, \ldots,\hat{\theta}_B^*\)</span> . Jadi, untuk acak <span class="math inline">\(\hat{\theta}_b^*\)</span>, ada kemungkinan 95% itu <span class="math inline">\(q_L \le \hat{\theta}_b^* \le q_U\)</span>. Membalikkan pertidaksamaan dan menjumlahkan <span class="math inline">\(\hat{\theta}\)</span> ke setiap sisi memberikan interval 95%</p>
<p><span class="math display">\[\hat{\theta} -q_U \le \hat{\theta} - \hat{\theta}_b^* \le  \hat{\theta} -q_L .\]</span></p>
<p>Jadi, <span class="math inline">\(\left( \hat{\theta}-q_U, \hat{\theta} -q_L\right)\)</span> adalah interval 95% untuk <span class="math inline">\(\hat{\theta} - \hat{\theta}_b^*\)</span>. Ide perkiraan bootstrap mengatakan bahwa ini juga merupakan interval 95% untuk <span class="math inline">\(\theta - \hat{\theta}\)</span>. Dengan menambahkan <span class="math inline">\(\hat{\theta}\)</span> ke setiap sisi memberikan interval 95% dalam persamaan diatas.</p>
<p>Banyak alternatif interval bootstrap yang tersedia. Yang paling mudah dijelaskan adalah interval bootstrap persentil yang didefinisikan sebagai <span class="math inline">\((q_L,q_U)\)</span>.</p>
<p><code>Contoh 6.2.3.</code> Klaim Cidera Tubuh dan Tindakan Risiko. Untuk melihat bagaimana interval kepercayaan bootstrap bekerja, dengan kembali ke klaim otomatis cedera tubuh yang dipertimbangkan dalam Contoh 6.2.1 . Alih-alih rasio eliminasi kerugian, misalkan ingin memperkirakan persentil ke-95 <span class="math inline">\(F^{-1}(0.95)\)</span> dan ukuran didefinisikan sebagai</p>
<p><span class="math display">\[TVaR_{0.95}[X] = \mathrm{E}[X | X &gt; F^{-1}(0.95)] .\]</span></p>
<p>Pengukuran ini disebut dengan ekor nilai berisiko; itu adalah nilai yang diharapkan dari X bersyarat X melebihi persentil ke-95. Bagian 10.2 menjelaskan bagaimana quantiles dan tail value-at-risk adalah dua contoh paling penting dari apa yang disebut sebagai ukuran risiko . Untuk saat ini, hanya akan menganggap ini sebagai ukuran yang ingin diperkirakan. Untuk persentil, dengan menggunakan estimator nonparametrik <span class="math inline">\(F^{-1}_n(0.95)\)</span> didefinisikan dalam Bagian 4.1.1.3 . Untuk tail value-at-risk, menggunakan prinsip plug-in untuk menentukan estimator nonparametrik</p>
<p><span class="math display">\[TVaR_{n,0.95}[X] = \frac{\sum_{i=1}^n X_i I(X_i &gt; F^{-1}_n(0.95))}{\sum_{i=1}^n I(X_i &gt; F^{-1}_n(0.95))} ~.\]</span></p>
<p>Dalam ungkapan ini, penyebut menghitung jumlah pengamatan yang melebihi persentil ke-95 <span class="math inline">\(F^{-1}_n(0.95)\)</span> . Pembilang menjumlahkan kerugian untuk pengamatan yang melebihi <span class="math inline">\(F^{-1}_n(0.95)\)</span> . Tabel dibawah ini merangkum penaksir untuk pecahan terpilih.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="simulation-and-resampling.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example from Derrig et al</span></span>
<span id="cb33-2"><a href="simulation-and-resampling.html#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#BIData &lt;- read.csv(&quot;Data/DerrigResampling.csv&quot;, header =T)</span></span>
<span id="cb33-3"><a href="simulation-and-resampling.html#cb33-3" aria-hidden="true" tabindex="-1"></a>BIData<span class="sc">$</span>Censored <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(BIData<span class="sc">$</span>AmountPaid <span class="sc">&gt;=</span> BIData<span class="sc">$</span>PolicyLimit)</span>
<span id="cb33-4"><a href="simulation-and-resampling.html#cb33-4" aria-hidden="true" tabindex="-1"></a>BIDataUncensored <span class="ot">&lt;-</span> <span class="fu">subset</span>(BIData, Censored <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb33-5"><a href="simulation-and-resampling.html#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="simulation-and-resampling.html#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)</span>
<span id="cb33-7"><a href="simulation-and-resampling.html#cb33-7" aria-hidden="true" tabindex="-1"></a>PercentVec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.98</span>)</span>
<span id="cb33-8"><a href="simulation-and-resampling.html#cb33-8" aria-hidden="true" tabindex="-1"></a>OutBoot1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="dv">5</span>,<span class="dv">10</span>)</span>
<span id="cb33-9"><a href="simulation-and-resampling.html#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(PercentVec)) {</span>
<span id="cb33-10"><a href="simulation-and-resampling.html#cb33-10" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> PercentVec[i]</span>
<span id="cb33-11"><a href="simulation-and-resampling.html#cb33-11" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data=</span>BIDataUncensored<span class="sc">$</span>AmountPaid,</span>
<span id="cb33-12"><a href="simulation-and-resampling.html#cb33-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">statistic=</span><span class="cf">function</span>(X,indices)</span>
<span id="cb33-13"><a href="simulation-and-resampling.html#cb33-13" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">quantile</span>(X[indices],PercentVec[i]),</span>
<span id="cb33-14"><a href="simulation-and-resampling.html#cb33-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">R=</span><span class="dv">1000</span>)</span>
<span id="cb33-15"><a href="simulation-and-resampling.html#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (i<span class="sc">==</span><span class="dv">1</span>){bootreal <span class="ot">&lt;-</span> results<span class="sc">$</span>t}</span>
<span id="cb33-16"><a href="simulation-and-resampling.html#cb33-16" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">2</span>] <span class="ot">&lt;-</span> results<span class="sc">$</span>t0</span>
<span id="cb33-17"><a href="simulation-and-resampling.html#cb33-17" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">mean</span>(results<span class="sc">$</span>t)<span class="sc">-</span>results<span class="sc">$</span>t0 </span>
<span id="cb33-18"><a href="simulation-and-resampling.html#cb33-18" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">sd</span>(results<span class="sc">$</span>t) </span>
<span id="cb33-19"><a href="simulation-and-resampling.html#cb33-19" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(results, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;norm&quot;</span>, <span class="st">&quot;basic&quot;</span>, <span class="st">&quot;perc&quot;</span>))</span>
<span id="cb33-20"><a href="simulation-and-resampling.html#cb33-20" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">5</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">2</span>]</span>
<span id="cb33-21"><a href="simulation-and-resampling.html#cb33-21" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">6</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">3</span>]</span>
<span id="cb33-22"><a href="simulation-and-resampling.html#cb33-22" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">7</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>basic[<span class="dv">4</span>]</span>
<span id="cb33-23"><a href="simulation-and-resampling.html#cb33-23" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">8</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>basic[<span class="dv">5</span>]</span>
<span id="cb33-24"><a href="simulation-and-resampling.html#cb33-24" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">9</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>percent[<span class="dv">4</span>]</span>
<span id="cb33-25"><a href="simulation-and-resampling.html#cb33-25" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">10</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>percent[<span class="dv">5</span>]</span>
<span id="cb33-26"><a href="simulation-and-resampling.html#cb33-26" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="images/6.2.3-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Misalnya, ketika pecahannya adalah 0,50, dapat melihat bahwa kuantil 2,5 bawah dan atas dari simulasi bootstrap adalah <span class="math inline">\(q_L= 6000\)</span> dan <span class="math inline">\(q_U= 6700\)</span>. Ini membentuk interval kepercayaan bootstrap persentil. Dengan estimator nonparametrik <span class="math inline">\(6500\)</span>, ini menghasilkan batas bawah dan atas interval kepercayaan dasar masing-masing <span class="math inline">\(6300\)</span> dan <span class="math inline">\(7000\)</span>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="simulation-and-resampling.html#cb34-1" aria-hidden="true" tabindex="-1"></a>CTE.boot <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices, RiskLevel){</span>
<span id="cb34-2"><a href="simulation-and-resampling.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  resample.data <span class="ot">&lt;-</span> data[indices,]</span>
<span id="cb34-3"><a href="simulation-and-resampling.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  X <span class="ot">&lt;-</span> resample.data<span class="sc">$</span>AmountPaid</span>
<span id="cb34-4"><a href="simulation-and-resampling.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  cutoff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(X, RiskLevel)</span>
<span id="cb34-5"><a href="simulation-and-resampling.html#cb34-5" aria-hidden="true" tabindex="-1"></a>  CTE <span class="ot">&lt;-</span> <span class="fu">sum</span>(X<span class="sc">*</span>(X <span class="sc">&gt;</span> cutoff))<span class="sc">/</span><span class="fu">sum</span>(X <span class="sc">&gt;</span> cutoff)</span>
<span id="cb34-6"><a href="simulation-and-resampling.html#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(CTE) </span>
<span id="cb34-7"><a href="simulation-and-resampling.html#cb34-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-8"><a href="simulation-and-resampling.html#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="simulation-and-resampling.html#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2017</span>)  </span>
<span id="cb34-10"><a href="simulation-and-resampling.html#cb34-10" aria-hidden="true" tabindex="-1"></a>PercentVec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.98</span>)</span>
<span id="cb34-11"><a href="simulation-and-resampling.html#cb34-11" aria-hidden="true" tabindex="-1"></a>OutBoot1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="dv">5</span>,<span class="dv">10</span>)</span>
<span id="cb34-12"><a href="simulation-and-resampling.html#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(PercentVec)) {</span>
<span id="cb34-13"><a href="simulation-and-resampling.html#cb34-13" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> PercentVec[i]</span>
<span id="cb34-14"><a href="simulation-and-resampling.html#cb34-14" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data=</span>BIDataUncensored, <span class="at">statistic=</span>CTE.boot, <span class="at">R=</span><span class="dv">1000</span>, <span class="at">RiskLevel=</span>PercentVec[i])</span>
<span id="cb34-15"><a href="simulation-and-resampling.html#cb34-15" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">2</span>] <span class="ot">&lt;-</span> results<span class="sc">$</span>t0</span>
<span id="cb34-16"><a href="simulation-and-resampling.html#cb34-16" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">mean</span>(results<span class="sc">$</span>t)<span class="sc">-</span>results<span class="sc">$</span>t0 </span>
<span id="cb34-17"><a href="simulation-and-resampling.html#cb34-17" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">sd</span>(results<span class="sc">$</span>t) </span>
<span id="cb34-18"><a href="simulation-and-resampling.html#cb34-18" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">boot.ci</span>(results, <span class="at">type =</span> <span class="fu">c</span>(<span class="st">&quot;norm&quot;</span>, <span class="st">&quot;basic&quot;</span>, <span class="st">&quot;perc&quot;</span>))</span>
<span id="cb34-19"><a href="simulation-and-resampling.html#cb34-19" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">5</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">2</span>]</span>
<span id="cb34-20"><a href="simulation-and-resampling.html#cb34-20" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">6</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>normal[<span class="dv">3</span>]</span>
<span id="cb34-21"><a href="simulation-and-resampling.html#cb34-21" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">7</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>basic[<span class="dv">4</span>]</span>
<span id="cb34-22"><a href="simulation-and-resampling.html#cb34-22" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">8</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>basic[<span class="dv">5</span>]</span>
<span id="cb34-23"><a href="simulation-and-resampling.html#cb34-23" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">9</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>percent[<span class="dv">4</span>]</span>
<span id="cb34-24"><a href="simulation-and-resampling.html#cb34-24" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">10</span>] <span class="ot">&lt;-</span> temp<span class="sc">$</span>percent[<span class="dv">5</span>]</span>
<span id="cb34-25"><a href="simulation-and-resampling.html#cb34-25" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div>
<p><img src="images/6.2.3-2.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Tabel di atas menunjukkan kalkulasi serupa untuk tail value-at-risk. Dalam setiap kasus, dapat melihat bahwa deviasi standar bootstrap meningkat seiring dengan peningkatan fraksi. Hal ini karena ada lebih sedikit pengamatan untuk memperkirakan kuantil seiring meningkatnya fraksi, yang menyebabkan ketidaktepatan yang lebih besar. Interval kepercayaan juga menjadi lebih lebar. Menariknya, tampaknya tidak ada pola yang sama dalam estimasi bias tersebut.</p>
</div>
<div id="bootstrap-parametrik" class="section level3 hasAnchor" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Bootstrap Parametrik<a href="simulation-and-resampling.html#bootstrap-parametrik" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Gagasan dari bootstrap nonparametrik adalah untuk mengambil sampel ulang dengan menggambar variabel independen dari fungsi distribusi kumulatif empiris <span class="math inline">\(F_n\)</span>. Sebaliknya, dengan bootstrap parametrik, kami menarik variabel independen dari <span class="math inline">\(F_{\widehat{\theta}}\)</span> di mana distribusi yang mendasarinya diasumsikan dalam keluarga parametrik <span class="math inline">\(\mathcal{F}=\{F_{\theta},\theta\in\Theta\}\)</span> . Biasanya, parameter dari distribusi ini diperkirakan berdasarkan sampel dan dinotasikan sebagai <span class="math inline">\(\hat{\theta}\)</span>.</p>
<p><code>contoh 6.2.4.</code> distribusi lognormal. Pertimbangkan lagi kumpulan datanya</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="simulation-and-resampling.html#cb35-1" aria-hidden="true" tabindex="-1"></a>sample_x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.46</span>,<span class="fl">2.80</span>,<span class="fl">3.28</span>,<span class="fl">3.86</span>,<span class="fl">2.85</span>,<span class="fl">3.67</span>,<span class="fl">3.37</span>,<span class="fl">3.40</span>,</span>
<span id="cb35-2"><a href="simulation-and-resampling.html#cb35-2" aria-hidden="true" tabindex="-1"></a>              <span class="fl">5.22</span>,<span class="fl">2.55</span>,<span class="fl">2.79</span>,<span class="fl">4.50</span>,<span class="fl">3.37</span>,<span class="fl">2.88</span>,<span class="fl">1.44</span>,<span class="fl">2.56</span>,<span class="fl">2.00</span>,<span class="fl">2.07</span>,<span class="fl">2.19</span>,<span class="fl">1.77</span>)</span></code></pre></div>
<p>Bootstrap klasik (nonparametrik) didasarkan pada contoh berikut.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="simulation-and-resampling.html#cb36-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sample</span>(sample_x,<span class="at">replace=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p>Sebagai gantinya, untuk bootstrap parametrik harus mengasumsikan bahwa distribusi dari <span class="math inline">\(x_i\)</span> adalah dari kelompok tertentu. Sebagai contoh, kode berikut menggunakan distribusi lognormal.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="simulation-and-resampling.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb37-2"><a href="simulation-and-resampling.html#cb37-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fitdistr</span>(sample_x, dlnorm, <span class="fu">list</span>(<span class="at">meanlog =</span> <span class="dv">1</span>, <span class="at">sdlog =</span> <span class="dv">1</span>))</span>
<span id="cb37-3"><a href="simulation-and-resampling.html#cb37-3" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div>
<p><img src="images/6.2.4-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="simulation-and-resampling.html#cb38-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="fu">length</span>(sample_x), <span class="at">meanlog=</span>fit<span class="sc">$</span>estimate[<span class="dv">1</span>], <span class="at">sdlog=</span>fit<span class="sc">$</span>estimate[<span class="dv">2</span>])</span></code></pre></div>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="simulation-and-resampling.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2074</span>)</span>
<span id="cb39-2"><a href="simulation-and-resampling.html#cb39-2" aria-hidden="true" tabindex="-1"></a>CV <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>,<span class="fl">1e5</span>,<span class="dv">2</span>)</span>
<span id="cb39-3"><a href="simulation-and-resampling.html#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(s <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(CV)){</span>
<span id="cb39-4"><a href="simulation-and-resampling.html#cb39-4" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(sample_x,<span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb39-5"><a href="simulation-and-resampling.html#cb39-5" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="fu">length</span>(sample_x), <span class="at">meanlog=</span>fit<span class="sc">$</span>estimate[<span class="dv">1</span>], <span class="at">sdlog=</span>fit<span class="sc">$</span>estimate[<span class="dv">2</span>])</span>
<span id="cb39-6"><a href="simulation-and-resampling.html#cb39-6" aria-hidden="true" tabindex="-1"></a>CV[s,] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">sd</span>(x1)<span class="sc">/</span><span class="fu">mean</span>(x1),<span class="fu">sd</span>(x2)<span class="sc">/</span><span class="fu">mean</span>(x2))</span>
<span id="cb39-7"><a href="simulation-and-resampling.html#cb39-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="simulation-and-resampling.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(CV[,<span class="dv">1</span>]),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Coefficient of Variation&quot;</span>, <span class="at">lty=</span><span class="dv">1</span>)</span>
<span id="cb40-2"><a href="simulation-and-resampling.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(CV[,<span class="dv">2</span>]),<span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb40-3"><a href="simulation-and-resampling.html#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">sd</span>(sample_x)<span class="sc">/</span><span class="fu">mean</span>(sample_x),<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb40-4"><a href="simulation-and-resampling.html#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="fu">c</span>(<span class="st">&quot;nonparametric&quot;</span>,<span class="st">&quot;parametric(LN)&quot;</span>),</span>
<span id="cb40-5"><a href="simulation-and-resampling.html#cb40-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>),<span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="at">bty=</span><span class="st">&quot;n&quot;</span></span></code></pre></div>
<p><img src="images/6.2.3-3.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Grafik di atas membandingkan distribusi bootstrap untuk koefisien variasi, yang satu berdasarkan pendekatan nonparametrik dan yang lainnya berdasarkan pendekatan parametrik, dengan asumsi distribusi lognormal.</p>
<p><code>Contoh 6.2.5.</code> Pengamatan yang Disensor Bootstrap.</p>
<p>Bootstrap parametrik menarik realisasi simulasi dari perkiraan parametrik dari fungsi distribusi. Dengan cara yang sama, sehingga dapat menggambar realisasi simulasi dari estimasi fungsi distribusi. Sebagai salah satu contoh, dengan mengambil dari estimasi yang dihaluskan dari fungsi distribusi yang diperkenalkan di Bagian 4.1.1.4 . Kasus khusus lainnya, yang dipertimbangkan di sini adalah menggambar estimasi dari estimator Kaplan-Meier yang dibahas di Bagian 4.3.2.2. Dengan cara ini, dapat ditangani pengamatan yang disensor.</p>
<p>Secara khusus, kembali ke data cedera tubuh pada Contoh 6.2.1 dan 6.2.3 tetapi sekarang menyertakan 17 klaim yang disensor oleh batasan kebijakan. Dalam Contoh 4.3.6 menggunakan kumpulan data lengkap ini untuk mengestimasi estimator Kaplan-Meier dari fungsi survival yang diperkenalkan di Bagian 4.3.2.2 . Tabel 6.6 menyajikan estimasi bootstrap kuantil dari estimator fungsi survival Kaplan-Meier. Ini termasuk perkiraan presisi bootstrap, bias dan standar deviasi, serta interval kepercayaan dasar 95%.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="simulation-and-resampling.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example from Derrig et al</span></span>
<span id="cb41-2"><a href="simulation-and-resampling.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)                <span class="co"># for Surv(), survfit()</span></span>
<span id="cb41-3"><a href="simulation-and-resampling.html#cb41-3" aria-hidden="true" tabindex="-1"></a>BIData<span class="sc">$</span>UnCensored <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(BIData<span class="sc">$</span>AmountPaid <span class="sc">&lt;</span> BIData<span class="sc">$</span>PolicyLimit)</span>
<span id="cb41-4"><a href="simulation-and-resampling.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="do">## KM estimate</span></span>
<span id="cb41-5"><a href="simulation-and-resampling.html#cb41-5" aria-hidden="true" tabindex="-1"></a>KM0 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(AmountPaid, UnCensored) <span class="sc">~</span> <span class="dv">1</span>,  </span>
<span id="cb41-6"><a href="simulation-and-resampling.html#cb41-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">type=</span><span class="st">&quot;kaplan-meier&quot;</span>, <span class="at">data=</span>BIData)</span>
<span id="cb41-7"><a href="simulation-and-resampling.html#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="simulation-and-resampling.html#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2019</span>)</span>
<span id="cb41-9"><a href="simulation-and-resampling.html#cb41-9" aria-hidden="true" tabindex="-1"></a>PercentVec <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.80</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.98</span>)</span>
<span id="cb41-10"><a href="simulation-and-resampling.html#cb41-10" aria-hidden="true" tabindex="-1"></a>OutBoot1 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>,<span class="dv">5</span>,<span class="dv">6</span>)</span>
<span id="cb41-11"><a href="simulation-and-resampling.html#cb41-11" aria-hidden="true" tabindex="-1"></a>KM.survobj <span class="ot">&lt;-</span> <span class="fu">Surv</span>(BIData<span class="sc">$</span>AmountPaid, BIData<span class="sc">$</span>UnCensored) </span>
<span id="cb41-12"><a href="simulation-and-resampling.html#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(PercentVec)) {</span>
<span id="cb41-13"><a href="simulation-and-resampling.html#cb41-13" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">1</span>] <span class="ot">&lt;-</span> PercentVec[i]</span>
<span id="cb41-14"><a href="simulation-and-resampling.html#cb41-14" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">bootkm</span>(KM.survobj, <span class="at">q=</span><span class="dv">1</span><span class="sc">-</span>PercentVec[i], <span class="at">B=</span><span class="dv">1000</span>, <span class="at">pr =</span> <span class="cn">FALSE</span>)</span>
<span id="cb41-15"><a href="simulation-and-resampling.html#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (i<span class="sc">==</span><span class="dv">1</span>){bootreal <span class="ot">&lt;-</span> results}</span>
<span id="cb41-16"><a href="simulation-and-resampling.html#cb41-16" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">quantile</span>(KM0, PercentVec[i])<span class="sc">$</span>quantile</span>
<span id="cb41-17"><a href="simulation-and-resampling.html#cb41-17" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="fu">mean</span>(results)<span class="sc">-</span>OutBoot1[i,<span class="dv">2</span>]</span>
<span id="cb41-18"><a href="simulation-and-resampling.html#cb41-18" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">sd</span>(results) </span>
<span id="cb41-19"><a href="simulation-and-resampling.html#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="co"># temp &lt;- boot.ci(results, type = c(&quot;norm&quot;,  &quot;basic&quot;,&quot;perc&quot;))</span></span>
<span id="cb41-20"><a href="simulation-and-resampling.html#cb41-20" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>OutBoot1[i,<span class="dv">2</span>]<span class="sc">-</span><span class="fu">quantile</span>(results,.<span class="dv">975</span>, <span class="at">type=</span><span class="dv">6</span>)</span>
<span id="cb41-21"><a href="simulation-and-resampling.html#cb41-21" aria-hidden="true" tabindex="-1"></a>OutBoot1[i,<span class="dv">6</span>] <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>OutBoot1[i,<span class="dv">2</span>]<span class="sc">-</span><span class="fu">quantile</span>(results,.<span class="dv">025</span>, <span class="at">type=</span><span class="dv">6</span>)</span>
<span id="cb41-22"><a href="simulation-and-resampling.html#cb41-22" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><img src="images/6.2.3-4.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Hasil pada tabel di atas konsisten dengan hasil untuk subsampel tanpa sensor pada Tabel 6.4 . Pada tabel di atas tercatat kesulitan dalam memperkirakan kuantil pada pecahan besar karena penyensoran. Namun, untuk fraksi berukuran sedang (0,50, 0,80, dan 0,90), estimasi nonparametrik Kaplan-Meier (KM NP) dari kuantil konsisten dengan Tabel 6.4 . Standar Deviasi bootstrap lebih kecil pada 0,50 (sesuai dengan median) tetapi lebih besar pada level 0,80 dan 0,90. Analisis data tersensor yang dirangkum dalam tabel di atas menggunakan lebih banyak data daripada analisis subsampel tanpa sensor pada Tabel 6.4 , tetapi juga mengalami kesulitan dalam mengekstraksi informasi untuk kuantil besar.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="aggregate-loss-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="premium-foundations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dsciencelabs/Analisa_Resiko/edit/master/chapters/06-SimulationNoKableExtra.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Analisa_Resiko.pdf", "Analisa_Resiko.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
